### ISSUE TITLE
Allow BindsInstance to work with module hierarchy

### ISSUE THREAD

**Issue by devinrsmith** [google/dagger#1067]
It would be nice if using `@BindsInstance` in an explicit builder still allowed for the inclusion of the implicit builder module methods defined in the modules hierarchy to alleviate this error:

```
@Component.Builder is missing setters for required modules or components: [XXX]
```

This would be *OK* if I was able to be a bit more explicit and verbose with my builders, but being more explicit forces me to make sure that the module *isn't* anywhere in the hierarchy (which is a big problem for re-use). Otherwise, this happens:

```
error: XXX is bound multiple times
```
 
I've worked up some code to more clearly illustrate what I'm trying to achieve:

https://gist.github.com/devinrsmith/a0235fdb950c2507e10d8b303f041002

Is there any way to use `@BindsInstance` and implicit modules defined in the hierarchy?

**Comment by ronshapiro** [comment]
Unfortunately not.

We typically prefer the explicitly defined component builders, since we don't like exposing APIs when we don't have to. Self-defined component builders also are a good way of checking that you know all of the external elements that need to be passed to the component - having that would lead to more confusion than the few extra lines of code that it would save.
