### ISSUE TITLE
Allow multiple scopes from component dependencies for Android performance refactoring

### ISSUE THREAD

**Issue by bubenheimer** [google/dagger#1075]
@ronshapiro's droidcon NYC 2017 talk (https://www.youtube.com/watch?v=PBrhRvhF00k) suggests structuring Android apps with component dependencies from multiple Gradle modules for build performance reasons. The reasoning seems sound, and the resulting code structure appears natural, yet the approach is rather limited in the real world because of Dagger's limitation to only a single scoped component dependency. I generally expect to have a certain number of genuine singleton entities spread across different dependent component functionalities. I assume I can generally find ugly and time–consuming individual workarounds, but that defeats the purpose. Relaxing Dagger's restriction would seem a much cleaner solution and would turn this desirable pattern into more than hand–waving.

Related issues are https://github.com/google/dagger/issues/782 and https://github.com/google/dagger/issues/636.

**Comment by BrantApps** [comment]
@bubenheimer - to achieve the singleton effect without resorting to hand-crafting the double check then you can create your expensive/globally-stateful objects within Android's near-enough-once-per-process-singleton `android.app.Application` subclass and then bind those instances into the 'child' modules.

Adopting this approach permits the component-to-component dependencies (that I too enjoy within layered/heavily modularised clients) but perhaps gives your modules an unexpected(?) contract...i.e. your API client module is initialised or "installed" with Guice-like nomenclature with a `Retrofit` binding. Incidentally, this approach is useful if your are making an SDK to be reused by clients you don't control.

I don't think this question will get much love since the relaxation you describe would mean another product!  If you can move away from comp-to-comp to subcomponents then you can start making use of finer grained scopes - personally, I rarely find the need for these lifecycles on Android. As I mentioned on a related ticket, the Android OS at least has other lifecycle managers that do the job. These of course will not be per-process singletons, but "local" living just longer than the classes they control. But I'm sure you knew that.

Give the `@BindInstance` route a go. Or if you are pre-whenever `BindInstance` became a think, pass it as a module constructor arg. I was sceptical of moaaar annotation processing but having just completed the migration to the `SubComponent.Builder` / `Component.Builder` the resulting code reads more naturally, what's left that is. 😄 `static` provisioning has a perf bump too I've read (not microbenchmarked!)

All the best.

**Comment by bubenheimer** [comment]
A general approach I conceived a while back for emulating multiple scoped component dependencies replicates a component's provision methods into a module that takes a scoped component instance as a constructor parameter and passes through the component's scoped and unscoped bindings. The module is a dependency of a new "facade" component that also replicates the original component's provision methods. This preserves the original component's scope without the scope being exposed to the outside; the facade component serves as the component dependency in place of the original. The performance impact is negligible. There is some boilerplate, but it can be reduced via type inheritance. I have an example up at https://github.com/bubenheimer/daggercomponentdependencies

Despite its relative ease It is unfortunate that this kind of boilerplate is needed to work around a limitation that from my perspective seems merely artificial.

**Comment by PaulWoitaschek** [comment]
@bubenheimer
I don't currently have the time to check if this works but can't you reduce the boilerplate by using kotlin's delegation?

So this:
```java
@Module
public final class ThirdFacadeModule implements ThirdComponent {
    private final ThirdBaseComponent component;

    public ThirdFacadeModule(
            final ThirdBaseComponent component) {
        this.component = component;
    }

    @Override
    @Provides
    public long longValue() {
        return component.longValue();
    }
}
```

could become this:

```kotlin
@Module
class ThirdFacadeModule(component : ThirdBaseComponent) : ThirdComponent by component
```

**Comment by bubenheimer** [comment]
Addressed by https://github.com/google/dagger/pull/1766. Would be curious what brought about the change in direction; I was under the impression that the Dagger team was previously opposed to this design change. Just a change in maintainers and a large number of comments, duplicate & related issues?

**Comment by Chang-Eric** [comment]
I wouldn't say the Dagger team necessarily recommends all of the design patterns this change enables, but since Dagger supports component dependencies through just plain interfaces the workaround was fairly well-known and simple and just adding more boilerplate. In addition, there are some known valid patterns combining usually two different scopes that cannot be supported via subcomponents so it made sense to make this change.
