### ISSUE TITLE
Stop releasing as SNAPSHOT

### ISSUE THREAD

**Issue by mgrzechocinski** [google/dagger#109]
Hey, due to the "improvements" introduced in the latest SNAPSHOT release, like #108, I'd like to ask one question. 

Since [Dagger2 is feature complete](http://youtu.be/oK_XtfXPkqw?t=38m15s) and you're squashing bugs and updating some docs, why don't you guys release current version as something like v2.0-beta1, or even 2.0 and then, when release bugfix versions, 2.0-beta2 or 2.0.1?

Continuing releasing under 2.0-SNAPSHOT leads all current users to failures occurring on random machines, where Gradle decided to silently update SNAPSHOT dependencies. Actually, it's the same situation as it was with ADT. When introducing new build system, based on Gradle, Xavier from Google said that they will release every build tools with particular version so that any update won't break projects which are built by previous version. Then, it's up to developer when he or she want to upgrade to new version. 

IMHO it's high time to release Dager2 with concrete version, isn't it?

**Comment by radzio** [comment]
@up +1

**Comment by balauru** [comment]
+1

**Comment by artem-zinnatullin** [comment]
:-1: Dagger 2 is not ready for non SNAPSHOT release, as we all can see because of issues like #108 mentioned by @mgrzechocinski which are breaking the API.

I agree, that Dagger team can release snapshot with versioning according to [Semantic Versioning v2.0.0 ](http://semver.org), it will be great.

If you want stability from SNAPSHOT — download jars from mavenCentral and put them into your projects, don't let your build system to change things on the fly.

**Comment by sleroux** [comment]
+1 Had an issue with the latest push to snapshot - still trying to boil it down into a simple example for an issue request...

**Comment by JakeWharton** [comment]
No. If you want a snapshot version to break your code then don't depend on it. There's plenty of other safe, hermetic ways to get Dagger 2 into your app. This is a terrible request to make.

**Comment by mgrzechocinski** [comment]
What are the "other safe and hermetic ways to get Dagger2 into your app"? Hope you won't ask us to  keep Dagger2 jar within source code like in old 90ies... 

I'm not against developing software under SNAPSHOT in overall. It's extremely useful in some situations, especially when working on multi-module apps. I also know, that depending on a SNAPSHOT might break my code, I'm aware of it.

I just think that Dagger2, as feature completed library is no longer a SNAPSHOT and should be released with fixed versions, so that real projects (=not simple examples) which can give you a real feedback won't break after ones push new version. Alpha, Beta, RC, there are plenty of classifiers to use until releasing as final v2.0.

**Comment by JakeWharton** [comment]
Why do you think it's feature complete? Features are landing in every sync from Google's internal repo.

**Comment by mgrzechocinski** [comment]
I pointed to Gregory's presentation when opening this request and also trying to being up to date with the latest commits.

**Comment by JakeWharton** [comment]
I'll tell the next pull request to watch the presentation. Deploy a jar to your internal artifact repository or check it in temporarily. These types of issues is what makes people burn out on open source and should be closed with extreme prejudice.

**Comment by mgrzechocinski** [comment]
I watched it and because I used Dagger1 a lot, I decided to switch to v2. 

Frankly, what makes me personally burnt out on OS is trying to help by giving feedback from a real project and failing it under random&unclear circumstances just because you can't use 0.x, Alpha, Beta or any other versioning rule, saying "don't depend on it". 

I'll check-in previous JAR version, feeling like in ANT times. EOT for me.

**Comment by JakeWharton** [comment]
Who said "don't depend on it"? If you depend on a snapshot, you have explicitly opted in to breaking changes without notice. Stop blaming others and just fix your build.

**Comment by tbroyer** [comment]
@mgrzechocinski How about using timestamped snapshots [1] with a repository manager (to make sure it's not pruned from the repository; you set your own strategy rather than relying on the Sonatype OSS one)
Or you can “fork” and release/deploy non-snapshots you can rely on (or snapshots under your own coordinates; the idea being that **you** choose when you update).

[1] Maven has [`mvn versions:lock-snapshots`](http://mojo.codehaus.org/versions-maven-plugin/lock-snapshots-mojo.html), there might be equivalent plugins for Gradle (maybe [`nebula.dependency-lock`](https://github.com/nebula-plugins/gradle-dependency-lock-plugin) would do it)

**Comment by cgruber** [comment]
We will be releasing a stable 2.0 shortly.

**Comment by JohannHei** [comment]
Hi, when you will release a new version with working injection?
