### ISSUE TITLE
Note: Prefer to run the dagger processor over that class instead. ?

### ISSUE THREAD

**Issue by damianpetla** [google/dagger#111]
When I build my project I see a note:
> Generating a MembersInjector or Factory for com.demo.MainActivity. Prefer to run the dagger processor over that class instead.

What can I do to make Dagger "happy" and get rid of that note or should I ignore it?

My code is very simple. I skipped some irrelevant parts.

**Application**
```java
public class BaseApplication extends Application {
    @Singleton
    @Component(modules = {AndroidModule.class, FontModule.class}) public interface ApplicationComponent {
        void inject(MainActivity mainActivity);
    }

    private static ApplicationComponent graph;

    @Override public void onCreate() {
        super.onCreate();
        graph = Dagger_BaseApplication_ApplicationComponent.builder()
                .androidModule(new AndroidModule(this)).fontModule(new FontModule())
                .build();
    }

    public static ApplicationComponent getGraph() {
        return graph;
    }
}
```

**MainActiivty**
```java
override fun onCreate(savedInstanceState: Bundle?) {
        super<BaseActivity>.onCreate(savedInstanceState)
        ....
        BaseApplication.getGraph().inject(this)
    }
```

**Comment by JakeWharton** [comment]
More issue info: `MainActivity` is in Kotlin, `BaseActivity` is in Java. Kotlin classes are not visible to the annotation processor.

**Comment by Ph1b** [comment]
How was this resolved?

I face the same problem and use kapt for the dagger processor. Shouldn't that solve the issue?

**Comment by netdpb** [comment]
That note is there because if you provide or inject a class that has an `@Inject` annotation but you didn't run Dagger over that class, Dagger generates the required code for that class lazily but reminds you that you should explicitly run the processor yourself.

We had a bug where Dagger emitted that note even for classes that don't have an `@Inject` annotation at all, even if you do run the Dagger processor over that class. I guess your MainActivity counts.

The bug is now fixed at head, and will be pushed in the next snapshot.

**Comment by Ph1b** [comment]
I do have that issue since I switched to kotlin. 

    kapt "com.google.dagger:dagger-compiler:$daggerVersion"

Shouldn't that make dagger generate the code?

**Comment by netdpb** [comment]
I don't know Kotlin or kapt. And you haven't included your MainActivity source code, so I'm guessing here.

But if MainActivity does not have any `@Inject` annotations itself, maybe instead relying on some in its superclasses, then even if you successfully run Dagger over that class it doesn't see any reason to generate a `MainActivity_MembersInjector` class in advance. Then when it processes your `@Component`, it realizes you need a `MembersInjector<MainActivity>`, so it generates one just-in-time and emits that note.

The bug (now fixed at head) is that it emits the note telling you to run Dagger over the `MainActivity` class _even if you did run Dagger over the `MainActivity` class_ because it can't tell the difference between didn't-run and ran-but-didn't-generate-code.
