### ISSUE TITLE
Why can't scoped Components share modules?

### ISSUE THREAD

**Issue by bnvinay92** [google/dagger#1126]
My understanding is that modules contain methods that know the "how" of creating dependencies. Why can't I reuse these methods across different scopes?

**Comment by huntj88** [comment]
can you give an example of when you would need to do that?

**Comment by ronshapiro** [comment]
Components can share these across `Component <---> Subcomponent` boundaries since these share implementations. `@Component.dependencies` are true API boundaries, so Dagger can't reach into those internals to access the modules. In fact, `@Component.dependencies` don't need to be related to dagger at all, they can be regular POJOs.
