### ISSUE TITLE
ContributesAndroidInjector support for androidx.lifecycle.ViewModel

### ISSUE THREAD

**Issue by sh4wn** [google/dagger#1271]
is there any plan for support androidx.lifecycle.ViewModel with @ContributesAndroidInjector?

**Comment by Vichy97** [comment]
Also wondering this same thing

**Comment by wlodzix** [comment]
+1

**Comment by ronshapiro** [comment]
We need to think through a few things, but the short answer is yes.

**Comment by Vichy97** [comment]
Is there a timeline on that?

**Comment by igokoro** [comment]
Would be really useful. Already got burned by this when implemented such injection myself. It turns out, depending on how/when you inject Fragment (in my case), dagger may "help" retain a "cleared" `ViewModel` instance. A quick fix in my case was to use `Provider<>` to get a just-in-time "alive" instance of my ViewModel.

It would also be extremely convenient if dagger could generate ViewModel Factories. From what I understand, the thing is a necessary (evil) piece of boilerplate code required by the framework. It has no other development value. Dagger could derive Factory implementation from injectable `ViewModel` constructor.

**Comment by matejdro** [comment]
> Dagger could derive Factory implementation from injectable ViewModel constructor.

See my comment [here](https://github.com/google/dagger/issues/1273#issuecomment-447997439), you can create that factory easily yourself.

**Comment by Chang-Eric** [comment]
I'm closing this since with the release of Hilt and the Jetpack extension for ViewModels using Hilt, I think this feature request for dagger.android is unlikely to be done.

**Comment by tir38** [comment]
This is what @Chang-Eric is referring to: https://developer.android.com/training/dependency-injection/hilt-jetpack#viewmodels

Sadly I wish there was a "vanilla" Dagger (aka w/out dagger-android or Hilt) way of doing this.

**Comment by tasomaniac** [comment]
Vanilla Dagger is platform agnostic. That's why it is vanilla 😉

**Comment by tir38** [comment]
oh yeah. I was complaining about ViewModel workings, not Dagger =)
