### ISSUE TITLE
In fastInit mode, Lazy is "heavier" than Provider for scoped classes.

### ISSUE THREAD

**Issue by pshmakov** [google/dagger#1278]
Lazy<Foo> and Provider<Foo> behave identically if Foo is scoped (get() always yields the single instance).

With fastInit disabled they are both instances of DoubleCheck.

With fastInit enabled, however, a Provider is a SwitchingProvider, but Lazy is a DoubleCheck wrapping a SwitchingProvider. So Lazy incurs some unnecessary overhead, compared to Provider.

This might become an incentive to always prefer Provider for scoped instances, even when Lazy is semantically more appropriate, and cause some confusion in the community.

**Comment by ronshapiro** [comment]
> This might become an incentive to always prefer Provider for scoped instances, even though Lazy is semantically more appropriate, and cause some confusion in the community.

We've maintained that you should always use the "correct" kind (Provider vs. Lazy) at the request site, regardless of scoping (since that's an implementation detail even from your own code's perspective).

It's also a bad idea to rely on micro-optimizations within Dagger, as these can always change. I'm also skeptical that this itself is any noticeable performance hit.

But we could consider something for `DoubleCheck` to detect scoped SwitchingProviders. That's probably not hard and definitely doable.
