### ISSUE TITLE
Using Dagger Android with component dependencies 

### ISSUE THREAD

**Issue by quiro91** [google/dagger#1298]
In a multimodule project, I have a `BaseComponent` in a base module, and then in each feature module there is a FeatureComponent with a module containing the `@ContributesAndroidInjector` bindings for the desired classes. I've tried to expose both the `DispatchingAndroidInjector` for activities in my `BaseComponent` and the multibinds map, but unfortunately it's not working, as the map is empty and immutable and so it can't be shared between modules, causing the following crash: 
`IllegalArgumentException: No injector factory bound for Class<com.quiro.feature.FeatureActivity>`

Is it possible to use dagger-Android with component dependencies? From my understanding dagger-android generates subcomponents which end up being part of their parent component. In order to avoid recompiling all the generated code, I thought that having this setup was the best option. Is there anything I'm missing?

I've taken the time to build a sample to reproduce the issue:
https://drive.google.com/open?id=1oZRS6Klqh4BrXFyFcQJc62rX6VWStll8

**Comment by ronshapiro** [comment]
There's no way to do this I believe. Multbindings aren't exposed through component dependencies, they look like any other `@Provides` method for the entire map. Because there's no `@EntriesIntoSet` there's no way to add them all in

Unless you wanted to have a finite number of `@IntoMap` methods that each accessed the `i`th element in the map, and some bogus value for extras, but that sounds gross.
