### ISSUE TITLE
Cannot inject members into types with unbounded type arguments

### ISSUE THREAD

**Issue by liulinjie1990823** [google/dagger#1327]
Cannot inject members into types with unbounded type arguments: com.llj.lib.base.MvpBaseActivity<?>
```
interface IBasePresenter : DefaultLifecycleObserver {
    fun destroy()
}
```
```
abstract class MvpBaseActivity<P : IBasePresenter> : AppCompatActivity(),
        IBaseActivity, ICommon, IUiHandler, IEvent, ILoadingDialogHandler, ITask {
    val mTagLog: String = this.javaClass.simpleName
    lateinit var mContext: Context

    @Inject lateinit var mPresenter: P
    private lateinit var mUnBinder: Unbinder
    private var mRequestDialog: ITag? = null

    private val mCancelableTask: ArrayMap<Any, Disposable> = ArrayMap()
```
```
@Route(path = CRouter.APP_MAIN_ACTIVITY)
class MainActivity : BaseTabActivity<MainPresenter>(), MainContractView {
```
2.17 is ok,but 2.19 failed

my MvpBaseActivity has a unbounded type(P : IBasePresenter),but is says unbounded,why

**Comment by ronshapiro** [comment]
This is working as intended. I believe this is a problem with Kotlin's declaration site variance that it seems to be a bounded wildcard but it's really unbounded.

Dagger can't members inject types with unbounded wildcards because it may lead to having to inject a member who's sole type is `?` (or `*` in Kotlin), which is not a type that can be bound.
