### ISSUE TITLE
Deprecate DaggerFragment over FragmentFactory

### ISSUE THREAD

**Issue by Ethan1983** [google/dagger#1372]
Hello,
    Is there any plan to deprecate DaggerFragment now that FragmentFactory is available to use constructor injection?

**Comment by JakeWharton** [comment]
FragmentFactory isn't stable yet, but once it is the members injection /
service locator should be deprecated as you say.

**Comment by Ethan1983** [comment]
Gotcha, would also need Navigation jetpack to start using it as well.

**Comment by Chang-Eric** [comment]
I'm going to close this because dagger-android isn't really being developed right now and because I suspect constructor injection in dagger-android may have similar concerns like those in Hilt (https://github.com/google/dagger/issues/1893), though probably to a lesser degree since dagger-android doesn't make as many guarantees.
