### ISSUE TITLE
Gradle instructions need updating

### ISSUE THREAD

**Issue by shaeberling** [google/dagger#1423]
Following the instructions for using Dagger with gradle does not work (anymore).

With the current gradle (5.2.1) and latest apt plugin version (0.21) the task name should be `annotationProcessor` instead of `apt`.

**Comment by JakeWharton** [comment]
You shouldn't be applying an apt plugin anymore anyway.

**Comment by tbroyer** [comment]
> You shouldn't be applying an apt plugin anymore anyway.

+1

(from the author of that plugin)

`annotationProcessor` exists since Gradle 4.6 (almost a year ago, according to https://gradle.org/releases/), and Gradle 5.2 now sets a default value to compilation tasks' `options.annotationProcessorGeneratedSourcesDir`.

@ronshapiro The README really is outdated and needs some love. As a lurker, I'm tired of all the duplicates of #1130 every now and then, and now the Bazel instructions, and then this. How can we move forward? Do you have all the information needed to unilaterally update the README or would you prefer PRs?

**Comment by shaeberling** [comment]
+1 to updating that README in general. I still have not found a way to make dagger work with bazel (which is why I opened #1422)

Thanks for noting that apt is no longer necessary. I updated this patch to remove the plugin. Verified it still works. Feel free to take it to do a big update on the whole page.
