### ISSUE TITLE
Implement JSR365

### ISSUE THREAD

**Issue by SchulteMarkus** [google/dagger#1424]
**Is** [Dagger is implementing JSR330/javax.inject:1.0](https://google.github.io/dagger/users-guide)
**Feature request** Dagger implements [JSR365/cdi-api:2.0](http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html)

**Motivation**
JSR365 is the successor of JSR330. For time being, Dagger is "only" supporting an outdated standard, which has for good reasons a successor.

**Comment by tbroyer** [comment]
JSR365 *builds upon* JSR330, it does not update or replace it: http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#_relationship_to_dependency_injection_for_java

See also #455 and #652

**Comment by SchulteMarkus** [comment]
Thanks for clarification!

**Comment by ronshapiro** [comment]
I hadn't seen JSR 365, thanks for pointing that out. It does, however, seem to be a very large spec, so it would likely take serious thought about what it would mean for Dagger to start "supporting" it. My guess is that due to the complexity, it's unlikely that we will do so in the near term as there are more pressing concerns for most of our users.

**Comment by cgdecker** [comment]
JSR-330 is a lightweight spec for dependency injection. JSR-365/CDI is a pretty heavyweight spec that is as far as I know aimed primarily at enterprise server applications, which I don't think it makes sense for Dagger to try to implement.
