### ISSUE TITLE
Support MapKey value types besides String and enumerated types

### ISSUE THREAD

**Issue by netdpb** [google/dagger#144]
For MapKey-annotated annotations where unwrapValue is true, the single member must be either a String or an enumerated type value.

Unwrapped MapKeys should allow the single member to have any primitive type, Class, or an annotation as well — basically any type allowed by JLS 9.7 that has value-equality semantics (i.e., excluding arrays).

**Comment by cgruber** [comment]
Yep - that was always the plan, as well as to offer some pre-fab keys, like StringKey, ClassKey, etc.  Enum keys and keys that contain annotations need their own custom key per enum because you can't specify these generically in an annotation spec.

Side note: For the annotation case, someone could just mark THAT annotation as unwrap=false and let that annotation BE the key.

**Comment by gk5885** [comment]
This is fixed and awaiting a sync from @cgruber .

**Comment by netdpb** [comment]
This is fixed in the latest snapshot.
