### ISSUE TITLE
Dagger does not seem to work with the classes generated by Glide

### ISSUE THREAD

**Issue by seyfullahbilgin** [google/dagger#1477]
Can dagger work with classes which are generated by another library/framework?
My goal is to provide GlideRequests class via Dagger (2.22.1) and i tried something like this:

```
@Provides
    fun provideGlideRequests(context: Context): GlideRequests {
        return GlideApp.with(context)
    }
```
Hovewer Dagger is not able to build with GlideRequests class  which is generated by Glide. 

Error:

> NetworkModule_ProvideGlideRequestsFactory.java:7: error: package error does not exist

Generated class by Dagger: (GlideRequests = NonExistentClass )

```
import android.content.Context;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import error.NonExistentClass;
import javax.inject.Provider;

public final class NetworkModule_ProvideGlideRequestsFactory implements Factory<NonExistentClass> {
  private final NetworkModule module;

  private final Provider<Context> contextProvider;

  public NetworkModule_ProvideGlideRequestsFactory(
      NetworkModule module, Provider<Context> contextProvider) {
    this.module = module;
    this.contextProvider = contextProvider;
  }

  @Override
  public NonExistentClass get() {
    return provideGlideRequests(module, contextProvider.get());
  }

  public static NetworkModule_ProvideGlideRequestsFactory create(
      NetworkModule module, Provider<Context> contextProvider) {
    return new NetworkModule_ProvideGlideRequestsFactory(module, contextProvider);
  }

  public static NonExistentClass provideGlideRequests(NetworkModule instance, Context context) {
    return Preconditions.checkNotNull(
        instance.provideGlideRequests(context),
        "Cannot return null from a non-@Nullable @Provides method");
  }
}

```

**Comment by ronshapiro** [comment]
Can you share your set up? Is `error.NonExistentClass` what you are seeing explicitly?

**Comment by ronshapiro** [comment]
It looks like this is a type generated by kapt. My first cursory look makes it seem that the type is not actually an `ErrorType`, which would be problematic: https://github.com/JetBrains/kotlin/search?q=error.NonExistentClass&unscoped_q=error.NonExistentClass

**Comment by seyfullahbilgin** [comment]
finally found the solution after two hours

Just add this to build gradle file to avoid the issues related NonExistentClass

kapt {
 correctErrorTypes true 
} 

https://kotlinlang.org/docs/reference/kapt.html#non-existent-type-correction

**Comment by luis-cortes** [comment]
@ronshapiro @bcorso  I am currently running into a similar issue that really has me baffled. 

@seyfullahbilgin's solution works for me, but only while I don't clean the project.
If I clean the project, the solution stops working and `kaptDebugKotlin` fails with the following error:

```
cannot find symbol
    public final OutboundMessageJsonAdapter providesOutboundMessageJsonAdapter(@org.jetbrains.annotations.NotNull()
```

`OutboundMessageJsonAdapter` is a class that's generated using [Moshi Kotlin Codegen](https://github.com/square/moshi/#codegen)

Steps:
1. Clean project
2. Add `correctErrorTypes = true` to the module in question
3. Sync IDE
4. Build is successful. 
5. Clean the project (not changing the `build.gradle.kts` file!)
6. Build fails

Once the build fails, it will no longer succeed reliably. Disabling/Enabling `correctErrorTypes` by commenting/uncommenting the kapt block and resyncing will, occasionally, produce a successful build. Most of the time it will just keep failing. 

## Two Build Failure Scenarios
### With `correctErrorTypes = true`
The class with the issue is a generated stub based off this module:
```
@Module(includes = [LifecycleObserverModule::class])
object MessagingModule {

  @Provides
  fun providesOutboundMessageJsonAdapter(moshi: Moshi): OutboundMessageJsonAdapter =
    OutboundMessageJsonAdapter(moshi)
}

@Module
abstract class LifecycleObserverModule {
  @Binds
  abstract fun bindsLifecycleObserver(messagingWebSocketClient: MessagingWebSocketClient): LifecycleObserver
}
```
Generated Stub:
```
@dagger.Module(includes = {com.redacted.LifecycleObserverModule.class})
public final class MessagingModule {
    public static final com.redacted.MessagingModule INSTANCE = null;
    
    @org.jetbrains.annotations.NotNull()
    @dagger.Provides()
    public final OutboundMessageJsonAdapter providesOutboundMessageJsonAdapter(@org.jetbrains.annotations.NotNull()
    com.squareup.moshi.Moshi moshi) {
        return null;
    }
    
    private MessagingModule() {
        super();
    }
}
```
### With `kapt` block commented out
I see the same issue as @seyfullahbilgin but with `OutboundMessageJsonAdapter` as the `NonExistentClass`.

## Other Details
 
* `MessagingModule` is installed on a `Subcomponent` in a feature module.
*  `implementation(Deps.Dagger2.dagger2)` and `kapt(Deps.Dagger2.compiler)` are in the `build.gradle.kts` of the module in question
* No other files are changing during this process. The only changes to the build process that ever happen are the comment/uncommenting of the kapt block
* `OutboundMessageJsonAdapter` is definitely being generated, even when builds are failing. 
* Commenting out `kapt.use.worker.api=true` did not help (thought maybe there was some crazy race condition between Moshi and Dagger)

I don't think there's anything unusual about my dagger setup, but even if there was, why is the build seemingly nondeterministic? If this feels like it could be a dagger issue, but you need a sample project to reproduce I can try and whip one up. 

Dagger version: 2.27 (found it on 2.27 but happens on 2.25.4 - 2.28)
Kotlin version: 1.3.72
AGP version: 3.6.3
Android Studio version: 3.6.3
