### ISSUE TITLE
Suspend method with @Provides

### ISSUE THREAD

**Issue by renannprado** [google/dagger#1502]
I'm trying to use Dagger2 with Kotlin and Vertx.
The creation of some dependencies are done asynchronously and vertx provides extension suspend methods for them.
So I'd like to use this from inside of the `@Provides` methods, but it doesn't seem to be possible at the moment.

When I try to add `suspend` to a `@Provides` method, I get the following error:

`error: [Dagger/MissingBinding] io.reactiverse.pgclient.PgConnection cannot be provided without an @Provides-annotated method.`

**Comment by JakeWharton** [comment]
Dagger generates Java and cannot invoke your suspend function.

**Comment by renannprado** [comment]
@JakeWharton @ronshapiro I understand that this this is not possible at the moment. But is this impossible to implement?

**Comment by JakeWharton** [comment]
Practically, yes, without switching to generating Kotlin instead of Java

**Comment by Joao360** [comment]
I know this is an old issue but I'm currently facing it. Are there any alternatives? I haven't found any

**Comment by Chang-Eric** [comment]
You probably need to have a wrapper class that has a suspend method that you can call later. This is similar to how you might want to wrap some code that creates a `ListenableFuture` in a class (like a data fetcher class) instead of binding the `ListeanbleFuture` data fetch directly into Dagger. This would be the general pattern for interacting with async things in Dagger with or without coroutines.

If you're using Dagger Producers which is made to string together async operations, you can probably do something like use [`async`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html) and then [`asListenableFuture`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-guava/kotlinx.coroutines.guava/as-listenable-future.html) in your `@Produces` node to interface with futures. This isn't a recommendation to use Dagger Producers over coroutines. This is just saying how you would interface coroutines with existing Producers code.

**Comment by k4dima** [comment]
kotlinx.coroutines.runBlocking and javax.inject.Provider or dagger.Lazy
