### ISSUE TITLE
Should I use Dagger2 in library project? Will it cause issues for application?

### ISSUE THREAD

**Issue by wellbranding** [google/dagger#1503]
I am currently working on Android library project. Currently we have pure dependency injection(without any Frameworks). However, we expand our library functionality: providing more modules, separating code into new modules, dynamic delivery and etc. This is why our current DI will not suit our needs. We would need to invest tons of resources into that.

I did not used Dagger2 in the beginning, because I thought that library should have few dependencies. I am comfortable with Dagger2, so it won't create any issues. 

However, what I fear is various issues, which my occur while integrating our library. 

I wanted to ask, if it is possible to get Android gradle, or any **other issues**, if application does not use Dagger2 and library does?

Will integration issues occur if both application and library, uses different versions of dagger2?

Will integration issues occur if application uses another **DI framework**, like Coin for instance?

Thanks for answers!

**Comment by ronshapiro** [comment]
In general, there's probably a way to design your library such that it works well with Dagger but is usable by non-dagger users. That's probably the most flexible option.

> I wanted to ask, if it is possible to get Android gradle, or any other issues, if application does not use Dagger2 and library does?

I don't get what you mean by this question.

There can definitely be issues if there are different versions for Dagger. If you can guarantee that they're the same, you should be safe.

I have no idea about Koin, but I imagine there could also be issues with using different versions, though because it's a runtime library perhaps it won't.
