### ISSUE TITLE
Android: Injecting in to activities form subcomponent created in runtime

### ISSUE THREAD

**Issue by wafel82** [google/dagger#1598]
Hi,

I'm trying to handle fairly simple login scenario with dagger-android: 
1. On application startup we do not have user data available.
2. Once application starts, it loads user data (eg. from network or db...)
3. Once user data are loaded, rest of the applications screens are fired up "within"  user context. 

In more details: 
1.  There is `OnboardingActivity` used as entry-point of my application. I'd like to inject in to it from application-scoped component (inject singleton instances)
2. There is a currently logged user fetching logic fired up in the onboarding screen. 
3. Once user-login on onbaoarding screen succeed -> **I'd like to create `UserComponent` with `UserScope` and thus make the user-based data to be injectable in to rest of my application.**
2.  Once user-login on onbaoarding screen succeed -> I'd like to switch to the `UserActivity`. There is no sense to show `UserActivity` without user context (need to present user specific data), so **I'd like to inject in to this activity from  `UserComponent`**

Actually I'm getting following error: 
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.(...).UserActivity}: java.lang.IllegalArgumentException: No injector factory bound for Class<com.(...).UserActivity>
```
And here is my implementation: 

Dagger dependencies: 
```
    implementation "com.google.dagger:dagger-android:2.24"
    implementation "com.google.dagger:dagger-android-support:2.24"
    kapt "com.google.dagger:dagger-android-processor:2.24"
    kapt "com.google.dagger:dagger-compiler:2.24"
```

Applicaton class: 
```kotlin
class FancyApplication : DaggerApplication() {
    override fun applicationInjector(): AndroidInjector<out DaggerApplication> {
        return DaggerFancyAppComponent
            .factory()
            .create(
                ... <- modules providing singletons go here
            )
    }
}
```
Singleton component: 
```kotlin
@Singleton
@Component(
    modules = [
        AndroidSupportInjectionModule::class,
        RootActivitiesModule::class,
        .... <-  other modules providing singletons go here
    ]
)
interface FancyAppComponent: AndroidInjector<FancyApplication> {
    @Component.Factory
    interface Factory {
        fun create(
             ... <- modules providing singletons go here
        ): FancyAppComponent
    }

    fun loggedUserFactory(): UserSubcomponent.Factory
}
```
RootActivitiesModule class: 
```kotlin
@Module
abstract class RootActivitiesModule {

    @ContributesAndroidInjector
    abstract fun contributeOnboardingActivity(): OnboardingActivity
}
```

UserSubcomponent class: 
```kotlin
@UserScope
@Subcomponent(modules = [
    UserActivitiesModule::class, 
    ... <- other user-scoped modules goes here
    ]
)
interface UserSubcomponent : AndroidInjector<FancyApplication> {

    @Subcomponent.Factory
    interface Factory {
        fun create(
            ... <- user-scoped modules goes here
        ): LoggedUserSubcomponent
    }
}
```
UserActivitiesModule class: 
```kotlin
@Module
abstract class UserActivitiesModule {

    @ContributesAndroidInjector
    abstract fun contributeUserActivity(): UserActivity
}
```

Result is that `OnboardingActivity` is successfully created (all needed stuff is successfully injected in to it), However app crashes on missing `UserActivity` injector.

I need to know what is the idiomatic way to somehow instantiate the `UserSubcomponent` once user date gets obtained so that all injectors defined in `UserSubcomponent`'s modules become available for the dagger.

Really appreciate any suggestions

**Comment by Chang-Eric** [comment]
So the issue with the crash is that in dagger.android, your Activity goes to the Application and asks it for an injector. If you use the standard base classes, this assumes your @ContributesAndroidInjector module is installed in the component that injects your Application. In your case, this isn't the case because it is installed in the UserSubcomponent, hence the failure.

@ContributesAndroidInjector to code generates an activity subcomponent for you and then an injector that is multibound into a map that is then looked up by the application. You would want to probably opt to not use @ContributesAndroidInjector and instead manually create your subcomponent (since it isn't going to be a direct child of the ApplicationComponent) and also your own injector since that injector has to know to not just directly create the activity subcomponent, but to first get the user subcomponent and then create the activity component.

An alternative approach if you know that every activity/Android component is going to be a subcomponent of the UserSubcomponent is to not use DaggerApplication directly and make the AndroidInjector returned by the HasAndroidInjector interface that your application would then implement come from the UserSubcomponent. I would probably recommend this one less though as it kind of locks you in to everything being a child of the UserSubcomponent.

**Comment by ahetawal-p** [comment]
Hi @wafel82 were you able to find any workarounds for this. The only solution seems to be to get rid of dagger-android and just use plain dagger to build and manage subcomponents. ?
