### ISSUE TITLE
Multiple unrelated components in the same class

### ISSUE THREAD

**Issue by faridz** [google/dagger#1629]
`class Multiple {
    @Inject
    protected A a;  // singleton provided by component A

    @Inject
    protected B b;  // singleton provided by component B

    public A {
        ComponentA.get().inject(this);
        ComponentB.get().inject(this);
    }
}`

ComponentA and ComponentB are independent of each other and have separate graphs.
For example, ComponentA is a library component used in multiple modules, whereas ComponentB is specific to one particular module. ComponetA lives in shared module and have no access to classes of componentB.

**Comment by Chang-Eric** [comment]
This is something we are not able to support since Dagger doesn't know which bindings you intend to provide from which component. Among other things, this would hamper our ability to give you useful missing binding errors since we wouldn't know if a binding was missing or was meant to be provided via some other component later on.
