### ISSUE TITLE
no suitable method found for inject(androidx.fragment)

### ISSUE THREAD

**Issue by Faiizii** [google/dagger#1652]
I am trying to inject my androidx.fragment using dagger docx like

`
@Override
    public void onAttach(@NonNull Context context) {
        AndroidInjection.inject(this); 
        super.onAttach(context);
       // AndroidSupportInjection.inject(this); // this works perfect
    }
`
**its says me no suitable method for injecting androidx fragment.**
I added my fragment in di fragment module and I am using `@ContributesAndroidInjector` with abstract module to generate its sub-component and factory. (stated in docs protip). yes I inject my activity.
when I refer to the inject method it looks like only simple android.fragment can be injected using `AndroidInjection.inject(this)`

**Comment by danysantiago** [comment]
To inject `androidx.fragment` use `AndroidSupportInjection` instead of `AndroidInjection`, the latter is meant for the framework classes. `AndroidSupportInjection` is for the support library, however since you seem to be using the AndroidX migrated version of the support lib then make sure you also have [enabled the Jetifier](https://developer.android.com/jetpack/androidx#using_androidx_libraries_in_your_project).

**Comment by trevjonez** [comment]
even the jetifier doesn't work well with later versions of androidx.activity and androidx.fragment. My recommendation is to reimplement your own version of DaggerActivity and DaggerFragment so that you can get proper visibility to new apis like `getOnBackPressedDispatcher` in fragments that subclass DaggerFragment.

additionally because jetifier makes dagger android support depend on older versions of androidx.fragment when you include newer versions of fragment-test on your androidTest configurations you will end up failing to build due to version constraint violations (this is a feature not a bug, the issue is that dagger needs to migrate)

all of which could probably be resolved if we could get the androidx migration done regardless of what you consider the future of `dagger-android` to be following all the noise from the android dev summit.

related issue https://github.com/google/dagger/issues/1619
