### ISSUE TITLE
Order of elements in generated code

### ISSUE THREAD

**Issue by nbali** [google/dagger#1733]
Due to various reasons unrelevant to the issue, we can't just generate the necessary code on-the-fly, but we actually commit it into our repository. Unfortunately the order of fields, assignments, etc in generated code isn't always the same showing up as changes in git. Functionality-wise it is identical, just few things are reordered.

I know this isn't the recommended usage, and yet I'm still curious is there any way to influence this order? (I failed to find it, but who knows.)

Even if there isn't, is there any reason against having consistent ordering added to code generation?

Dagger version: 2.25.2

**Comment by nbali** [comment]
@fpeter8 fyi

**Comment by BaloghTamas** [comment]
In theory, Dagger should generate the same code for every build if the sources are identical, however, in practice there are some factors that may affect generated code, which I believe are beyond Dagger's influence. 

Generated code is created by an annotation processor, that is included in the compilation chain, along with possibly other annotation processors. According to [Lombok devs](https://stackoverflow.com/a/29235021/1966483) the order of annotation processors is random, as annotation processors are [loaded in separate classloaders](http://openjdk.java.net/groups/compiler/doc/compilation-overview/index.html), that uses `hashCode()` which is [based on a memory address](http://net-informations.com/java/cjava/hash.htm). So if you are using other annotation processors, the order of processing could affect the generated code. With properly built annotation processors, this should not affect the behavior, only the layout of the code as you mentioned.

Also, the order of classes, fields, methods, etc.., given by the compiler for the annotation processor is up to the compiler implementation. I would expect that this is deterministic, however, there are [strange cases as well](https://github.com/google/auto/blob/6dde49040ffbd2ce644f280a70180948666046f8/value/src/main/java/com/google/auto/value/processor/EclipseHack.java#L52), so that could also be an issue, that is beyond Dagger's influence.

There could be further things as well that could affect this, that I couldn't think of right now, so I would suggest to not commit generated code into Git. Also as I mentioned I don't think this issue could and should be addressed by Dagger itself.

**Comment by nbali** [comment]
I'm familiar with the annotation processor ordering issue - we also encountered that, but that has a workaround if the project structure allows it -, but this has nothing to do with that. The affected code I'm talking about uses only Dagger, and no other APT is modifying it.

I'm not that familiar with Dagger's implementation itself, and I haven't played around with it to be sure, but I still think I found places, where using a simple sort before working through a few elements would make this deterministic. I guess this isn't all of them.

For example:
https://github.com/google/dagger/blob/b14f93303fb3eaeb269c7d3b92e9f47cce15cae3/java/dagger/internal/codegen/validation/InjectBindingRegistryImpl.java#L91-L104
This iterates over a simple `Deque` in other order of addition basically. I'm only *guessing*, but I *guess* this influences the order here. So it might well be a `TreeSet` with a proper deterministic comparator.

![image](https://user-images.githubusercontent.com/581927/73769636-4dcc3700-477b-11ea-9b94-b5f678d7210f.png)
![image](https://user-images.githubusercontent.com/581927/73769665-59b7f900-477b-11ea-9c5c-5221c79a6c1f.png)

**Comment by Chang-Eric** [comment]
To clarify, are you saying that Dagger generates slightly different code if built twice with the exact same sources or that the generated code changes slightly when there are changes that you believe should not affect the generated code?

In either case, I think it will depend on where the source of the randomness is coming from. If the source is somehow in Dagger itself, that is something I'd be willing to fix, but I don't want to add sorts over places where there is randomness coming in (e.g. if say the given order of methods in a module class were random). I think adding those sorts would negatively impact build times (which are already an issue) and be overall fragile in a way that we'd be likely to break the guarantee again.

**Comment by nbali** [comment]
"Dagger generates slightly different code if built twice with the exact same sources"

We use Eclipse, IntelliJ and Maven from CLI for the same codebase, and there is no version of code that stays the same with all 3 after a full build.

**Comment by ronshapiro** [comment]
Eclipse and javac have different orders for lists of elements that they
return, which wreaks havoc.

Can you run a build as part of your pre-commit and always use the same
compiler there?

**Comment by nbali** [comment]
1. A pre-commit hook is already too late, because when you compose a commit, you would like to see the actual changes and pick from them. Now it's hidden among dozens/hundreds of generated classes.
2. IMO our project is way too big for a full build prior to every commit.
3. Executing `git checkout ./\*/generated-sources/\*.java` does the trick pretty well if there is no change in the Dagger-related classes. It's just a PITA.

**Comment by Chang-Eric** [comment]
I'm sorry but I don't think maintaining a specific order for the generated code is something we are willing to commit to. It is likely going to be be something that constantly backslides (and the fixes would be low priority for us causing frustration for you) and also it would increase annotation processing time for other users so it probably wouldn't be a good experience on either side.

I'm going to close this issue, but feel free to continue the conversation if there is something I've missed, thanks.

**Comment by nbali** [comment]
We are still suffering from this issue. It's even worse as it's another bigger project, and the maven and eclipse differences are even bigger. It affects even the parameter ordering of methods that causes the build to have compilation errors if not every Dagger generated file has been created by the same compiler. Can't it be implemented with a flag? I suspect I already spent significantly more time with working around this then it would have taken me to do some PRs here.

**Comment by Chang-Eric** [comment]
I really think this is not really possible and would add a huge burden to maintaining Dagger. We'd really have to run a sort every time we read an attribute from anything, like getting methods, interfaces, parameters, etc. Also, a significant portion of our code now goes through XProcessing and helper functions in there, which means there might be things out of our control as well. A flag doesn't help because it isn't just one place in the code, it'd be nearly everywhere. The situation is unfortunate, but I don't think we can make/maintain this guarantee for your use case.

**Comment by nbali** [comment]
Well, I managed to make it work - at least seemingly -, but it definitely has got some strange behaviour. The original generated code was really chaotic regarding the differences between the two versions. So first I made the binding/providing method names consistent across the whole codebase. That definitely reduced the amount of changes between the versions. I have no idea why, it shouldn't have, but it did. These smaller amount of changes helped me realize that the generated fields are grouped based on the files it will be injected into (so with a superclass hierarchy the various "levels" were next to each other in the factory), but inside that "group" one version containted them in alphabetical, and the other containted them in the same order they were found in the code. By ensuring that all the injected fields are in alphabetical order the differences were further reduced. It's still there, but at least the parameter order is the same, so it seemingly always compiles.

IMO there would be no need to always sort it like you assume. I mean guaranteeing that the code is identical (my original use-case) can be indeed more complicated, but having consistent parameter order (fresh use-case) shouldn't be that hard, and that is what is actually breaking the compilation. (Compile with maven, open IDE, modify file, it updates some geneated files, but not all -> parameter order conflict)

**Comment by Chang-Eric** [comment]
> These smaller amount of changes helped me realize that the generated fields are grouped based on the files it will be injected into (so with a superclass hierarchy the various "levels" were next to each other in the factory), but inside that "group" one version containted them in alphabetical, and the other containted them in the same order they were found in the code.

Glad you got it to work out, but honestly, I feel like this is a bug as in my opinion compilers should always give the elements to us in declaration order. We ran into an issue recently where a header compiler was doing an optimization and sorting methods because it is ABI compatible and would reduce cache misses. This started causing actual compilation issues though. This is because for code generators sometimes declaration order is the only way to standardize on a certain order. For example, I'm not sure if you're familiar with [AutoValue](https://github.com/google/auto/blob/main/value/userguide/index.md), but the order of the user defined properties is also the order used for the generated constructor which is part of the API. If the compiler sorts those methods for code generators, then you'll get compile errors, and the only way to fix that would be to change the AutoValue API to say the order of the constructor params is the sorted order of the methods, which would be a bad API.

I guess this is all to say that, for some things declaration order is the right API to use rather than sorted, so I kind of lean towards the side that compilers should be giving us elements in declaration order (or expose a method for us to get that order), rather than us sorting it to deal with the compiler sometimes sorting it (and thereby sometimes influencing API because of that).

**Comment by nbali** [comment]
"compilers should always give the elements to us in declaration order"

We can also wait for miracles :)

Anyway I think AutoValue - or Lombok - is a different use-case. Having the original order is indeed the way to go *there*, because you can see and use that signature.

Meanwhile here the generated code - this issue was all about all - is "internal code". The order doesn't matter as long as it works. I mean it's kinda obvious given that totally different generated versions were all perfectly fine with the actual code of the project, and it only caused clashes/differences with itself.

Anyway if I get fed up again, and do the changes myself controlled by a flag similar to `-Adagger.formatGeneratedSource=enabled` without affecting the performance if it's disabled, will it be accepted?
