### ISSUE TITLE
Android Junit build would not generate Dagger class.

### ISSUE THREAD

**Issue by soapsign** [google/dagger#175]
Using the experimental android studio Junit Test framework,
Even adding the following lines in the build file, the Dagger classes are not generated.
`testCompile 'com.google.dagger:dagger-compiler:2.0'`
`androidTestCompile 'com.google.dagger:dagger-compiler:2.0'`
`androidTestApt 'com.google.dagger:dagger-compiler:2.0'`
But running the Android instrumental test, it work fines.
So how to make Junit build generate the classes?

**Comment by tomrozb** [comment]
This issue is related to apt and gradle plugin. It will be address in gradle plugin v1.3.x

You can find more here: https://bitbucket.org/hvisser/android-apt/issue/22/dagger-robolectric-gradle-apt-source-not

I've tested this and you should use `testCompile 'com.google.dagger:dagger-compiler:2.0'`
All the necessary classes are generated but are not visible in Android Studio. Even though the code compiles and tests work as intended.

**Comment by gk5885** [comment]
Unless I hear otherwise, we'll assume that @tomrozb is correct and that this is a gradle issue.
