### ISSUE TITLE
[ClassCanBeStatic] warning flagged by error prone on generated code

### ISSUE THREAD

**Issue by davido** [google/dagger#1855]
Building Dagger with Bazel, with updated EP version to 2.3.5-SNAPSHOT, is complaining:

```
[...]
bazel-out/k8-fastbuild/bin/javatests/dagger/functional/producers/_javac/producers-functional-tests_lib/libproducers-functional-tests_lib_sourcegenfiles/dagger/functional/producers/subcomponent/DaggerModuleSubcomponentsInterop_ProductionParent.java:63: error: [ClassCanBeStatic] Inner class is non-static but does not reference enclosing class
  private final class ProvisionChildImpl implements ModuleSubcomponentsInterop.ProvisionChild {
                ^
    (see https://errorprone.info/bugpattern/ClassCanBeStatic)
  Did you mean 'private static final class ProvisionChildImpl implements ModuleSubcomponentsInterop.ProvisionChild {'?
```

The generated class is [here](http://paste.openstack.org/show/793843/).

**Comment by Chang-Eric** [comment]
Sorry this has been a while, but I think that this might be hard to fix since I think whether that class can be static or not depends on what that component uses. It is probably technically possible for us to keep track of this while writing the component, but it probably isn't worth the extra complexity, especially since this is just a warning.
