### ISSUE TITLE
Check for compilation errors or a circular dependency with generated code

### ISSUE THREAD

**Issue by wishy-viewlift** [google/dagger#1892]
I have an existing Java Android application and I am porting it to Kotlin
While with Java there is no error with injection but when I try to inject the same object in Kotlin fragment or activity 

I get the error 

`ComponentProcessor was unable to process this class because not all of its dependencies could be resolved.`

More information is on stackoverflow 

[https://stackoverflow.com/questions/62297735/kotlin-dagger-componentprocessor-was-unable-to-process-this-interface-android](Dagger kotlin conversion)

Where should I check in the generated code for errors?

**Comment by bcorso** [comment]
This error is from [BasicAnnotationProcessor](https://github.com/google/auto/blob/master/common/src/main/java/com/google/auto/common/BasicAnnotationProcessor.java#L175), and it usually happens when [superficial validation](https://cs.corp.google.com/piper///depot/google3/third_party/java_src/auto/common/src/main/java/com/google/auto/common/BasicAnnotationProcessor.java?type=cs&sq=package:piper+file://depot/google3+-file:google3/experimental&rcl=315681552&g=0&l=73) fails.

Since this happens when when you switch from Java to Kotlin it may be an issue with [Kotlin non-existent type correction](https://kotlinlang.org/docs/reference/kapt.html#non-existent-type-correction). Can you try adding this to your `build.gradle` file:

```
kapt {
    correctErrorTypes = true
}
```

**Comment by wishy-viewlift** [comment]
Tried doesn't seem to work, giving same error

**Comment by bcorso** [comment]
Hmm, not sure without more information. If you have a minimal working example I can take a closer look.

**Comment by NaturallyAsh** [comment]
I can attest that this has been happening to me as well and I too have a Kotlin/Java blended app. I would create a Kotlin class and get that dependency error, then redo it in Java and it'll work fine. It's a struggle because I am trying to learn Kotlin but I can't because of the error.
