### ISSUE TITLE
Fragment viewmodel being scoped with ActivityRetained.

### ISSUE THREAD

**Issue by Bberx** [google/dagger#1939]
Why is fragment viewmodel being scoped with activity retained even its lifecycle is dependent on the fragment not on its parent activity?  Hence I cannot constructor inject the fragments viewmodel with dependencies that is fragment scoped.

**Comment by Chang-Eric** [comment]
Injecting things from the fragment component may leak Fragment instances across configuration changes.

There is unfortunately no FragmentRetainedComponent to use (See https://dagger.dev/hilt/components for the full hierarchy) because there are technical complications with Dagger. Basically, Dagger only supports a single parent for a subcomponent and because FragmentRetainedComponent would have to be a sibling of the ActivityComponent, this would cause two parents for FragmentComponent. It creates a diamond which isn't supported in Dagger.

**Comment by Bberx** [comment]
> Injecting things from the fragment component may leak Fragment instances across configuration changes.
> 
> There is unfortunately no FragmentRetainedComponent to use (See https://dagger.dev/hilt/components for the full hierarchy) because there are technical complications with Dagger. Basically, Dagger only supports a single parent for a subcomponent and because FragmentRetainedComponent would have to be a sibling of the ActivityComponent, this would cause two parents for FragmentComponent. It creates a diamond which isn't supported in Dagger.

Can you suggest some workarounds?

**Comment by Chang-Eric** [comment]
I think it really depends on the pattern. FWIW, if you had `ActivityComponent` bindings, you wouldn't be able to inject those into your activity ViewModel classes either. `@ViewModelInject` doesn't change the ViewModelOwner being used as well, so you should be able to access fragment arguments through that as well.
