### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by martipello** [google/dagger#1942]
can we get an example of how to use hilt with AndroidViewModel

**Comment by martipello** [comment]
can we get an example of how to use hilt with AndroidViewModel

**Comment by danysantiago** [comment]
To use `AndroidViewModel` simply add the `Application` as a dependency request in your constructor.

```kotlin
class MyAndroidViewModel @ViewModelInject constructor(
    app: Application,
    database: MyDatabase
) : AndroidViewModel(app) {
  
}
```
be sure to follow the instruction on how to enable `@ViewModelInject` found [here](https://developer.android.com/training/dependency-injection/hilt-jetpack#viewmodels).

otherwise if you want a more vanilla `AndroidViewModel` then there is nothing different you need to do:

```kotlin
class MyAndroidViewModel(app: Application) : AndroidViewModel(app) {
  
}
```
