### ISSUE TITLE
Feature request: Add isInitialized on Lazy

### ISSUE THREAD

**Issue by mchiu-snap** [google/dagger#1949]
It seems there's no way to check if a dagger.Lazy is initialized (akin to Kotlin's Lazy.isInitialized). Can we add one?

The specific scenario I have is that a Lazy dependency is injected so we can call its clean up methods. However if the object isn't initialized, the Lazy.get will initialize it even though there's no need. Perhaps there's a workaround?

**Comment by Chang-Eric** [comment]
Hm, I'm not sure how I feel about this. Lazy is already just a convenience over using a Provider and a field (which would be the workaround for your issue).

I'm hesitant about adding more functionality to Lazy because I've already seen confusion about whether to use Lazy or Provider and how these are different. I sort of see Lazy as a mistake in that regard.

Another thought too is that Dagger doesn't let you introspect to see if a scoped binding has been initialized and so you get into some slightly weird edge cases since our DoubleCheck (used for scoped bindings in general) implements Lazy. We do this in order to avoid allocating another Lazy object when a scoped binding is requested as a Lazy.

**Comment by JakeWharton** [comment]
I would implement this yourself. I've done this in the past for similar concerns since their usually isolated.

Something like `CloseableLazy<T> : Lazy<T>, Closeable` which injects a `Provider<T>` and does the double-checked locking and conditional cleanup. The only downside is you have to provide that in the graph explicitly yourself, but the unusual semantics of the object usually mean they're few which isn't too bad.

**Comment by mchiu-snap** [comment]
Thanks Eric and Jake for the quick response! Appreciate the insight into the inner workings and for the custom example. I'll try the CloseableLazy. Sounds like this can be closed out then. :)
