### ISSUE TITLE
Subcomponents and multiple dependencies

### ISSUE THREAD

**Issue by stefanrusek** [google/dagger#195]
Consider the following:

    @Component(modules={M1.class
    public interface C {
        T t();
        S plus(M2 m2);
    }

    @Module
    public class M1{
        @Provides Context providesContext() { return application; }
    }

    @Subcomponent(modules = {M2.class})
    public interface S {
        T t();
    }

    @Module
    public class M2 {
        @Provides Context providesContext() { return activity; }
    }

    public class T {
        @Inject public T(Context c) {}
    }

Calling t() on both C and S passes the application context to T, but the intent is pretty clear that C would pass the application and S would pass the activity.

**Comment by vaughandroid** [comment]
Yuck! This is what `@Named` is for.
Unless there's a genuine use case - and I can't think of one - this ought to fail at compile time.

**Comment by Zhuinden** [comment]
Use component dependencies between C and S, and don't inherit `T t()` to `S` from `C`.

**Comment by stefanrusek** [comment]
@Zhuinden @vaughandroid Here is a simplified example with a little more explanation.

    @Component(modules={M1.class
    public interface C {
        Context context();
        S plus(M2 m2);
    }
    
    @Module
    public class M1{
        @Provides Context providesContext() { return application; }
    }
    
    @Subcomponent(modules = {M2.class})
    public interface S {
        Context context();
    }
    
    @Module
    public class M2 {
        @Provides Context providesContext() { return activity; }
        @Provides Activity providesActivity() { return activity; }
    }

Requesting a Context from either S or C will always retrieve the application Context object.

On Android, system level IoC is achieved by using the Context object as a service locator. Context is an interface and sub-scoping is achieved via inheriting from ContextWrapper. The two most common implementations of ContextWrapper are the application object and the activities. Because activities add additional services, but these services are accessed via the Context interface, this can make using dagger painful at times. The most common workaround for us has been to change the type of the dependency to Activity and remove providesContext() from the subcomponent.

However that is a rather brittle solution, because there are times when you want to introduce another ContextWrapper into the chain. For example, we have views that are created by dagger and they are passed a Context. This context can be used to get a Theme object, which the Android view system uses to set fonts, text sizes, heights, widths, etc. The application has a theme object, the activity has a theme object, and it is sometimes desireable to provide a new theme object, such as in the case of a Dialog. In those three cases, you have a view that you might want to resize or recolor based on the context.

Because dagger does not provide a way for submodules to override a dependency from the outer scope/component, we are not able to fully utilize dagger.

**Comment by netdpb** [comment]
It would be nice to have a standard way for subcomponent hierarchies to model this kind of binding stack. I can think of a few solutions:

* Allow subcomponents to override any parent binding. We probably won't support this, mainly because in most cases, conflicting bindings are actually an error, and supporting overriding bindings will make it hard to distinguish between intentional and unintentional rebinding.

* We could address this by letting people explicitly distinguish overriding bindings, either by annotating overridable or overriding bindings.

* Or we could add explicit support for this kind of decorating stack somehow.

This needs further research on our part.

-----

In the meantime, perhaps you could use map bindings to have the effect you're looking for:

```java
@Module class ApplicationModule {
  @Provides(type=MAP) @ContextLevelKey(APPLICATION)
  Context applicationContext(MyApp app) { return app; }
}

@Module class ActivityModule {
  @Provides(type=MAP) @ContextLevelKey(ACTIVITY)
  Context activityContext(MyActivity activity) { return activity; }
}

@Module class ContextModule {
  @Provides Context context(Map<ContextLevel, Provider<Context>> contexts) {
    for (ContextLevel level : ContextLevel.smallToLarge()) {
      if (contexts.contains(level)) return contexts.get(level).get();
    }
  }
}
```

**Comment by netdpb** [comment]
Closing for now since there's a workaround. We will continue to think about the best ways for Dagger to support Android.

**Comment by davidliu** [comment]
@netdpb Has any new consideration been made towards explicit overriding bindings/decorating stack since the closing of this issue?

The dependencies solution mentioned by @Zhuinden works very similar to overriding bindings, just as a whitelist solution as to what bindings to inherit from a parent component. It'd be nice to see a blacklist solution to make it more usable with graphs that have a large number of bindings and a small number of overrides.
