### ISSUE TITLE
Allow Hilt to be used in a standalone library

### ISSUE THREAD

**Issue by mattinger** [google/dagger#1954]
Currently, it seems as if Hilt cannot be used in a standalone library.

Consider the case where a library has it's own activities.  The host application would pass down some data which would be used to initialize a dagger graph that is unique to that library.  That dagger graph would then be used to inject the activities using that graph.

This can be done easily by handcrafting dagger components, but not with Hilt.

**Comment by Chang-Eric** [comment]
This unfortunately isn't something we're looking to support right now. One of the main issues is that with the way modules are discovered in Hilt it wouldn't be possible to distinguish which modules belong in the app's components (if they did happen to use Hilt) and the library or other library's components.

The other issue is that it would complicate and confuse the pre-built component hierarchies. Like if your library has an activity, it doesn't make sense to have the parent be the ApplicationComponent since you aren't putting your components in the Application. Similarly, if you had a library that only had fragments and was hosted in an app's activity, you could run into similar things where you want your library fragment to be standalone but then it doesn't make sense for the FragmentComponent parent to be the ActivityComponent anymore.

Sorry to reject this, but hope that makes sense.

**Comment by mattinger** [comment]
Fair enough.  There'd have to be some way of generating a new hierarchy per library, which would likely complicate the annotation processor.  Imagine each librarh having it's own LibraryComponent, LibraryActivityComponent, etc....

I guess i'll be sticking to standard dagger for now at least.

**Comment by bcorso** [comment]
> Consider the case where a library has it's own activities. The host application would pass down some data which would be used to initialize a dagger graph that is unique to that library. That dagger graph would then be used to inject the activities using that graph.

@mattinger is there a reason why your library needs its own components rather than using `@AndroidEntryPoint` to inject themselves?

If the library needs some data passed in via the host application, can you create a qualifier/type that they can bind to? For example, your activity would `@Inject Thing`, and the user of your library would provide `@Binds Thing impl(ThingImpl)`.
