### ISSUE TITLE
Build fail with codeAttr must not be null

### ISSUE THREAD

**Issue by DanShima** [google/dagger#1955]
* What went wrong:
Execution failed for task ':app:transformClassesWithAndroidEntryPointTransformForDebug'.
> codeAttr must not be null

I can't make out what needs to be changed with this error? Do I need to add @AndroidEntryPoint to all my custom views too? If I do that, I still get this error

**Comment by danysantiago** [comment]
Thanks for reporting this. This is happening when you have `@AndroidEntryPoint` in an abstract class and that abstract class has an abstract method with no body. We'll work on a fix, in the meantime you can either add an empty / default body to the method or use the 'long-form' of `@AndroidEntryPoint` as documented [here](https://dagger.dev/hilt/gradle-setup#why-use-the-plugin).

**Comment by MVK059** [comment]
I'm facing the same issue. I tried implementing the suggested solution but it isn't working. First, I cannot add body to an abstract method. 
Second I referred the link you suggested, but that isn't working too. This is what I did. I've a BaseActivity which is abstract and there are few abstract methods which need to be implemented in MainActivity to get some variables. This is my base class.

```
@AndroidEntryPoint
abstract class BaseActivity() : AppCompatActivity() {...}
```
I've tried 
```
@AndroidEntryPoint(AppCompatActivity::class)
abstract class BaseActivity() : Hilt_BaseActivity() {...}
```
But the issue here is the __Hilt_BaseActivity__ is not being created. This is the error __@AndroidEntryPoint class expected to extend Hilt_BaseActivity. Found: Object__
Any ideas on how to get it working while you work on a fix.

**Comment by martipello** [comment]
same issue tried the long form solution to no avail

**Comment by Chang-Eric** [comment]
@MVK059 Hm, that error you get when not using the plugin is weird. Do you have correctErrorTypes turned on? https://kotlinlang.org/docs/reference/kapt.html#non-existent-type-correction

**Comment by MVK059** [comment]
@Chang-Eric  Thank you for the suggestion, but it isn't working. __Hilt_BaseActivity__ is now created. This is how it is
```
@AndroidEntryPoint(AppCompatActivity::class)
abstract class BaseActivity() : Hilt_BaseActivity() {...}
```
But the error I get is 
```
Execution failed for task ':base:transformClassesWithAndroidEntryPointTransformForDebug'.
> codeAttr must not be null
```
