### ISSUE TITLE
Inject a ViewModel (@ViewModelInject) inside a @HiltAndroidTest class

### ISSUE THREAD

**Issue by Flavien-R** [google/dagger#1973]
I would like to use Hilt in order to inject my ViewModel in my test Class.

My ViewModel :

`class LoginViewModel @ViewModelInject constructor(private val sharedPref: SharedPreferences) : ViewModel() { ... }`

In order to inject it, I use :

`val loginViewModel: LoginViewModel by activityViewModels<LoginViewModel>()`

The problem is that we can do it from a Fragment only because it comes from :

`import androidx.fragment.app.activityViewModels`

So I tried the way as described in the https://dagger.dev/hilt/testing page :

` class TestFragment : Fragment() {
        val loginViewModel: LoginViewModel by activityViewModels<LoginViewModel>()
    }`

`@Before
    fun init(){
        val testFragment = TestFragment() 
        testFragment.loginViewModel . . .
    }`

But the Fragment must be attached to an activity to be used. So I think that I don't get the right way do to this kind of stuff.

**Comment by bcorso** [comment]
Hey @Flavien-R,

> But the Fragment must be attached to an activity to be used. So I think that I don't get the right way do to this kind of stuff.

That's correct, for fragments you will also need to create a Hilt activity to attach the fragment  because the fragment is only injected once it's attached to the Activity.

**Comment by danysantiago** [comment]
We don't have a built-in API for easily launching `@AndroidEntryPoint`-annotated fragments in tests but we offer some guidance on this in d.android.com: https://developer.android.com/training/dependency-injection/hilt-testing#launchfragment

**Comment by Flavien-R** [comment]
Hey @bcorso 

Indeed, this is what I understand from the documentation but I don't get the way to do it correctly.

`@AndroidEntryPoint
  class TestActivity : AppCompatActivity()`

I think this is what you mean by 

> create a Hilt activity

Even if this activity is created, how should I attach my testFragment to this activity ? This Fragment just exists to allow me to inject my ViewModel.

**Comment by bcorso** [comment]
> @AndroidEntryPoint class TestActivity : AppCompatActivity()

Yep, that's what I meant. The next steps are:

1. Create an instance of your activity, e.g. using [`ActivtiyScenario.launch(TestActivity.class)`](https://developer.android.com/reference/androidx/test/core/app/ActivityScenario).
2. Add your fragment to the activity's [fragment manager](https://developer.android.com/guide/components/fragments#java).
3. Once the fragment is attached, grab the injected value from the fragment instance, e.g. `testFragment.loginViewModel`.

---------

**Note:** Normally, you would probably use [`FragmentScenario.launch`](https://developer.android.com/reference/androidx/fragment/app/testing/FragmentScenario) to create your fragment, but as noted in the [training doc](https://developer.android.com/training/dependency-injection/hilt-testing#launchfragment) that won't work because the API does not allow you to define a custom activity class. However,  as @danysantiago mentioned above, you can define your own `launchFragmentInHiltContainer` method as described in the [android architecture example app](https://github.com/android/architecture-samples/blob/dev-hilt/app/src/androidTest/java/com/example/android/architecture/blueprints/todoapp/HiltExt.kt#L38). The benefit of this approach is that this method can then be reused across all of your tests.

**Comment by Flavien-R** [comment]
Ok, finally it works fine, thanks a lot ! In fact I used `launchFragmentInHiltContainer` :)
