### ISSUE TITLE
HILT Custom Application object doesn't have components generated when running from Android Instrumentation test

### ISSUE THREAD

**Issue by chaitanyazooms** [google/dagger#1988]
We have a Custom Application which has field injection via an Entry point Accessor.
The Field injection works fine in the production code as the Custom Application's super class is Annotated with @HiltAndroidApp

But when the Custom Application is subclassed and used as a Hilt Test Application in Android Test Runner.

The Field injection fails as the component is not yet generated. It errors out saying "The component was not created. Check that you have added the HiltAndroidRule."

The Custom application's onCreate is called before the @Rule applies as the rule is in the Test Class.

Is there way to get the the components generated even before the HiltAndroidRule is applied?

```
class AppCore: Application{
@Inject B b;
fun onCreate(){
AppInitializerEntryPoint entryPoint = EntryPointAccessors.fromApplication(
                getApplicationContext(),
                AppInitializerEntryPoint.class);
}
}
```

```
@HiltAndroidApp
class HiltAppCore : AppCore()
```

Test Runner
```
public final class TestRunner extends AndroidJUnitRunner {


    @Override
    public Application newApplication(ClassLoader cl, String className, Context context) throws InstantiationException, IllegalAccessException, ClassNotFoundException {
        return super.newApplication(cl, PpbTestHiltApp_Application.class.getName(), context);
    }
```

Custom Test Application class
```
@CustomTestApplication(AppCore::class)
interface PpbTestHiltApp
```

Test Class
```
@HiltAndroidTest
@RunWith(AndroidJUnit4.class)
@UninstallModules(AppLevelOverridesModule.class)
public class NavigationControllerTest {


    public HiltAndroidRule hiltRuleLocal = new HiltAndroidRule(this);

    @Rule
    public final org.junit.rules.RuleChain mRuleChain;
      public HiltAndroidRule hiltRule = new HiltAndroidRule(this);


    public androidx.test.rule.ActivityTestRule activity;
    public androidx.test.rule.GrantPermissionRule grantPermissionRule = androidx.test.rule.GrantPermissionRule.grant(android.Manifest.permission.READ_EXTERNAL_STORAGE, android.Manifest.permission.WRITE_EXTERNAL_STORAGE);


    public NavigationControllerTest() {
        super();



        mRuleChain = org.junit.rules.RuleChain.outerRule(hiltRuleLocal)
                .around(activity)
                .around(grantPermissionRule)
                .around(screenshotTestWatcher);
    }
```

**Comment by bcorso** [comment]
You can do this with [`OnComponentReadyRunner#addListener`](https://github.com/google/dagger/blob/67fc8593e539a18738e3216cf89e5233ade91c02/java/dagger/hilt/android/testing/OnComponentReadyRunner.java#L49), but it's only available within tests, so you would need to separate that logic so that in tests it can be called from within the listener, e.g.

```kotlin
class AppCore: Application{
  fun onCreate() {
     OnComponentReadyRunner.addListener(
         this,
         AppInitializerEntryPoint.class,
         (AppInitializerEntryPoint entryPoint) -> {
           // Do something with your entryPoint
         });
  }
}
```

However, [as noted in the docs](https://dagger.dev/hilt/testing#best-practices) it's better not to put a lot of logic into your test application because that state is shared by all test classes and test cases, which can easily lead to leaking data between tests.

Instead, it's usually better to put your setup logic within a custom `TestRule` so that it can be initialized with each test case.

**Comment by chaitanyazooms** [comment]
> You can do this with [`OnComponentReadyRunner#addListener`](https://github.com/google/dagger/blob/67fc8593e539a18738e3216cf89e5233ade91c02/java/dagger/hilt/android/testing/OnComponentReadyRunner.java#L49), but it's only available in the test artifact, so you would need to separate that logic so that it can be called from within `OnComponentReadyRunner.addListner` in the test app, e.g.
> 
> ```kotlin
> class TestAppCore: Application{
>   fun onCreate() {
>      OnComponentReadyRunner.addListener(
>          this,
>          AppInitializerEntryPoint.class,
>          (AppInitializerEntryPoint entryPoint) -> {
>            // Do something with your entryPoint
>          });
>   }
> }
> ```
> 
> However, [as noted in the docs](https://dagger.dev/hilt/testing#best-practices) it's better not to put a lot of logic into your test application because that state is shared by all test classes and test cases, which can easily lead to leaking data between tests.
> 
> Instead, it's usually better to put your setup logic within a custom `TestRule` so that it can be initialized with each test case. As long as the test rule is called after the `HiltAndroidRule` it will be able to access your entry points.

How could do we use this technique If AppInitializer was a class outside Appcore and using Entry point injection from its constructor.
We have several such custom classes that are using EntryPoint interfaces to do field injection.
Our instrumentation tests has to call the OnCreate of the Production application as this takes the app to a runnable state with the user logged in.

```
class AppCore: Application{
protected static AppCore appInstance;
public static AppCore getInstance() {
        return AppCore.appInstance;
    }

    private static void setInstance(AppCore instance) {
        AppCore.appInstance = instance;
    }
fun onCreate(){
AppCore.setInstance(this);
}
}
```

class AppIniitializer{
@Inject B b;
public AppIniitializer(){

AppInitializerEntryPoint entryPoint = EntryPointAccessors.fromApplication(
                AppCore.getInstance().getApplicationContext(),
                AppInitializerEntryPoint.class);
}

}

**Comment by bcorso** [comment]
The first thing that comes to mind is to try to call `super.onCreate()` from the listener in the test app:

```java
abstract class TestAppCore extends AppCore {
  @Override
  public void onCreate() {
    OnComponentReadyRunner.addListener(this, Object.class, ignored ->  super.onCreate());
  }
}
```

Note that in this case you can just pass `Object.class` as the entry point type because we don't actually care about it. (FWIW, we may want to consider changing the API here to add an overload of the method without the entry point type to simplify this particular usage to `OnComponentReadyRunner.addListener(this, super::onCreate)`.)

----------

Also, is there a reason `AppInitializer` is calling an entry point within it's constructor rather than just using constructor injection?

**Comment by chaitanyazooms** [comment]
AppInitializer is a singleton so having entry point within the private constructor. 
I tried the above approach of calling Oncreate of the Production AppCore.


Getting the below error 
_java.lang.IllegalStateException: Cannot reset state if the test rule has not been set.
	at dagger.hilt.internal.Preconditions.checkState(Preconditions.java:83)
	at dagger.hilt.android.internal.testing.TestApplicationComponentManager.clearState(TestApplicationComponentManager.java:138)
	at dagger.hilt.android.internal.testing.MarkThatRulesRanRule$1.evaluate(MarkThatRulesRanRule.java:94)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
	at com.paypal.merchant.client.framework.PpbAndroidTestRunner.onStart(PpbAndroidTestRunner.java:18)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)_
Test Runner
```
public final class PpbAndroidTestRunner extends AndroidJUnitRunner {

    @Override
    public void onStart() {
        RxIdlerHelper.setupRxJavaPlugins();

        super.onStart();
    }

    @Override
    public Application newApplication(ClassLoader cl, String className, Context context) throws InstantiationException, IllegalAccessException, ClassNotFoundException {
        return super.newApplication(cl, PpbHiltTestApplication_Application.class.getName(), context);
    }

    @Override
    public void onDestroy() {
        RxIdlerHelper.resetRxJavaPlugins();

        super.onDestroy();
    }
}
```
Test class

```
@HiltAndroidTest
@RunWith(AndroidJUnit4.class)
@UninstallModules(AppLevelOverridesModule.class)
public class NavigationControllerTest {

   
    @Rule
    public HiltAndroidRule hiltRule = new HiltAndroidRule(this);
@Before
    public void init() {
        hiltRule.inject();
    }
```

**Comment by chaitanyazooms** [comment]
Any help why this error would occur
Getting the below error
```
java.lang.IllegalStateException: Cannot reset state if the test rule has not been set.
at dagger.hilt.internal.Preconditions.checkState(Preconditions.java:83)
at dagger.hilt.android.internal.testing.TestApplicationComponentManager.clearState(TestApplicationComponentManager.java:138)
at dagger.hilt.android.internal.testing.MarkThatRulesRanRule$1.evaluate(MarkThatRulesRanRule.java:94)
```

**Comment by bcorso** [comment]
Does the failure still happen when you just run a single `@Test` test case?

My guess is that the failure is happening because state isn't being cleared before starting a new test case. If we look at where the failure is happening, [here](https://github.com/google/dagger/blob/3a169af264e1bf42373d41096a5d330955567468/java/dagger/hilt/android/internal/testing/MarkThatRulesRanRule.java#L94)

```
try {
  componentManager.checkStateIsCleared();            // <-- probably failing here
  ...
  componentManager.setHasHiltTestRule(description);  // <-- rule is set here, but never gets here.
  base.evaluate();
} finally {
  componentManager.clearState();                     // <-- throws here because rule isn't set.
}
```

My guess is that `checkStateIsCleared()` is failing but the user only sees the failure in the finally block because the call to `clearState()` fails too (which is definitely a bug we should fix).

Can you put a debugger inside `checkStateIsCleared()` and verify that's what is failing. Also, if that is what is failing can you see which state isn't cleared yet?

**Comment by chaitanyazooms** [comment]
yes, This failure is happening when i run a single test case.

**Comment by bcorso** [comment]
Thanks for checking! I still think something in the `try` block is failing before you get to the `finally` block, so if you can debug to see what's failing there, that would help. 

Also, if you have a repro app I can debug too.

**Comment by chaitanyazooms** [comment]
@bcorso I have a created a public repo for the issue we are discussing.
https://github.com/chaitanyazooms/Hilt-migration/blob/master/app/src/androidTest/java/com/cmovva/hiltsample/ExampleInstrumentedTest.kt

**Comment by bcorso** [comment]
Thanks for the repro case!

Sorry, I should have realized this would be an issue before I suggested it. The failure is because we don't allow the `OnComponentReadyRunner` to set a listener before the test runs.

I think the best advice I have is to call your app initialization from a custom `TestRule`. This is generally the recommended approach anyway because it ensures you are reinitializing state before each test case (and cleaning it up after each test case).

If possible, move the initialization logic into `AppCore.init()`, and in your test you call it within the test rule rather than onCreate:

```java
public final class AppInitTestRule implements TestRule {
  @Override
  public Statement apply(final Statement base, Description description) {
    return new Statement() {
      @Override
      public void evaluate() throws Throwable {
        ((AppCore) ApplicationProvider.getApplicationContext()).init();
        base.evaluate();
        // Do cleanup here
      }
    }
  }
}
```

Hopefully this leads you to something that works for your use case.

**Comment by bcorso** [comment]
Closing this. Feel free to reopen if you still have questions.
