### ISSUE TITLE
How to provide viewModelScope or lifecycleScope as dependencies 

### ISSUE THREAD

**Issue by mochadwi** [google/dagger#2004]
Is there any alternatives ways to provides a `viewModelScope` or `lifecycleScope` instead of `CoroutineScope(Job() + Dispatchers.Main)`?

Gist references: https://gist.github.com/RBusarow/2e79e15bb27347b8de811a91b5f4717e#file-dagger2qualifiedcoroutinescope-kt

Article references: https://proandroiddev.com/stronger-typing-for-coroutinescopes-f32f87b515f6

Our approach using **Hilt** in `:base` module & **Vanilla Dagger** in `:dfm` module
```
//  :base - Repository
interface LoginRepository {
  fun doLogin(): String
}

class LoginRepositoryImpl @Inject constructor(val coroutineScope: CoroutineScope) : LoginRepository {
 // impl. omitted
}
```

```
// :base - Setup Dependencies Modules
typealias UiScope = CoroutineScope(Job() + Dispatchers.Main)

@DisableInstallInCheck
@Module
interface PresentationModule {

    @get:Binds
    val UiScope.postExecutionThread: CoroutineScope

    @get:Binds
    val LoginRepositoryImpl.loginRepository: LoginRepository
}

// any other VM module configuration is omitted for verbosity
```

```
// :dfm/scope/LoginScope.kt

// :dfm/LoginComponent.kt
@LoginScope
@Component(
    modules = [from.base.PresentationModule::class]
)
interface LoginComponent {
    fun inject(activity: LoginActivity)
}

// :dfm/LoginViewModel.kt
class LoginViewModel @Inject constructor(
   private val repository: from.base.LoginRepository
) : ViewModel() {
   // impl. omitted
}

// :dfm/LoginActivity.kt
override oncreate() {
   DaggerLoginComponent.inject(this)
}
```

**Comment by danysantiago** [comment]
Hilt has a default binding for activities and fragments, you can provide both `lifecycleScope` and `viewModelScope` using those bindings.

For example, a module that can provide `lifecycleScope` using the ktx extensions would look like this:
```
@Module
@InstallIn(ActivityComponent::class)
object CoroutineModel {
  @Provides
  fun provideLifecycleCoroutineScope(activity: Activity): LifecycleCoroutineScope = 
     (activity as ComponentActivity).lifecycleScope
}
```

If you want to provide dependencies to your DFM modules take a look at the information in https://developer.android.com/training/dependency-injection/hilt-multi-module#dfm

Since this is not an issue with Hilt or Dagger I'll be closing this issue now. These types of questions are better suited for https://stackoverflow.com/ were a bigger community might be able to help you since we might not be experts in the type of bindings you want Dagger & Hilt to provide, in this case Coroutine Scopes.

**Comment by yschimke** [comment]
Can we reopen this, we can do this for a ServiceScoped

```
    @ServiceScoped
    @Provides
    fun serviceCoroutineScope(
        service: Service
    ): CoroutineScope {
        return (service as LifecycleOwner).lifecycleScope
    }
```

It would be nice to be able to do this for ActivityRetainedScoped

```
    @ActivityRetainedScoped
    @Provides
    fun providesCoroutineScope(
        viewModel: ViewModel
    ): CoroutineScope = viewModel.viewModelScope
```

**Comment by mairs8** [comment]
@yschimke can you please provide how you currently inject viewModelScope with Hilt?

**Comment by yschimke** [comment]
I'm doing the same for view models. But hoping instead I could access viewModel.viewModelScope.

I might file a request instead for optio al LifecycleScope or LifecycleOwner for services, activities and viewmodels.
