### ISSUE TITLE
ApplicationComponent is not annotated with @DefineComponent 

### ISSUE THREAD

**Issue by AntonHolovin** [google/dagger#2009]
[The documentation](https://dagger.dev/hilt/modules) encourages us to install modules in ApplicationComponent, but as soon as we define a module, we get an error message:

```
dagger.hilt.android.components.ApplicationComponent, expected to be annotated with @DefineComponent
```

The module:
```kotlin
@Module
@InstallIn(ApplicationComponent::class)
abstract class DataModule {
    @Binds
    abstract fun provideRepository(repositoryImpl: RepositoryImpl): Repository
}
```

Dependencies: 
```groovy
implementation "androidx.hilt:hilt-lifecycle-viewmodel:1.0.0-alpha02"
implementation "com.google.dagger:hilt-android:2.28.3-alpha"
kapt "androidx.hilt:hilt-compiler:1.0.0-alpha02"
kapt "com.google.dagger:hilt-android-compiler:2.28-alpha"
```

**Comment by bcorso** [comment]
Hi Anton,

I think your issue is that your dagger-compiler is using `2.28-alpha` rather than `2.28.3-alpha`.

While it's still okay to use `ApplicationComponent`, we've renamed that component to `SingletonComponent` in [`2.28.2`](https://github.com/google/dagger/releases/tag/dagger-2.28.2). Currently, you can use either class in your code, but we recommend switching to `SingletonComponent` because it's likely that we'll eventually remove `ApplicationComponent` in a future release.

Also, thanks for pointing out that the documentation is out of date. I'll file a bug to update that.

**Comment by AntonHolovin** [comment]
Hi Brad, 

You are right! Android Studio did not let me know that the dagger-compiler should be updated too. I'll use gradle-versions-plugin next time.
