### ISSUE TITLE
Feature Request: Allow applying @IntoSet to Constructors

### ISSUE THREAD

**Issue by JaniruTEC** [google/dagger#2026]
### Request
Please allow applying the `@IntoSet`-Annotation to constructors to automatically add them to the corresponding sets. 

### Technical background
Famously `@IntoSet` can be used to automatically add the result (of type T) of all annotated providers to Sets of Type T.
As mentioned the condition is that T is provided by a provider method. This often results in methods of the follow contract:
```
@Provides
@IntoSet
@MyScope
public T provideT() {
    return new TImpl();
}
```

### Reasoning
As seen the method merely wraps a constructor for `TImpl`. 
From my perspective `@IntoSet` is designed to be used independently from the injected Classes. Citing from the [Dagger Docs:](https://dagger.dev/dev-guide/multibindings.html)
> Dagger allows you to bind several objects into a collection even when the objects are bound in different modules using multibindings. Dagger assembles the collection so that application code can inject it without depending directly on the individual bindings.

> You could use multibindings to implement a plugin architecture, for example, where several modules can contribute individual plugin interface implementations so that a central class can use the entire set of plugins. Or you could have several modules contribute individual service providers to a map, keyed by name.

Therefore having to use a wrapper method to merely inject a constructor contradicts the idea behind `@IntoSet`. Following this logic being able to apply the annotation together with any qualifier to constructors would and allowing developers to leave out the wrapper-method seems desirable. Also adding new Implementations of T gets easier and the maintenance cost sinks.

### Implementation/Definition suggestion
1. Change the `@Target` of `@IntoSet` from `@Target(METHOD)` to `@Target({METHOD, CONSTRUCTOR})`
2. Require all constructors that are annotated with `@IntoSet` to also be annotated with `@Inject` to satisfy any dependencies.
3. Change the contract of `@IntoSet` from roughly `Adds the result of all annoated providers that return T to the Set<T> set.` to `Adds the result of 1) all annotated providers that return T and 2) all annotated constructors of classes that match T to the Set<T> set.`

**Comment by bcorso** [comment]
Hi @JaniruTEC,

You can use `@Binds` rather than `@Provides` to reduce some of the boilerplate:

```
@Binds
@IntoSet
@MyScope
abstract T provideT(TImpl tImpl);
```

However, for the suggested proposal IIUC annotating the constructor of `TImpl` with `@IntoSet` would give you a `Set<TImpl>`? But often that's not what you want -- you want to contribute it to a `Set<T>` instead. Dagger would either need to try to infer that automatically (probably infeasible), or allow you to pass that information in via the annotation (which doesn't work well with generic types). Please let me know if I've missed something or misunderstood. Thanks!

**Comment by JaniruTEC** [comment]
Hi @bcorso,

thanks for the quick answer and for the suggestion using `@Binds`. That in fact slipped my mind, but it's not quite what this proposal is about. I really would like to further minimize it to the point, where only the class itself needs an annotation instead of a helper method.

> However, for the suggested proposal IIUC annotating the constructor of TImpl with @IntoSet would give you a Set<TImpl>? But often that's not what you want -- you want to contribute it to a Set<T> instead.

That's probably right and I do indeed want to contribute to a `Set<T>`.

> Dagger would either need to try to infer that automatically (probably infeasible)
You're right. That's infeasible. Dagger would have to roll dice if my class implements two Interfaces that are mentioned elsewhere.

> allow you to pass that information in via the annotation (which doesn't work well with generic types).
That should work IMO, let me give you an example:
```
@BindAs(T.class) //The magic happens here
@IntoSet //Or @IntoSet(T.class) instead of @BindAs
@Inject
public TImpl() { }
```

Thanks for your time!

**Comment by bcorso** [comment]
I definitely hear what you're saying and I agree it's a pain point. However, I'm just not convinced this is the right solution for a couple reasons.

  1. As mentioned, it doesn't handle parameterized types well
  2. There's no way to remove the type from the set. For example, you still want to inject `Set<T>` but you don't want that particular class in the set. With modules you just remove the module, but with this solution  you would have to remove the class from your class path, which can either be difficult or impossible if it's used elsewhere. 
  3. This problem comes up a lot of other context than `@IntoSet`, so I think it would be a mistake to just try to solve it for this particular use case and not more generally. For example, binding any implementation to an interface has many of the same pain points.

Sorry, I know these issues might not be as big of a concern to your particular project.

**Comment by JakeWharton** [comment]
Prior issues: #633 & #510

**Comment by bcorso** [comment]
Ah, regarding the last point I just added, it looks like that was the main reason #510 was closed previously.
