### ISSUE TITLE
Multibinding doesn't work with Component Dependencies

### ISSUE THREAD

**Issue by marcellogalhardo** [google/dagger#2027]
Dagger docs states:

> A binding in a subcomponent can depend on a multibound set or map from its parent, just as it can depend on any other binding from its parent. But a subcomponent can add elements to multibound sets or maps that are bound in its parent as well, by simply including the appropriate @Provides methods in its modules.

However, the same is not true when using component dependencies. If one has many small components that shares dependencies using "component dependencies" - a "child" component that has a dependency to another component might not be able to contribute to its Graph.

For example, consider the following classes:

```kotlin
@Component
interface CommonComponent {
    fun factoryBindings(): Map<String, Factory>
}

@Component(
    modules = [FeatureModule::class]
    dependencies = [CommonComponent::class]
)
interface FeatureComponent

@Module
interface FeatureModule {
    // Contributes to factories map.
    @[Binds IntoMap FactoryKey("featureFactory")]
    fun featureFactory(impl: FeatureFactory): CustomFactory
}

class CompositeCustomFactory @Inject constructor(
   val factoriesMap: Map<String, Factory>
)
```

In this if I use `FeatureComponent` to inject the `CompositeCustomFactory`, I would only receive the ones contributed inside `CommonComponent` - ignoring the ones inside `FeatureComponent` (e.g., `FeatureFactory`).

Note that using a `subcomponent` setup, it'd work as expected.

Is this a design decision and/or limitation of Dagger, a bug when dealing with component dependencies or am I doing something wrong?

Obs: #1186 is related but the use cases are slightly different so I opened this PR.

**Comment by bcorso** [comment]
Hi Marcello,

Related issues: #1186, #1112

> In this if I use FeatureComponent to inject the CompositeCustomFactory, I would only receive the ones contributed inside CommonComponent - ignoring the ones inside FeatureComponent (e.g., FeatureFactory).

The `CommonComponent` only exposes a `Map<String, Factory>` so `FeatureComponent` has no way to know that the map should actually be contributed into its multibinding map.  I don't think there's currently a great way to do this besides exposing the `CommonComponent`'s map with a qualifier and doing something similar to https://github.com/google/dagger/issues/1112#issuecomment-474985867.

However, the part that might be a bug is that I would have expected Dagger to give an error because you have duplicate bindings. In particular, the multibinding `Map<String, Factory>` in `FeatureComponent` should conflict with the normal `Map<String, Factory>` in `CommonComponent`.

**Comment by Chang-Eric** [comment]
I think the issue is the return type in the `FeatureModule` is `CustomFactory` so it is adding to the `Map<String, CustomFactory>` and hence doesn't conflict.

**Comment by marcellogalhardo** [comment]
Hey, thanks for the quick feedback!

I will try to provide a small sample application simulating it and I will be posting here. Thanks again.

**Comment by bcorso** [comment]
Hi Marcello, no need to provide an example. I think @Chang-Eric is right that the reason you don't get a conflict is because the `FactoryComponent` is installing into the map with type `Map<String, CustomFactory>`.

However, I think the suggestion in https://github.com/google/dagger/issues/2027#issuecomment-670589644 still applies, just make sure your map types are the same.

**Comment by marcellogalhardo** [comment]
Hey @bcorso,

The workaround is working as expected and it is enough for my UseCase and therefore, I will close this issue.

Thanks a lot for yours and @Chang-Eric help! ✌️
