### ISSUE TITLE
Hilt+multibindings non-determinism

### ISSUE THREAD

**Issue by ZacSweers** [google/dagger#2032]
After moving my project to Hilt, I've found a case of non-deterministic behavior regarding multibindings contributed from upstream (gradle) modules.

To give a general bit of context
* my project has a number of "services" that contribute instances of their service to a [multibinding declared downstream in the consuming `app` module](https://github.com/ZacSweers/CatchUp/blob/a4696aec5350b787debda9ab219fca914a4851b8/app/src/main/kotlin/io/sweers/catchup/ui/activity/MainActivity.kt#L136-L140).
* the project has an annotation processor that generates a dagger module that `includes` all these services' upstream modules. Sort of similar to some of the functionality that [Anvil](https://github.com/square/anvil) offers as a compiler plugin. In my project, this generated module is generated from [here](https://github.com/ZacSweers/CatchUp/blob/main/service-registry/service-registry/src/main/kotlin/io/sweers/catchup/serviceregistry/CatchUpServiceRegistry.kt) and looks like this:
  ```kotlin
  @Module(includes = [
      HackerNewsModule::class,
      RedditModule::class,
      MediumModule::class,
      ProductHuntModule::class,
      SlashdotModule::class,
      DesignerNewsModule::class,
      DribbbleModule::class,
      GitHubModule::class,
      UnsplashModule::class,
      UplabsModule::class
  ])
  @InstallIn(ActivityComponent::class)
  object ResolvedCatchUpServiceRegistry : CatchUpServiceRegistry
  ```
* The generated hilt app component is `DaggerCatchUpApplication_HiltComponents_ApplicationC`

One example generated factory from a service is `GitHubMetaModule_Companion_ProvideGitHubServiceMeta$github_releaseFactory`. _Sometimes_, it properly includes these upstream contributed services to the multibinding. Often times however, it does not and just provides empty `ImmutableMap.<...>of()` instances.

To reproduce, just clone and build this project - https://github.com/ZacSweers/CatchUp - and run `./gradlew :app:assembleDebug`

**Comment by bcorso** [comment]
Hey Zac,

IIUC, the annotation processor is processing [`@ServiceRegistry`](https://github.com/ZacSweers/CatchUp/blob/main/service-registry/service-registry-annotations/src/main/kotlin/io/sweers/catchup/serviceregistry/annotations/ServiceRegistry.kt) annotations and generating the `@InstallIn` module you show above? You will need to annotated all annotations that trigger generation of Hilt input with [`@GeneratesRootInput`](https://dagger.dev/hilt/creating-extensions#generatesrootinput) so that the Hilt processors knows to wait for your processor to generate its sources before we generate the components.

**Comment by ZacSweers** [comment]
Dany pointed me to that as well, but I found it didn't make a difference in my testing 😕. It's also somewhat inconvenient as it requires making the annotations module and any that depend on it Android projects (I faked this by just copying in the GeneratesRootInput annotation with the same package name)

**Comment by bcorso** [comment]
> Dany pointed me to that as well, but I found it didn't make a difference in my testing 😕. 

Okay, I can try to reproduce using your repro steps this week.

**Comment by bcorso** [comment]
Actually, just realized how big the repro app is. Do you happen to have a minimal, reproducible example? Otherwise it might be faster for me to ask you some questions.

1. For each `@InstallIn my.pkg.FooModule` usage we generate a class like `hilt_aggregated_deps.my_pkg_FooModuleModuleDeps`. Can you check that this source file is generated in the module where you are generating the `@InstallIn`?

2. If 1 is true, can you verify that the difference between the bindings being installed or not is just whether the generated Hilt_Component installed that module or not.

**Comment by danysantiago** [comment]
I took a quick look at Zac's project. It not enough to just add `@GeneratesRootInput` to the `service-registry-annotations` Gradle pojrect, Zac would also need to apply the `hilt-android-compiler` to it, but you'll probably run into more trouble because the aggregating class generated uses a type from the `hilt-android` artifact but since thats an AAR you won't be able to use it (you can copy the small class though, its [GeneratesRootInputPropagatedData](https://github.com/google/dagger/blob/master/java/dagger/hilt/internal/generatesrootinput/GeneratesRootInputPropagatedData.java)). Once that done, I think things should work fine.

In the meantime we are still working on splitting the `AAR` into the core Hilt APIs and the Android specifics, once that is done these types of cases should be along with using `@InstallIn` in non-android projects should be doable.

**Comment by danysantiago** [comment]
Turns out adding `@GeneratesRootInput` is quite not necessary since the modules are generated in a separate Gradle module that is not the root so they will be generated before Hilt aggregates them into components, it would still be good to add it but not quite necessary in this case.

Anyway, the root issue is that the Dagger modules generated by the `service-registry-compiler` are in Kotlin sources and based on http://issuetracker.google.com/issues/163423535#comment2, KAPT will not trigger new rounds for newly generated Kotlin sources with annotations to process. Therefore causing Hilt to not generate the aggregating metadata needed for them to be picked up later in the root. You'll have to update your processor to generate them in Java, sorry.

**Comment by ZacSweers** [comment]
Thanks for getting to the bottom of this! I thought kapt supported rounds now but didn't realize it was only for java sources. Easy enough to fix on my end 👍
