### ISSUE TITLE
Issue with subcomponent repeated modules: "Is bound multiple times"

### ISSUE THREAD

**Issue by douglasiacovelli** [google/dagger#2050]
I'm developing an android app and I'm facing an issue when using subcomponents.

1. There's a Fragment A, which has its own Component, which installs Module A and injects a class `ClassFoo`.
2. There's nested fragment (Fragment B), which has a Subcomponent, which also installs Module A and injects the same class as Fragment A: `ClassFoo`.
3. The Fragment A instantiates Fragment B inside of it and one of its modules installs the Subcomponent of Fragment B.

When in the nested fragment (Fragment B) I want to inject the `ClassFoo` I'm having issues. The repeated modules seem to be instantiated as new ones and Dagger complains saying:
```
[Dagger/DuplicateBindings] com.mypackage.ClassFoo is bound multiple times
```
 

My Subcomponent builder method:
```
@Subcomponent.Builder
    interface Builder {
        fun build(): AppBannerDialogComponent
    }
```

The moduleA has a constructor with no args.
Ps: I know if I remove `ModuleA` from my subcomponent modules list that it will work, but I'd like to be explicit so I can use in other contexts that may or may not have `ModuleA` installed. I also know that if I remove `ClassFoo` from FragmentA that it works.

**Comment by Chang-Eric** [comment]
I'm assuming `ModuleA` has a binding for `ClassFoo`? If so, the issue here is that bindings in subcomponents are inherited from the parent. Even though both bindings come from the same module, Dagger treats them differently because some things are based on the context of the component they binding is installed in like which scope annotations are allowed. You'll want to just install modules at the widest scope they are needed.

From your PS, I think the way to think about it is figuring out if FragmentB's API is that it comes with a definition for `ClassFoo` or if it requires a `ClassFoo` from its user. It kind of needs to be one or the other. If you want to set up a default that can be overridden, you would have to do that with some extra machinery with optionals.

**Comment by douglasiacovelli** [comment]
You're right about your assumption, @Chang-Eric! I forgot to mention `ClassFoo` is provided by `ModuleA`.

Thank you for your explanation! I've gotta make a choice.
As from the docs, I though Dagger would handle that and reuse the same instances of the already created modules, as seen here https://dagger.dev/dev-guide/subcomponents.html on "Repeated modules".

**Comment by Chang-Eric** [comment]
Hm...I wasn't aware of those docs, I will need to check that and get back to you...

**Comment by Chang-Eric** [comment]
Hm, from reading that doc and trying it out, I think I was wrong and you are right that subcomponents should be able to install the same module. I honestly kind of feel like it'd be best not to do that, but I guess that is something else at this point.

Do you have more info on that duplicate binding error? Usually it should have more information telling you what the duplicated bindings are.

**Comment by douglasiacovelli** [comment]
```
/.../build/tmp/kapt3/stubs/stgDebug/com/example/FragmentAComponent.java:8: error: [Dagger/DuplicateBindings] com.example.ClassFoo is bound multiple times:
public abstract interface FragmentAComponent {
                ^
      @org.jetbrains.annotations.NotNull com.example.ClassFoo com.example.AppComponent.provideClassFoo()
      @Binds @org.jetbrains.annotations.NotNull com.example.ClassFoo com.example.WebRouterModule.bindsClassFoo(com.example.ClassFooImpl)
      com.example.ClassFoo is injected at
          com.example.FragmentB.mClassFoo
      com.example.FragmentB is injected at
          com.example.FragmentBComponent.inject(com.example.FragmentB) [com.example.FragmentAComponent → com.example.FragmentBComponent]
```

I don't have a sample code. I changed the names of the classes and methods of my project to reflect the example I gave earlier.

One more thing I though wouldn't make any difference for the sake of the sample is that: This ModuleA actually is installed on the AppComponent, which my FragmentAComponet depends on. So in theory I though it would be the same as installing on the FragmentAComponent itself

**Comment by Chang-Eric** [comment]
Oh, it looks like you have a combination of subcomponents and component dependencies. The line `@org.jetbrains.annotations.NotNull com.example.ClassFoo com.example.AppComponent.provideClassFoo()` indicates that the conflict is from the AppComponent as a component dependency. Even if the binding in AppComponent is from `ModuleA` because it is a component dependency it is opaque to Dagger so we can't tell it is from the same source (since it is treated like it is just an interface).

**Comment by douglasiacovelli** [comment]
Oh wow! I'm sorry I didn't mention that earlier. My thought was that it wouldn't make such a difference.

So I believe the first suggestion you gave still applies. I'll take that into consideration.

Thank you for helping me figuring that out, @Chang-Eric! 
I'm closing the issue for now :)
