### ISSUE TITLE
Runtime parameters to component creation calls

### ISSUE THREAD

**Issue by stefanrusek** [google/dagger#210]
When working with List<>s of things, mapping creation calls to objects in a list becomes unwieldy.

For examples, consider we have a list of objects and we are implementing a RecyclerView.Adapter class. We need to create an arbitrary number of objects that implement ViewHolder<T>. ViewHolder's have a View parameter in their constructors.   While we could argue the merits of this particular design decision by Google, the fact is that there are times when we need to create an object with one or more dependencies that only apply to that single object. There are a number of inelegant workarounds, such as having a special module and subcomponent just for creating instances of the single class. Sometimes it is possible to create a single instance then call an .inject() method, but it isn't always possible.

The cleanest solution would be to support this kind of component method:

    interface ProfileComponent {
        ProfileReviewHolder profileReviewHolder(View view);
    }

    class ProfileReviewHolder extends ViewHolder<ProfileReview> {
        @Inject
        ImageDownloader imageDownloader;

        @Inject
        public ProfileReviewHolder(View view) {
            super(view);
        }
    }

**Comment by elincoln** [comment]
:+1:

**Comment by netdpb** [comment]
I don't think every class needs to be instantiated by a DI framework. Data structures like sets and maps shouldn't be, for instance. Maybe `ViewHolder` classes shouldn't be either.

In your example, what does `ProfileReviewHolder` do with its `imageDownloader` field? Could you refactor it so that it takes a `ViewHolder<>` argument, or a list of them, so that instead of `ProfileReviewHolder` depending on an `ImageDownloader`, some controller class passes the views to the downloader?

**Comment by tbroyer** [comment]
How about [AutoFactory](https://github.com/google/auto/tree/master/factory)? You could then inject a `ProfileReviewHolderFactory` where you need it or have a method in your `ProfileComponent` returning the factory (instead of acting like a factory as originally proposed). I think you'd have to move the `ImageDownloader` as a constructor parameter though (and annotate it with `@Provided`).

**Comment by netdpb** [comment]
+1, @tbroyer.

**Comment by netdpb** [comment]
Closing for now, as @tbroyer and I suggested a way to handle this situation.
