### ISSUE TITLE
[Hilt] Build performance for unit tests

### ISSUE THREAD

**Issue by snepalnetflix** [google/dagger#2121]
Our project has about 800 test class (declared mostly in *Test.kt files).

As a part of our migration to Hilt, we annotated each test class with @HiltAndroidTest.

Since the migration we've noticed that our build times have increased by about 50%.

Is this expected? If so are there any best practices to improve performance?

One thing we've noticed is that each test generates +20 classes for dagger components. If that's the root cause of the performance issue could we improve performance by sharing dagger components across tests?

**Comment by bcorso** [comment]
Hi @snepalnetflix, thanks for sharing this!

> Since the migration we've noticed that our build times have increased by about 50%.
>
> Is this expected?

We do expect some build time impact from using @HiltAndroidTest because we're generating separate Hilt components for each test. This was a trade-off that was made so that each test can be independently configured to install, replace, or uninstall its own bindings without affecting other tests.

> are there any best practices to improve performance?

One thing to keep in mind is that for each @AndroidEntryPoint/@EntryPoint the generated Dagger components must satisfy all transitive dependencies for each entry point whether or not your test actually uses them. For example, suppose we have the following independent activities and their corresponding tests:
:app
  |_ src
     |_ main
        |_ FooActivity.kt
        |_ BarActivity.kt
     |_ test
        |_ FooActivityTest.kt
        |_ BarActivityTest.kt

In this case, Hilt must generate a component for each test that includes the injector (and all transitive dependencies) for both FooActivity and BarActivity even if each test individually only tests one of these. One way to avoid this issue is to split into separate Gradle modules, e.g.
:fooFeature
  |_ src
     |_ main
        |_ FooActivity.kt
     |_ test
        |_ FooActivityTest.kt
:barFeature
  |_ src
     |_ main
        |_ BarActivity.kt
     |_ test
        |_ BarActivityTest.kt

In addition to the normal build parallelism that you get from splitting Gradle modules, the generated Hilt component will also be smaller because it only includes entry points for the code you're testing. Note that this assumes that fooFeature and barFeature are actually independent. If they are dependent, e.g. say FooActivity intents to BarActivity you may want to try to break that explicit dependency by trying not to directly reference BarActivity.

> One thing we've noticed is that each test generates +20 classes for dagger components. If that's the root cause of the performance issue could we improve performance by sharing dagger components across tests?

It may be possible, e.g. if we could allow `@HiltAndroidTest` on a base class that each test extends. However, that would make the tests less flexible, more interdependent, and more complicated as DI and configuration logic of all tests mix into a single base class. For this reason, we'd rather not go that route.

**Comment by snepalnetflix** [comment]
Thanks for the detailed response. We have a modularized app but due to legacy reasons all our tests pull in all modules as dependencies. Sounds like the best path forward is to prune our test dependencies.
