### ISSUE TITLE
Question about sample

### ISSUE THREAD

**Issue by dumihi** [google/dagger#2141]
As the sample https://github.com/google/dagger/tree/master/examples/maven/coffee/src/main/java/example/dagger
I wonder why dont have any module class for CoffeeLogger ?

**Comment by bcorso** [comment]
There's no need to create a module for `CoffeeLogger` because Dagger already knows how to create it since it has an `@Inject` constructor. If you look at [`CoffeeMaker`](https://github.com/google/dagger/blob/master/examples/maven/coffee/src/main/java/example/dagger/CoffeeMaker.java#L28-L33), it injects `CoffeeLogger` directly:

```java
public class CoffeeMaker {
  @Inject
  CoffeeMaker(CoffeeLogger logger, Lazy<Heater> heater, Pump pump) {
    this.logger = logger;
    this.heater = heater;
    this.pump = pump;
  }
}
```

Note that the reason we needed [`HeaterModule`](https://github.com/google/dagger/blob/master/examples/maven/coffee/src/main/java/example/dagger/HeaterModule.java) and [`PumpModule`](https://github.com/google/dagger/blob/master/examples/maven/coffee/src/main/java/example/dagger/PumpModule.java) is because Dagger doesn't know how to create a [`Heater`](https://github.com/google/dagger/blob/master/examples/maven/coffee/src/main/java/example/dagger/Heater.java) or a [`Pump`](https://github.com/google/dagger/blob/master/examples/maven/coffee/src/main/java/example/dagger/Pump.java) (they're just interfaces).
