### ISSUE TITLE
 Lazy load

### ISSUE THREAD

**Issue by lylissuperman** [google/dagger#2173]
Is there any support for this kind of Value that requires lazy load? Or they already have ？

```
@Module
@InstallIn(ActivityComponent::class)
class Module {
     @IntoMap
     @StringKey(MAIN)
     @Provides
     fun providerSettingTest(): Lazy<ITest> {
      return lazy {
        Test(TestSealed.Test(TestSealed.Main))
      }
    }

    @IntoMap
    @StringKey(MAIN_1)
    @Provides
    fun providerSettingTest1(): Lazy<ITest> {
    }
}
```

**Comment by JakeWharton** [comment]
Dagger is already lazy in that it will only invoke the provider when it is first needed for injection. If you want to delay that even farther, inject a `Provider<T>` or `Lazy<T>` (or for a map, `Map<K, Provider<V>>`). You do not have to change the module to support this.

**Comment by lylissuperman** [comment]
本来是想要用注入 Map的方式来减少依赖，或者说不用 if/else  , 但是 Test()创建就没办法注入了，这少了连贯性

**Comment by lylissuperman** [comment]
Originally, I wanted to use the method of injecting Map to reduce dependencies, or without if/else, but there is no way to inject Test() creation, which lacks consistency

**Comment by lylissuperman** [comment]
> Dagger is already lazy in that it will only invoke the provider when it is first needed for injection. If you want to delay that even farther, inject a `Provider<T>` or `Lazy<T>` (or for a map, `Map<K, Provider<V>>`). You do not have to change the module to support this.

Originally, I wanted to use the method of injecting Map to reduce dependencies, or without if/else, but there is no way to inject Test() creation, which lacks consistency

**Comment by Chang-Eric** [comment]
I'm not sure if this is also part of the question, but if you have something that you want to force to be injected as a `Lazy<T>` or `Provider<T>` because you know the provision will be slow or expensive, in those cases our recommendation is that you manually wrap that in a class yourself. So instead of having for example a `ListenableFuture<Data>` as a binding, have a `DataFetcher` class that has a method that returns `ListenableFuture<Data>`. This might seem like a pain, but it usually leads to better code overall in my opinion.
