### ISSUE TITLE
Provide Activity to service

### ISSUE THREAD

**Issue by AbdElraoufSabri** [google/dagger#2182]
My started service needs a notification helper to be able to create foreground notification when it starts. That notification is used to launch MainActivity. I can't provide the activity to the application component.

As I'm understanding A service is scoped to the service component or the application component.
Activities have the scope of the Activity component.

So my question is: **How to pass activity reference to the service?** 

**I just need the class type to create intent.**

**Comment by danysantiago** [comment]
You can't and should not reference an activity from a service since these two are different Android components with their own lifecycles. You should be able to create an intent for the activity using the activity's class name, e.g. `MyActivity.class`. 

In terms of Hilt the common components between these two is the `SingletonComponent`/`ApplicationComponent` so any dependency declaration in that components can be used by both the service and the activity. 

There are also a handful of other ways for an activity and service to communicate, starting the service with an intent and some data, or the activity binding to the service, all of those are unrelated to Dagger though.

**Comment by AbdElraoufSabri** [comment]
Problem solved, I Inject an object at the application component with a nullable public field. 
When the activity is created -> set that variable
when activity is destroyed -> unset it.

from service, -> use that nullable variable.

Not a dagger problem though. But thank you
