### ISSUE TITLE
about FragmentScope

### ISSUE THREAD

**Issue by byrxs5216** [google/dagger#2241]
did u consider this kind of case: ChildFragment needs to reuse ParentFragment's object instead of creating a new one。hilt may not support this kind of case

**Comment by Chang-Eric** [comment]
This has come up a few times before so I think I should add something to the Hilt docs. But this is a known limitation. Unfortunately, there's no good way I know of to really support this. The depth of your parent fragments is really unknown until runtime so there isn't a good way to represent this statically. I think it can also probably get confusing with which fragment a binding is scoped to.

You can, however, support this yourself for individual bindings at runtime. For example, have a provider method that under some condition just delegates to a parent fragment via an EntryPoint. For example:

```
@Provides
static Foo provideFoo(Fragment fragment) {
  if (fragment.getParentFragment() == null) {
    return new Foo();
  } else {
    return EntryPointAccessors.fromFragment(fragment.getParentFragment(), FooEntryPoint.class).getFoo();
  }
}
```

Another reason we don't directly support this is you likely don't want every binding to have this behavior, and many times you might want to hard code a certain fragment that is the owner (e.g. instead of the base case being getParentFragment() == null, make it be like fragment instanceof FooFragment).

Anyway, hope that helps. I'll try to write up something for the docs on this when I get a chance too.

**Comment by byrxs5216** [comment]
Thanks for your response, I think your solution will work，and I had also tried some other way like this:
@ChildFragmentScoped
@DefineComponent(parent = FragmentComponent.class)
public interface ChildFragmentComponent {
}

@DefineComponent.Builder
public interface ChildFragmentComponentBuilder {
ChildFragmentComponentBuilder fragment(@BindsInstance Fragment fragment);
ChildFragmentComponent build();
}

@Scope
@Retention(CLASS)
public @interface ChildFragmentScoped {
}

other source code may be not suitable presented here.
but I think my soluation is so complicated,I will choose yours.



At 2020-12-30 09:56:19, "Eric Chang" <notifications@github.com> wrote:

This has come up a few times before so I think I should add something to the Hilt docs. But this is a known limitation. Unfortunately, there's no good way I know of to really support this. The depth of your parent fragments is really unknown until runtime so there isn't a good way to represent this statically. I think it can also probably get confusing with which fragment a binding is scoped to.

You can, however, support this yourself for individual bindings at runtime. For example, have a provider method that under some condition just delegates to a parent fragment via an EntryPoint. For example:

@Provides
static Foo provideFoo(Fragment fragment) {
  if (fragment.getParentFragment() == null) {
    return new Foo();
  } else {
    return EntryPointAccessors.fromFragment(fragment.getParentFragment(), FooEntryPoint.class).getFoo();
  }
}


Another reason we don't directly support this is you likely don't want every binding to have this behavior, and many times you might want to hard code a certain fragment that is the owner (e.g. instead of the base case being getParentFragment() == null, make it be like fragment instanceof FooFragment).

Anyway, hope that helps. I'll try to write up something for the docs on this when I get a chance too.
