### ISSUE TITLE
Adding `enableTransformForLocalTests` in Kotlin Gradle DSL breaks the build script 

### ISSUE THREAD

**Issue by childofthehorn** [google/dagger#2314]
Citing either implementation below:

`hilt{
    enableTransformForLocalTests
}`
or 
`hilt.enableTransformForLocalTests = true`

Adding this parameter to Kotlin Gradle DSL build scripts breaks the build scripts. Parameter works fine in Groovy Gradle scripts. 

Build tools and versions tested with:
Gradle : 6.7.1 and 6.8.1
Hilt : 2.28-alpha through to 2.31.1-alpha (all versions)
Android Build Tools : 4.1.1, 4.1.2, 4.2.0-beta03, 7.0.0-alpha03, 7.0.0-alpha04
Roboelectric : 4.4 and 4.5
JUnit : 4.13.1

All Injected code is working fine, this is only an issue for Hilt `@AndroidEntryPoint` injected Roboto tests.

Issue is occurring on even the most simple generated apps through Android Studio with no other outside dependencies or defined build versions, even without a `/buildSrc` folder.

[Stacktrace on Control-C](https://controlc.com/7e59b2f3)

**Comment by danysantiago** [comment]
If you are using AGP 4.2+ and Hilt 2.31.x then `enableTransformForLocalTests` is not needed since the plugin will use AGP's transform pipeline that applies to local unit test. Can you try that combination? Flag OFF and AGP 4.2.0 beta along with Hilt  2.31.2?

Otherwise this is an issue likely occurring in the custom task configuration we have when using AGP 4.1 or earlier, I'll try to investigate further.

**Comment by childofthehorn** [comment]
`hilt.enableTransformForLocalTests = false` worked fine and did not cause any build errors. 

Ironically enough, it appears that simply moving to Hilt `2.31.2-alpha` fixed this issue in combination (as tested just now) AGP `7.0.0-alpha04`. Will report back in a moment with whether this is also now fine with AGP `4.2.0-beta03`.

**Comment by childofthehorn** [comment]
AGP `4.2.0-beta03` is also working fine with Hilt `2.31.2-alpha`. 🙌

**Comment by danysantiago** [comment]
Closing this as AGP 4.2.0 is now stable.
