### ISSUE TITLE
Module private provides/binds

### ISSUE THREAD

**Issue by BugsBunnyBR** [google/dagger#2329]
Would it be possible to have something that says: 
This provide/bind annotated method provides something that should be available just to other module provides/binds in this module?

For instance, you may have a NetworkModule to provide OkHttp, but it requires some interceptors. The interceptors could be "private" to this module.

This would be useful to avoid full dagger graph validation and with the transitive dependencies problem that we have today.

Maybe a new annotation to support this?

**Comment by bcorso** [comment]
Hi @BugsBunnyBR,

> Would it be possible to have something that says:
> This provide/bind annotated method provides something that should be available just to other module provides/binds in this module?

Can you accomplish what you want with private qualifiers? For example:

```java
@Module
abstract class NetworkModule {
  @Qualifier
  private @interface MyPrivateQualifier {}

  // This binding is only available in this module because the qualifier is private
  @Provides
  @MyPrivateQualifier
  static Interceptor provideInterceptor() {...}

  @Provides
  static OkHttp provideOkHttp(@MyPrivateQualifier Interceptor interceptor) {...}
}
```

> This would be useful to avoid full dagger graph validation and with the transitive dependencies problem that we have today.

Sorry, I don't understand which problem you're referring to. Can you elaborate or give an example?

**Comment by BugsBunnyBR** [comment]
hey @bcorso , yeah that does help with the leaking dependencies from the module from the point of view of the developer.
But not from the dagger point of view. That elements are still in the graph, ideally they should be be kept in a separate graph so dagger would not validate it outside this module.

The transitive dependency issue that I talked about is this https://github.com/google/dagger/issues/970

Suppose I include OkHttp logging interceptor dependency to my "network" gradle module and in "network" dagger module, all gradle modules that depend on my gradle "network" module to use the dagger module will need to depend on OkHttp logging interceptor as well because of dagger validating the whole graph. 
This means the gradle "network" module will have to use api or all other modules will declare the dependence on OkHttp logging interceptor as well.

The solution you propose does not help with this problem.

**Comment by bcorso** [comment]
Ah, sorry now I see what you meant.

For Hilt, starting with version [2.31](https://github.com/google/dagger/releases/tag/dagger-2.31) we've introduced a flag, [`enableExperimentalClasspathAggregation`](https://dagger.dev/hilt/gradle-setup#classpath-aggregation), that should fix this issue (with the caveats described in the [doc](https://dagger.dev/hilt/gradle-setup#classpath-aggregation)). 

For Dagger, unfortunately the flag mentioned above won't work because it currently relies on the Hilt android plugin. However, the idea is that eventually we can work with the Gradle team to come up with something that is more general (and hopefully more efficient) and that works for both Dagger and Hilt. 

That said, I think we'll wait for the more general solution rather than trying to build this into Dagger's API.

(FWIW, you can also try using [component dependencies](https://dagger.dev/api/latest/dagger/Component.html#dependencies--), along with the flag described in #970, to try to break these api dependencies)

**Comment by BugsBunnyBR** [comment]
Hey, thanks for the reply.

My problem with these flags is that is it a global thing that remove some of the assurances that dagger gives us.
My idea of a module private provision allows us to hide dependencies case by case giving more granularity control.
Sometimes we do want that transitive dependency and use `api` in the providing gradle module.

**Comment by bcorso** [comment]
> My problem with these flags is that is it a global thing that remove some of the assurances that dagger gives us.

Understood. Perhaps that flag would be better supported as an annotation on the component?

> My idea of a module private provision allows us to hide dependencies case by case giving more granularity control.

Please let me know if I'm misunderstanding your proposal, but I think you're essentially asking to be able to validate these "private" provision bindings when compiling the module, and then skipping validation of those bindings during validation of the component.

In general, we wouldn't have enough information to validate the dependencies of these "private" bindings. For example, let's say the "network" library contained a "private" `LoggingInterceptor` that depends on a `Logger`. In this case, the `Logger` is likely bound at the application level, and Dagger has no way to verify in the "network" library if it's valid. An even more likely example is if the `LoggingInterceptor` depended on another provision binding within the "network" library, Dagger can't really validate that dependency without knowing that those modules are connected (which is usually the job of `@Component.modules`).

Again, unless I'm misunderstanding you proposal, it sounds like you may just want to use component dependencies, but you want to be able to control the flag in #970 on a per-component basis. Is that right?

**Comment by BugsBunnyBR** [comment]
I am not that well versed in the inner works of dagger, so I may be asking for stuff that is too hard to get or just not the right path, but let me try to explain.

> Understood. Perhaps that flag would be better supported as an annotation on the component?

I don't know. I think that the flag is a different thing.

> Please let me know if I'm misunderstanding your proposal, but I think you're essentially asking to be able to validate these "private" provision bindings when compiling the module, and then skipping validation of those bindings during validation of the component.

I think we still need to validate in the module and in the component.

> In general, we wouldn't have enough information to validate the dependencies of these "private" bindings. For example, let's say the "network" library contained a "private" LoggingInterceptor that depends on a Logger. In this case, the Logger is likely bound in the Gradle application module, and Dagger has no way to verify in the "network" library if it's valid. An even more likely example is if the LoggingInterceptor depended on another provision binding within the "network" library, Dagger can't really validate that dependency without knowing that those modules are connected (which is usually the job of @Component.modules).

I am not asking to remove the validation for "private provides/binds", I am asking to change the validation strategy.

For "public" provisions we could validate up in the graph until we find a "private" provision and then look for its dependencies.

When validating a "private" provision dagger still would need to validate it against the "siblings" provisions (to avoid repeated provisions) I understand that this happens at module level and would not trigger the transitive dependencies problem.

The dependencies of a "private" provision (like the logger that comes from another module), just like the public provisions needs to be validated at component level, but not the "private" provision itself.

Suppose that we have 4 dependencies in 3 dagger modules and that "_" means private.
C -> B -> _B1 -> A

When C requires B dagger needs to validate that A is available to B

C = retrofit
B = OkHttp
_B1 = LoggingInterceptor
A = Logger


Sorry I may have missed something.

**Comment by Chang-Eric** [comment]
Unfortunately, I don't think this can really be done easily. As a concept, Dagger doesn't really see modules right now, just bindings. The modules are just a way to pass those bindings to the component and organize them. For resolving bindings and such though, everything is intended to be part of the kind of "global" scope. For similar reasons, I don't think doing something like this will actually fix the validation problem as we're still going to generate code in the component referencing those private types. The factories we generate at the module level don't actually hook any bindings up, mostly because they can't without some global knowledge (e.g. resolving duplicate bindings, `@Inject` overridden by `@Provides`, multibindings), so even if those bindings are private to the module it still gets all hooked up at the component level which is what causes the dependency problem.

For binding management, we recommend private qualifiers as mentioned above. For the dependency issue, we're looking at fixes at the Gradle level (e.g. things along the same line as the flag mentioned in https://github.com/google/dagger/issues/1991)
