### ISSUE TITLE
Any way to inject some common object in subclass?

### ISSUE THREAD

**Issue by hahafather007** [google/dagger#2407]
I have a BaseViewModel just like this
```
abstract class BaseViewModel : IBaseViewModel() {
    @Inject
    lateinit var signInRepo: SignInRepo

    override suspend fun resign():Boolean{
        return signInRepo.resign()
    }
}

@Singleton
class SignInRepo @Inject constructor() : BaseRepo() {
    suspend fun resign(): Boolean {
       // Do some thing here
    }
}

class MainViewModel @ViewModelInject constructor() : BaseViewModel() {
    suspend fun doWhenTokenExpired() {
        resign()
    }
}
```
But when I use `resign()`,  crash happened like this:
```
W/System.err: kotlin.UninitializedPropertyAccessException: lateinit property signInRepo has not been initialized
```

So is there any way to inject some common object in base class?

**Comment by bcorso** [comment]
Hi @hahafather007,

`@ViewModelInject` is now [deprecated](https://developer.android.com/reference/androidx/hilt/lifecycle/ViewModelInject), partially because of this issue you're running into. 

If possible, can you switch to using the new [`@HiltViewModel`](https://dagger.dev/hilt/view-model), which should correctly inject your base class members.

**Comment by danysantiago** [comment]
See https://dagger.dev/hilt/view-model for more info.

**Comment by magamal** [comment]
I had the same issue 
Any help please
