### ISSUE TITLE
Service Context in Hilt

### ISSUE THREAD

**Issue by tompee26** [google/dagger#2442]
Why is there no `ServiceContext` qualifier? How can one obtain the service context in a module installed in `ServiceComponent`?

**Comment by danysantiago** [comment]
There is indeed no `@ServiceContext` in Hilt, we need to add one. However, [the `Service` itself is an available binding in the ServiceComponent](https://dagger.dev/hilt/components#component-bindings), so you can write a module that provides it:
```
@Module
@InstallIn(ServiceComponent::class)
abstract class ServiceContextModule {
  @Binds
  @MyServiceContextQualifier // <- Create a qualifier for it
  abstract fun provideContext(service: Service): Context
}
```
or you can just inject `Service` where as you would use the context since they are the same (Service is a Context).

**Comment by Chang-Eric** [comment]
What @danysantiago said is correct, but I would say I'm not sure we really should add an `@ServiceContext`. It isn't clear to me that the qualifier adds value over injecting `Service` directly. The same could be said for `@ActivityContext` which I am not sure yet if I regret adding. Most code I see injects `Activity` directly.

**Comment by neronguyenvn** [comment]
I inject Service directly to a class but in that Service I want to have that class dependency, which simply mean I create that class in the Service and pass the Service instance, but it still create a dependency cycle, how to fix that ?
