### ISSUE TITLE
Migrating dagger to hilt: unable to process this Hilt generated ApplicationC class

### ISSUE THREAD

**Issue by sanginovs** [google/dagger#2448]
Hi Dagger developers, 
First of all, thanks for a great library. Currently, I am trying to migrate our codebase from the Dagger-android to Hilt. I am currently running into this kapt error:

```
error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
  public abstract static class ApplicationC implements SampleComponent,
 
```
  ApplicationC is a Hilt generated component located in `MyApplicationName_HiltComponents.java`.
  Any idea why I am running into this error? There's not much logs available for me to debug this. 
  
  I found this [ticket](https://youtrack.jetbrains.com/issue/KT-33223) online. not sure if they are related.

**Comment by bcorso** [comment]
Hi @sanginovs,

Dagger delays processing until it can validate all types referenced by an annotated element (e.g. a component may reference a type that is invalid until it is generated by another processor). In this case, the error means that Dagger kept waiting but the type never became valid so Dagger never began processing.  

Unfortunately, the error doesn't really tell you much by itself, e.g. it could mean that the Hilt processor had an error and was unable to generate a type that Dagger was waiting on. In this case, there's usually another error from Hilt somewhere in the logs so I would double check very carefully for that (and post the entire log here if you can).

Otherwise, we'll probably need to have more information to help.  Can you describe what you've migrated so far (e.g. did you just add the @HiltAndroidApp annotation to the application or have you started to migrate activities/fragments as well)?

**Comment by sanginovs** [comment]
i was able to figure out the cause of this issue. I tried swap the dagger modules in/out from Hilt component and found out that one of the dagger modules was causing this kapt error without any helpful logs. not sure why though.
