### ISSUE TITLE
Flag validateTransitiveComponentDependencies doesn't seem to work

### ISSUE THREAD

**Issue by EliottLujan** [google/dagger#2465]
This issue is the continuation of issue [#2098](https://github.com/google/dagger/issues/2098)

@jbluntz created a repo to reproduce the probleme here : https://github.com/jbluntz/dagger-module-test

The repo contains the following :

dagger 2.30.1
AGP 6.7

Module "component" setting up a dagger component

```
@Component(modules = [ModuleA::class])
interface Component
```
"module-a" 

```
@Module(includes = [ModuleB::class])
interface ModuleA {
    @Binds
    fun bindA(a: A): IA
}

interface IA

class A @Inject constructor(b: IB): IA
```

"module-b" 

```
@Module
interface ModuleB {

    @Binds
    fun bindB(b: B): IB
}

interface IB

class B @Inject constructor(): IB
```

Even with the flag

```
kapt {
    javacOptions {
        option("-Adagger.validateTransitiveComponentDependencies=DISABLED")
    }
}
```

we sill get the following error 

```
error: cannot access ModuleB
  class file for com.jbluntz.dagger.moduleb.ModuleB not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.jbluntz.dagger.moduleb.ModuleB not found
```

Do i missunderstand what the flag is for or how it works ? According to the [release note ](https://newreleases.io/project/github/google/dagger/release/dagger-2.29.1) and issue [#970](https://github.com/google/dagger/issues/970) it would seem disabling validateTransitiveComponentDependencies should make the "class not found" disappear, right ?

**Comment by bcorso** [comment]
@EliottLujan, `validateTransitiveComponentDependencies` is specifically for component dependencies, i.e. the usage of `@Component.dependencies`. It has no affect if you are not using component dependencies.

We cannot disable validation in your case because Dagger needs access to all of the transitive `@Module` classes to process and generate the component implementation.

**Comment by bcorso** [comment]
@EliottLujan, we can't have a flag for module dependencies. When processing an `@Component` we need to be able to access all of its transitive modules to process and generate the component. The validation that is skipped by the flag when using `@Component.dependencies` isn't technically needed to process and generate the component, so that's why it can be skipped.

**Comment by EliottLujan** [comment]
Alright I understand ! Thanks a lot for your answer 😄

**Comment by rluick15** [comment]
@bcorso Hey just running into this issue myself after the latest dagger update. I think I understand why this flag is not working here. We are using `@ContributesAndroidInjector` to generate our subcomponents instead of using `@Component.dependencies`. Is there any way around this with this setup or are we in the same boat?

**Comment by bcorso** [comment]
Yeah, `@ContributesAndroidInjector` uses [subcomponents](https://dagger.dev/dev-guide/subcomponents) rather than component dependencies, and the flag is only meant to work with component dependencies. 

The difference is that component dependencies are kind of a black box to the component -- i.e. they don't actually have to be components themselves, we just gets handed an instance of it at runtime. Thus, the validation for component dependencies is really best effort anyway, so skipping the validation is not so critical.

However, subcomponents are not black boxes to the component. In particular, Dagger is responsible for generating the implementation of each subcomponent -- thus we have to be able to fully validate subcomponents. I also don't think it would really be feasible to use component dependencies with `@ContributesAndroidInjector`.
