### ISSUE TITLE
HILT_XXXFragment generated by HILT will override the getContext method and return a FragmentContextRapper object. This will cause view.getContext return FragmentContextRapper instead of Context. Is there a good solution for this

### ISSUE THREAD

**Issue by byrxs5216** [google/dagger#2470]

**Comment by bcorso** [comment]
> This will cause view.getContext return FragmentContextRapper instead of Context. Is there a good solution for this

What's the actual issue you are running into? Can you describe your use case and show any errors you are getting?

**Comment by Chang-Eric** [comment]
This is something expected since we need the wrapper to get the Dagger components to the view. If you are calling `view.getContext()` and expecting the context to be the activity context, you should unwrap the context instead until you get the activity context by calling `getBaseContext()`. This is something that you should do anyway because Android may wrap your activity context anyway for things like themes and stuff.

**Comment by byrxs5216** [comment]
thanks
