### ISSUE TITLE
@HiltiViewModel and missed binding

### ISSUE THREAD

**Issue by NataliMakarenko** [google/dagger#2492]
Annotated view model with @HiltViewModel caused binding issue Missed provide/bind for a chain
view model (useCase (repositoryContract))

To make it work I have explicitly use repository implementation instead of repository interface.

But it works with depracated @ViewModelInject.

 hilt_version = "2.33-beta"
 hilt_androix_version = "1.0.0-alpha03" 
 
 Reproduce also with 2.31 and 1.0.0-alpha01

**Comment by bcorso** [comment]
Hi @NataliMakarenko, can you post your code and the stack trace for the error message?

**Comment by NataliMakarenko** [comment]
@HiltAndroidApp
class MyApp : Application()

@AndroidEntryPoint
class MainActivity : AppCompatActivity() {
    private val mainVewModel: MainViewModel by viewModels()
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
    }
}

@HiltViewModel
class MainViewModel @Inject constructor (useCase: MainUseCase): ViewModel()

class MainUseCase @Inject constructor (useCase: MainRepositoryContract)

interface MainRepositoryContract

class MainRepositoryImp @Inject constructor(): MainRepositoryContract

@InstallIn(ActivityComponent::class)
@Module
abstract class MainModule {
    @ActivityScoped
    @Binds
    abstract fun bindMainRepository(impl: MainRepositoryImp): MainRepositoryContract
}

**Comment by NataliMakarenko** [comment]
/AndroidStudioProjects/TestHilt/app/build/generated/source/kapt/debug/com/begemothsoft/testhilt/MyApp_HiltComponents.java:122: error: [Dagger/MissingBinding] com.begemothsoft.testhilt.MainRepositoryContract cannot be provided without an @Provides-annotated method.
  public abstract static class SingletonC implements MyApp_GeneratedInjector,
                         ^
      com.begemothsoft.testhilt.MainRepositoryContract is injected at
          com.begemothsoft.testhilt.MainUseCase(useCase)
      com.begemothsoft.testhilt.MainUseCase is injected at
          com.begemothsoft.testhilt.MainViewModel(useCase)
      com.begemothsoft.testhilt.MainViewModel is injected at
          com.begemothsoft.testhilt.MainViewModel_HiltModules.BindsModule.binds(vm)
      @dagger.hilt.android.internal.lifecycle.HiltViewModelMap java.util.Map<java.lang.String,javax.inject.Provider<androidx.lifecycle.ViewModel>> is requested at
          dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.ViewModelFactoriesEntryPoint.getHiltViewModelMap() [com.begemothsoft.testhilt.MyApp_HiltComponents.SingletonC → com.begemothsoft.testhilt.MyApp_HiltComponents.ActivityRetainedC → com.begemothsoft.testhilt.MyApp_HiltComponents.ViewModelC]

**Comment by bcorso** [comment]
Thanks for the details!

The issue is that the `MainRepositoryContract` is installed in the `ActivityComponent` and the view model does not have access to bindings in the `ActivityComponent`.

The docs show Hilt's [component hierarchy](https://dagger.dev/hilt/components#component-hierarchy).
The view model only has access to bindings in the `SingletonComponent`, `ActivityRetainedComponent`, and `ViewModelComponent`. We don't allow the view model to access `ActivityComponent` bindings because that would be a memory leak since view models are meant to outlive a given activity instance.

The fix would be to install `MainRepositoryContract` in `SingletonComponent`, `ActivityRetainedComponent`, or `ViewModelComponent`.

**Comment by NataliMakarenko** [comment]
Thanks!
