### ISSUE TITLE
Hilt @AndroidEntryPoint not working for package named "public"

### ISSUE THREAD

**Issue by Rogdan** [google/dagger#2500]
In my android application, i have package named "public". E.g. **com.example.ui.dashboard.feed.public**.
In this package, i have fragment SomeFragment, annotated with **AndroidEntryPoint**.
Hilt not working for this specific [public] package, i have compilation error with next stack trace:
`* What went wrong:
Execution failed for task ':app:transformClassesWithAndroidEntryPointTransformForDebug'.
> javassist.NotFoundException: com.nagi.ui.dashboard.feed.public.Hilt_SomeFragment

Only renaming of package from [public] to any another (e.g. **com.example.ui.dashboard.feed.public** -> renamed to **com.example.ui.dashboard.feed.news**) helped.

**What am i whant**. I whant you to add more read-able error for this "special case". Or add this lines in documentation:
"Hilt not working for packages, named **public**"

Hilt version: 2.33-beta

**Comment by dmapr** [comment]
That's an invalid package name, you should be getting a compiler error about it even without Hilt. Can't use reserved words in package names.

**Comment by bcorso** [comment]
IIUC, the issue is that [`public` is allowed](https://kotlinlang.org/docs/keyword-reference.html#modifier-keywords) as an identifier in package names for Kotlin. However, when kapt tries to create a java stub for this class it can't, and it looks like it just ignores it rather than throwing an exception. Thus, the Hilt never even processes the source, which is why the `Hilt_SomeFragment` is missing in your case.

Can you file a bug against kapt instead to see if they can throw an error message whenever they can't generate a java stub? While we could add something to our Hilt plugin to try to detect this, it seems like the wrong place to try to handle this issue.

**Comment by danysantiago** [comment]
Kotlin has an issue to enable a 'strict mode' to error out for these type of cases: https://youtrack.jetbrains.com/issue/KT-25518, but overall not much Hilt can do about this.
