### ISSUE TITLE
[ Hilt ] Classpath Aggregation build performance impact

### ISSUE THREAD

**Issue by sanginovs** [google/dagger#2510]
Hi there, 

I was reading this [thread](https://github.com/google/dagger/issues/1991) regarding build performance of Hilt in multi-module apps. Currently, Hilt comes with [classpath aggregation](https://dagger.dev/hilt/gradle-setup#classpath-aggregation) to avoid errors in multi-module apps however it impacts build performance due to an increase in compilation classpath.
Any timeline on when the Hilt team is going to improve the build performance on **[classpath aggregation](https://dagger.dev/hilt/gradle-setup#classpath-aggregation)** feature?

Thanks a lot.

**Comment by danysantiago** [comment]
No precise timeline (sorry!) but we have some ideas for this along with other related build time improvements and we are working towards implementing them. In essence they are:
* Share test components as much as possible, this reduces the amount of generated code that needs to be compiled.
* Remove the aggregating processor, this improves incremental compilation and reduces the amount of times components have to be generated.
* Perform the classpath aggregation in a separate Gradle task that is less often outdated and does not affect the default compile tasks due to its inputs only being relevant transformed artifacts.
