### ISSUE TITLE
Can not use @Qualifier with @EntryPoint?

### ISSUE THREAD

**Issue by andrewhunter0** [google/dagger#2516]
If i use `@Qualifier` in `ModuleBEntryPoint.kt` an compile error happens:
```
e: D:\Git\github\DataBindingError\app\build\generated\source\kapt\debug\com\andrew\architecture\AppApplication_HiltComponents.java:154: ����: [Dagger/MissingBinding] com.andrew.architecture.services.service.AnalyticsService3 cannot be provided without an @Provides-annotated method.
    public abstract static class ApplicationC implements AppApplication_GeneratedInjector,
    ^
    A binding with matching key exists in component: com.andrew.architecture.AppApplication_HiltComponents.ApplicationC
    com.andrew.architecture.services.service.AnalyticsService3 is requested at
    com.bruce.moduleb.hilt.ModuleBEntryPoint.getAnalyticsService3()
```

See my demo（https://github.com/andrewhunter0/DataBindingError） in class `ModuleBEntryPoint`, if add 
```
@AnalyticsService3One
var analyticsService3: AnalyticsService3?
```
will cause error, if comment it, every thing is ok.   
Dose `@Qualifier` can only use with `@Inject`?

How can i do when one interface has two instance class?

**Comment by danysantiago** [comment]
You have to specify the [use-site](ModuleBEntryPoint) of the annotation so that Dagger can properly pick it up. 
```
@get:AnalyticsService3One
var analyticsService3: AnalyticsService3?
```

This is a Kotlin interop inconvenience. Because your `@AnalyticsService3One` has no [`@Target`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.annotation/-target/) when the annotation is placed on a property it ends up on a synthehtic method which won't be read by Dagger (https://github.com/google/dagger/issues/2104).

**Comment by andrewhunter0** [comment]
Ok, tha't it. thanks.
