### ISSUE TITLE
Are qualifiers supported in modules?

### ISSUE THREAD

**Issue by adi1133** [google/dagger#253]
Dagger 2 causes some undefined behaviour in my app when using qualifiers in modules.
Are they supported ? 
If needed I can post a small project that reproduces the issue I am having.

    @AppScope
    @Provides
    Retrofit provideRetrofit(Moshi moshi, OkHttpClient okHttpClient, @ServerPath String serverUrl) {
    ...
    }

    @Qualifier
    @Retention(RetentionPolicy.SOURCE)
    public @interface ServerPath { }

**Comment by cgruber** [comment]
Qualifiers should work fine in Dagger 2 to qualify provisions or
dependencies listed in provides methods' parameter lists.  The above should
result in a specifically qualified `@ServerPath String` to be supplied to
the third parameter of the provideRetrofit() method.

What behavior are you seeing?

**Comment by adi1133** [comment]
Here is a repo that reproduces the issue.
https://github.com/adi1133/Dagger-2-Qualifier-Unit-Test-Issue
Try to run the unit test with **gradlew test**

Dagger 2 fails to generate the necessary code to implement **TestComponent**

TestComponent resides inside the unit test source set and relies on a module from the **main** source set
The module contains Qualifiers.

Dagger 2 is added as a dependency using apt 1.8

    compile 'com.google.dagger:dagger:2.0.1'
    apt 'com.google.dagger:dagger-compiler:2.0.1'
    testApt 'com.google.dagger:dagger-compiler:2.0.1'

**Comment by ronshapiro** [comment]
A couple things happening here:
  - Your qualifier annotations are not public, so they can't even be used to build `SomeComponent` since they cross a package boundary. Either make them public or move them into the same package.
  - You marked the qualifiers `@Retention(RetentionPolicy.SOURCE)` which means they get stripped after they are compiled. Since the test scope uses the main scope as a dependency, by the time the main code is compiled and reaches the test code for compilation, the qualifiers don't exist. You can fix this by marking `@Retention(RetentionPolicy.CLASS)` (read more on [RetentionPolicys here](http://docs.oracle.com/javase/7/docs/api/java/lang/annotation/RetentionPolicy.html)). Note that you can also mark it `RetentionPolicy.RUNTIME`, but unless you plan on using these annotations using reflection you probably don't need it.
  - Finally, in order to get the code to compile, `TestComponent` must extend the `SomeComponent` interface. Otherwise, the types in `SomeComponent component = DaggerTestComponent.create();` don't match.

**Comment by adi1133** [comment]
Thank you for your help !
I didn't know that the compiler runs multiple passes when I compile android unit tests.
**@Retention(RetentionPolicy.CLASS)** on my qualifiers fixed my problem. Now my projects run as expected. This issue may be closed.
