### ISSUE TITLE
Dagger version 2.14.1 support for Android 11

### ISSUE THREAD

**Issue by Flavind** [google/dagger#2566]
Hello!
My Application uses Dagger version 2.14.1 and supports Android version 5.1.
I want to update the application so that it can be compatible with Android 5.1 and Android 11.
I am just making the app compatible as it is with Android 11 without changing any functionality/features.
Will this Dagger version support Android 11 and 5.1 or do I need to update to version 2.34?

**Comment by danysantiago** [comment]
If you are using just Dagger (not dagger-android) then you'll likely be fine without updating Dagger since as far as I know, core Dagger does not have requirements for a minimum Android version. But as with many things, you'll have to try it to make sure targeting the newest Android version works fine. Feel free to file a bug if you encounter an issue with Dagger and updating to the latest version doesn't work for you.

**Comment by Flavind** [comment]
Thanks for the reply.
I am using dagger-android.
In that case will it (version 2.14.1) support Android 11?
