### ISSUE TITLE
Forbid method names for built-in types

### ISSUE THREAD

**Issue by vRallev** [google/dagger#2576]
Method names like 
```kotlin
@BindsInstance public fun int(int: Int): Builder
```
are problematic and cause surprising errors. As @bcorso highlighted [here](https://github.com/google/dagger/issues/2574#issuecomment-825940532) Kapt seems to skip generating stubs for these method names. It would be great if Dagger could detect such scenarios.

**Comment by danysantiago** [comment]
There is a feature request to prevent users from using Java keywords / identifiers when using KAPT but it seems it never got enough traction to be done. https://youtrack.jetbrains.com/issue/KT-25518

The current KAPT 'strictMode' does not error out when KAPT skips generating stubs due to usage of Java keywords.

Detecting this seems decently expensive, it means we would need to validate all elements with the information of the Metadata, looking for missing ones. However, this seem like an issue KAPT could prevent more easily.

**Comment by vRallev** [comment]
Sounds fair, feel free to close this ticket if you think there's no work needed on your side.
