### ISSUE TITLE
Compose Desktop Support

### ISSUE THREAD

**Issue by theapache64** [google/dagger#2599]
Any plans to support Compose Desktop? (something like Hilt for Desktop) :smile:

**Comment by Chang-Eric** [comment]
It looks like for that we'd have to support Kotlin multiplatform, which means finishing our support for KSP, changing Dagger to generate Kotlin, and then taking a look at whatever integration would be needed for the actual Compose Desktop aspect.

This feels far enough away that I'm going to close this bug because there really are no plans for this right now. Sorry!

**Comment by theapache64** [comment]
Understood
