### ISSUE TITLE
Please evaluate a feature proposal for building inversed reference.

### ISSUE THREAD

**Issue by jinweihan2020** [google/dagger#2605]
Hi team, 

My team hopes to have a chance to build the `inversed reference` relationship between an instance and its dependencies. For example, Class A is a field of Class B, A was injected by the constructor of B, so we can naturally find A by B, but we also hope to know which Object is holding A (maybe B or another class, if it is B, then which B?). It is helpful for us to maintain a running context along with a reference chain, which helps in perf tracking. 

I wrote a demo like below, which gives us a callback in `Intercept.bind()`, which allows us to utilize Foo and Bar/Baz instance at the same time, to do something like building `inversed reference`.

Hope to learn your attitude for this kind of feature, and if this idea is acceptable for you, then I could work on a PR to implement it since already have a local demo. Appreciate your time in advance, looking for your feedback.

Sincerely,
J

Demo turns:
![image](https://user-images.githubusercontent.com/62824817/117732929-9015cc80-b1a5-11eb-8a1e-1647a57b1bcf.png)
to
![image](https://user-images.githubusercontent.com/62824817/117732259-6a3bf800-b1a4-11eb-942e-d58e43047940.png)

**Comment by Chang-Eric** [comment]
Sorry, but I think we're unlikely to want to do this. There are some open questions here like how are you supposed to register your interceptors, how are we going to give you the dependencies (is it just an array of objects that you cast and assume a certain order of?), what is the contract for `Provider`/`Lazy`/`Optional` dependencies, etc.

I think a big question will also be how useful such an interceptor will be if we can't give you some sort of identifier for each type (to know which binding it is from), and if we have to give you such an identifier, how could we do so in a way that isn't expensive or extremely cumbersome (e.g. string representations of the keys would get incredibly long).

There's also going to be a question of usefulness, given that most interceptors probably don't want to process every single binding (since that would be a lot), but even the act of filtering to the bindings you care about may cause significant performance issues given the number of bindings that are typically seen in apps.

Anyway, these are my initial thoughts on why this is unlikely to be something we want to work on right now. Sorry about that =\

**Comment by jinweihan2020** [comment]
Thanks for the reply anyway @Chang-Eric , let me explain for the `Intercept.bind()` since I didn't provide any other information besides a calling example.

In my mind, a simple demo could be like this, provide a base class that allows the app developer to extend, and then it could be auto-register once the object constructed at runtime. We could only pass the dependencies as an array of Objects without strong order. Provider/Lazy/Optional could be treated as normal Objects.
```
  public abstract class Interceptor {
    Interceptor() {
      Intercept.register(this);
    }

    /**
     * First parameter is the root instance, and dependencies are all its dependencies injected.
     * We could keep the same order in the constructor and inject site.
     * */
    public abstract void bind(Object root, Object... dependencies);
  }
```

We could build an inverse reference relationship since we could have a root object and some dependencies objects. We only need to check the type and building inversed reference when necessary, which could be checked by `instanceof`.

```
   class MyInterceptor extends Interceptor {

        MyInterceptor(){
            super();
        }

        @Override
        public void bind(Object root, Object... dependencies) {
            if (root instanceof ContextHolder) {
                for (Object dependency : dependencies) {
                    if (dependency instanceof ContextHolder) {
                        ((ContextHolder) dependency).setContext((ContextHolder) root);
                    }
                }
            }
        }
    }
```

There will be a runtime performance overhead, while we could consider reducing the cost by many methods, the performance overhead depends on the implementation of `Interceptor`. We could optimize the overhead by some technical skills, for example, build cache for `instanceof` reduce the type check cost from instance count level to type count level; use allowlist and denylist on the root object type. In default, if people leave the `Interceptor` blank, there will not be a significant cost. We could keep the `bind()` delegate be as lightweight as possible:
```

public class Intercept {
  private static Interceptor interceptor;

  public static void register(Interceptor callback) {
    assert interceptor == null;
    interceptor = callback;
  }

  public static void unregister() {
    interceptor = null;
  }

  public static void bind(Object root, Object... ref) {
    if (interceptor == null) return;

    if (ref.length > 0) {
        interceptor.bind(root, ref);
    }
  }
}
``` 

> Sorry, but I think we're unlikely to want to do this. There are some open questions here like how are you supposed to register your interceptors, how are we going to give you the dependencies (is it just an array of objects that you cast and assume a certain order of?), what is the contract for `Provider`/`Lazy`/`Optional` dependencies, etc.
> 
> I think a big question will also be how useful such an interceptor will be if we can't give you some sort of identifier for each type (to know which binding it is from), and if we have to give you such an identifier, how could we do so in a way that isn't expensive or extremely cumbersome (e.g. string representations of the keys would get incredibly long).
> 
> There's also going to be a question of usefulness, given that most interceptors probably don't want to process every single binding (since that would be a lot), but even the act of filtering to the bindings you care about may cause significant performance issues given the number of bindings that are typically seen in apps.
> 
> Anyway, these are my initial thoughts on why this is unlikely to be something we want to work on right now. Sorry about that =\

**Comment by Chang-Eric** [comment]
While this would work for your use case because for your inverse reference case you don't care about the order of arguments or identifying which dependency it came from, I think as a generic interceptor for Dagger there would have to be some identifier. Otherwise, if a class injects a `Foo` and a `@Qualified Foo` then it would be impossible to distinguish the two dependencies.

Also, in your example, how would you handle `Provider<ContextHolder>` injections? In those cases, the dependency and the object that holds the dependency is actually broken up between two intercept calls.

**Comment by jinweihan2020** [comment]
Yeah, in my case I don't care about orders and even don't need to distinguish a `Foo` and a `@Qualified Foo`. Just treat it as two objects, give them to callback and let the customer handle it in their way.

The `Provider<ContextHolder>` injections case, in my opinion, is not a typical node in the inversed reference chain, so the Provider itself is not a `ContextHolder` then it can be skipped.

![image](https://user-images.githubusercontent.com/62824817/118108224-98802a00-b394-11eb-8f9e-2512707c552c.png)

> While this would work for your use case because for your inverse reference case you don't care about the order of arguments or identifying which dependency it came from, I think as a generic interceptor for Dagger there would have to be some identifier. Otherwise, if a class injects a `Foo` and a `@Qualified Foo` then it would be impossible to distinguish the two dependencies.
> 
> Also, in your example, how would you handle `Provider<ContextHolder>` injections? In those cases, the dependency and the object that holds the dependency is actually broken up between two intercept calls.

**Comment by Chang-Eric** [comment]
Yea, unfortunately I think this is a case where your specific use case can make assumptions/optimizations that avoid these tough issues, but as a generally usable API I think these issues would be large blockers. Sorry, but I am going to close this since it doesn't seem feasible to me =\
