### ISSUE TITLE
Dagger 2.27 and lint compliance

### ISSUE THREAD

**Issue by anilgorthy** [google/dagger#2609]
In our multi-module project, we are using dagger 2.27

```
implementation 'com.google.dagger:dagger-android:2.27' 
```

 and just this morning I noticed a lint compliance error for this version and asked me to update to 2.35.1

```
 This version is . Details: Consider switching to recommended version 2.35.1.
```

I’m trying to find out what could have triggered this compliance error just now since all other versions remained the same.

**Comment by danysantiago** [comment]
Dagger only has a few Lint rules all of them which you can find [here](https://github.com/google/dagger/blob/master/java/dagger/lint/DaggerKotlinIssueDetector.kt) and they are only applicable to sources, not build files. That warning must be coming from somewhere else, possibly from Android Builds Tools, I would file a bug to the Android Studio Team but otherwise from our side, feel free to use the version that works best for you.

**Comment by arekolek** [comment]
@anilgorthy Can you post a link here if you report it somewhere else?

**Comment by patrickpilch** [comment]
We experienced the same problem, where builds started breaking left and right all over the place with no dependency version changes. Something in the android build process must be pulling in an external dependency with dynamic version constraints, which is very worrying.

**Comment by arekolek** [comment]
I was going to report an issue similar to this one https://issuetracker.google.com/issues/170240589, but I got an error saying "You do not have permission to create issues in this component.", so I'll just leave a comment here.

What changed is this metadata file https://dl.google.com/dl/android/sdk/metadata/sdk_registry.xml. It used to say:

```xml
  <library  groupId="com.google.dagger" artifactId="dagger-android" recommended-version="2.15" >
    <versions from="2.15" />
    <versions from="2.14.1" status="deprecated" description="Bug affecting SDK performance" url="https://github.com/google/dagger/releases/tag/2.15" />
    <versions from="2.14" status="deprecated" description="Bug affecting SDK performance" url="https://github.com/google/dagger/releases/tag/2.15" />
    <versions from="2.13" status="deprecated" description="Bug affecting app performance" url="https://github.com/google/dagger/releases/tag/2.15" />
    <versions from="2.12" status="deprecated" description="Bug affecting app performance" url="https://github.com/google/dagger/releases/tag/2.15" />
    <versions from="2.11" status="deprecated" description="Bug affecting SDK performance" url="https://github.com/google/dagger/releases/tag/2.15" />
    <versions from="2.11-rc2" status="deprecated" description="Bug affecting SDK performance" url="https://github.com/google/dagger/releases/tag/2.15" />
    <versions from="2.11-rc1" status="deprecated" description="Bug affecting SDK performance" url="https://github.com/google/dagger/releases/tag/2.15" />
    <versions from="2.10" status="deprecated" url="https://github.com/google/dagger/releases/tag/2.15" />
  </library>
```

And now it says:

```xml
  <library  groupId="com.google.dagger" artifactId="dagger-android" recommended-version="2.35.1" >
    <versions from="2.15" />
    <versions from="2.14.1" status="deprecated" description="Bug affecting SDK performance" url="https://github.com/google/dagger/releases/tag/2.15" />
    <versions from="2.14" status="deprecated" description="Bug affecting SDK performance" url="https://github.com/google/dagger/releases/tag/2.15" />
    <versions from="2.13" status="deprecated" description="Bug affecting app performance" url="https://github.com/google/dagger/releases/tag/2.15" />
    <versions from="2.12" status="deprecated" description="Bug affecting app performance" url="https://github.com/google/dagger/releases/tag/2.15" />
    <versions from="2.11" status="deprecated" description="Bug affecting SDK performance" url="https://github.com/google/dagger/releases/tag/2.15" />
    <versions from="2.11-rc2" status="deprecated" description="Bug affecting SDK performance" url="https://github.com/google/dagger/releases/tag/2.15" />
    <versions from="2.11-rc1" status="deprecated" description="Bug affecting SDK performance" url="https://github.com/google/dagger/releases/tag/2.15" />
    <versions from="2.10" status="deprecated" url="https://github.com/google/dagger/releases/tag/2.15" />
  </library>
```

Not sure if this was a deliberate change, because they didn't add any `status` or `description` for versions `2.15` - `2.35` when raising the `recommended-version`.

I can only guess it has something to do with Hilt graduating to stable in 2.35?
