### ISSUE TITLE
@HiltViewModel has incorrect scope

### ISSUE THREAD

**Issue by goldy1992** [google/dagger#2621]
**Hilt version**: 2.35.1
**implementation group: 'androidx.hilt', name: 'hilt-navigation-compose', version: '1.0.0-alpha01'**
**compose_version**: 1.0.0-beta05

Given a ViewModel:
```
@HiltViewModel
class MyViewModel {
   var someLiveData : LiveData<SomeObject>
}
```

and an activity where this ViewModel is injected:
```
@AndroidEntryPoint(AppCompatActivity::class)
class MyActivity : : Hilt_MainActivity() {

  @Inject
  lateinit var viewModel : MyViewModel

  override fun  onCreate(savedInstanceState: Bundle?) {
     super.onCreate(savedInstanceState)
     viewModel.observe(this) {
       // some code that needs to be done with a LifecycleOwner
     }
     setContent {
       MyComposeApp()
     }
  }
}
```

and some Composable functions

```
@ExperimentalPagerApi
@Composable
fun MyComposeApp() {
    val navController = rememberNavController()
    NavHost(
        navController =  navController,
        startDestination = "mainScreen") {
        composable("mainScreen") { mainScreen(navController,
            ) }

    }
}


@ExperimentalPagerApi
@Composable
fun mainScreen(navController: NavController,
               viewModel: MainScreenViewModel = hiltViewModel<MainScreenViewModel>()
) {
  /// some jetpack compose code
}
```

**Expected**: The `viewModel` in `MainActivity` and the composeable function `mainScreen` are the same object.
**Actual**: Hilt seems to construct s**eparate instances**!!!

**Comment by danysantiago** [comment]
This is intended, the `LocalViewModelStoreOwner` within a Navigation composable is the `NavBackStackEntry` so the function `hiltViewModel()` is scoping  the ViewModel to the nav graph which will be different from your activity.

If you wish to retrieve your activity ViewModel then you'll have to use the Activity's ViewModel store along with the `ViewModelProvider` APIs:
```
ViewModelProvider(activity).get(MainScreenViewModel::class.java)
```

Note that using Compose's `viewModel()` is not useful here since that API is for creating a ViewModel in the local scope, but since you are trying to use a parent one, then you need to use the non-compose ViewModel APIs.

**Comment by goldy1992** [comment]
Thanks you for the clarification @danysantiago
