### ISSUE TITLE
How to tell Proguard obfuscated class name with @Inject

### ISSUE THREAD

**Issue by dzungpv** [google/dagger#2660]
This is not really a bug.
For some reason I must use Proguard, not R8 for old project.
All class include @Inject for inject class not rename with the Proguard, I don't use any rule for it.
Now I want Proguard rename all that class, I find all over but still not solve it.

**Comment by Chang-Eric** [comment]
Hm, I don't think we've ever run into this issue before. As far as I know Proguard is fine with renaming `@Inject` classes, so I think there must be something with your configuration or some configuration you are picking up from a library (since libraries can package Proguard configs into their jars). I think you'll need to ask for help somewhere that can help with more direct Proguard knowledge though, like either the Proguard maintainers or somewhere like Stack Overflow.
