### ISSUE TITLE
using dagger in Android library, when application consume .aar at run time application throws 'Didn't find class "dagger.internal.Preconditions" on path: DexPathList'

### ISSUE THREAD

**Issue by inderpalaulakh** [google/dagger#2685]
is it mandatory for application to use ` implementation 'com.google.dagger:dagger:2.x'` when consuming Android library that uses Dagger?

As dagger is compile time, the expectations is the code is generated in .aar and so that we do not force application to include Dagger.

**Comment by bcorso** [comment]
The classes in `com.google.dagger:dagger` are mostly just annotations and interfaces, but you need them at runtime because they will be referenced from both your own classes and the Dagger generated classes at runtime.

The annotations in `com.google.dagger:dagger` (e.g. `@Component`, `@Module`, etc.) while not used at runtime by Dagger, are still `@Retention(RUNTIME)` and can be used by other libraries at runtime, like [`Dagger-Reflect`](https://github.com/JakeWharton/dagger-reflect).

The interfaces in `com.google.dagger:dagger` (e.g. `dagger.internal.Factory`, `dagger.internal.DoubleCheck`) are used by Dagger generated classes. As an example, for a class `Foo` with an `@Inject` constructor, Dagger will generated a `Foo_Factory` that extends the `dagger.internal.Factory` interface. The generated component will later use `Foo_Factory` to create `Foo` since `Foo`'s constructor may not be public:

```
// Generated in the same package as Foo
@Generated
public final class Foo_Factory implements Factory<Foo> {  // <-- References dagger.internal.Factory
  @Override public Foo get() { return new Foo(...); }
}
```

Finally, there are also interfaces in `com.google.dagger:dagger` that you may reference directly in your own sources, e.g. `dagger.Lazy` and `dagger.MembersInjector`.

**Comment by iaulakh** [comment]
Thanks @bcorso . I noticed that I do not need to include dagger in application if Android library uses only dagger component (no modules).

Once we start using modules, then we need to include Dagger in application as `dagger.internal.Factory` and `dagger.internal.Preconditions` are required by compiled code.

**Comment by inderpalaulakh** [comment]
Thanks @bcorso . I noticed that I do not need to include dagger in application if Android library uses only dagger component (no modules).

Once we start using modules, then we need to include Dagger in application as dagger.internal.Factory and dagger.internal.Preconditions are required by compiled code.
