### ISSUE TITLE
[Hilt] Unable to get activity context

### ISSUE THREAD

**Issue by longnguyencmg** [google/dagger#2698]
First of all, thank you for the great tool 👍  🥇 
Currently I'm using com.google.dagger:hilt-android:2.37, compiler is com.google.dagger:hilt-android-compiler:2.37.

I want to create a module for an activity.

Activity example code:

```
@AndroidEntryPoint
class DetailActivity: BaseActivity<ActivityDetailBinding, DetailViewModel>() {

    private val detailViewModel: DetailViewModel by viewModels()

    lateinit var repo: Repo

    override fun getLayoutId(): Int = R.layout.activity_detail

    override fun getViewModel(): DetailViewModel = detailViewModel

    override fun getBindingVariable(): Int = BR.viewModel

    override fun initView() {
        intent.getParcelableExtra<Repo>(REPOSITORY)?.let { repo = it }
        detailViewModel.updateRepoDetail(repo)
    }

    companion object {
        private const val REPOSITORY = "repo"

        fun callingIntent(context: Context, repo: Repo): Intent {
            val intent = Intent(context, DetailActivity::class.java)
            intent.putExtra(REPOSITORY, repo)
            return intent
        }
    }
}
```

ViewModel example code:

```
@HiltViewModel
class DetailViewModel @Inject constructor(
    private val router: DetailRouter
) : BaseViewModel() {
    fun updateRepoDetail(repo: Repo) {
        fullName = repo.fullName.orEmpty()
        language = repo.language.orEmpty()
        forks = repo.forksCount?.coerceAtLeast(0).toString()
        issues = repo.openIssuesCount?.coerceAtLeast(0).toString()
        stars = repo.stargazersCount?.coerceAtLeast(0).toString()
        ownerType = repo.owner.type
    }

    fun goBack() {
        router.goBack()
    }
}
```

Router interface and implementation example code: (it could any logic to update UI/routing from activity)
```
interface DetailRouter {
    fun goBack()
}

@ActivityScoped
class DetailRouterImpl @Inject constructor(@ActivityContext private val activity: Context) : DetailRouter {

    override fun goBack() {
        (activity as DetailActivity).onBackPressed()
    }
}
```

Detail Module example code:

```
@Module
@InstallIn(ViewModelComponent::class)
object DetailModule {

    @Provides
    @ViewModelScoped
    fun provideDetailRouter(context: Context): DetailRouter {
        return DetailRouterImpl(context)
    }
}
```

I can see that the `context` on `DetailModule` is application context, which is not something I expected. 
In this case, how can I inject a specify activity context into a class?

It worked fine on `com.google.dagger:hilt-android:2.28.3-alpha` with the code below:

```
@Module
@InstallIn(ActivityComponent::class)
object DetailModule {

    @Provides
    @ActivityScoped
    fun provideDetailRouter(@ActivityContext context: Context): DetailRouter {
        return DetailRouterImpl(context)
    }
}
```

**Comment by danysantiago** [comment]
It is not possible to inject the activity context (or the activity itself) into a `@HiltViewModel` since that would cause a leak because ViewModels outlive the activity in configuration changes. (See the red warnings at https://developer.android.com/topic/libraries/architecture/viewmodel)

If you take a look at [Hilt's component hierarchy](https://dagger.dev/hilt/components#component-hierarchy) you'll see the ViewModelComponent (and ViewModels in general) are based off the activity retained component, meaning dependencies defined in modules are installed in the `ActivityComponent` are not available in the `ViewModelComponent`.

One recommendation I can give is to inject your activity dependant binding into the activity (like your Router) and via some interaction with the ViewModel and Activity trigger the navigation.

**Comment by longnguyencmg** [comment]
Hi @danysantiago, thank you for your reply.
You're right. I don't want to inject activity in view model.

Because I did something similar in Dagger, for example, I have `ActivityModule` contains code below (this module is included in `ApplicationComponent`)
```
@ActivityScope
@ContributesAndroidInjector(modules = [DetailModule::class])
abstract fun detailActivity(): DetailActivity
```
Then I can inject `DetailActivity` in any class example router or interactor in `DetailModule`. This is for Dagger right.

As you can see in `DetailRouterImpl `, I tried to inject activity context there. And then in `DetailModule `, I passed context to router. 
```
@Module
@InstallIn(ViewModelComponent::class)
object DetailModule {

    @Provides
    @ViewModelScoped
    fun provideDetailRouter(context: Context): DetailRouter {
        return DetailRouterImpl(context)
    }
}
```
However, this context param is application context :(. 
I want to specify that context is from `DetailActivity`, how do I achieve that?

**Comment by danysantiago** [comment]
You can't inject the Activity context in any `@Module` installed in  the `ViewModelComponent`, because that would be a leak.

If you want the activity context specifically, you can inject one if the module is installed in the `ActivityComponent`:
```
@Module
@InstallIn(ActivityComponent::class)
object DetailModule {
  @Provides
  fun provideDetailRouter(@ActivityContext activity: Context): DetailRouter {
    return DetailRouterImpl(context)
  }
}
```
Note that you can also write a provider that injects `Activity`:
```
@Provides
fun provideDetailRouter(activity: Activity): DetailRouter {
  return DetailRouterImpl(activity)
}
```
But you won't be able to inject your `DetailRouter` in your ViewModel, because that would cause a leak. 

As for your navigation, I think you need to separate your UI driving logic from your business logic in the VM, and one way to do this is to inject your router into the activity and then make the activity use the router based on logic in your ViewModel, maybe by some listener, or some `LiveData`, there are plenty of ways to do this so I'll leave it up to you to research that.
