### ISSUE TITLE
Save machine-readable error details from validators like MissingBindingValidator

### ISSUE THREAD

**Issue by KeatonTech** [google/dagger#2706]
This is a feature request to help solidify automated tooling around Dagger builds. When a build fails due to (for example) missing bindings I would like to get a list of the particular DependencyRequest keys that can't be found so that our project-specific developer tooling can automatically recommend modules to import. 

My team has thousands of test targets that each pull in a large chunk of the full app and so need to import a fairly large list of modules. For test-performance reasons we only want to import the modules that are actually required for each test, but that list can be really hard to pin down. Running the test first without any additional modules and having Dagger directly tell us what needs to get added would be a big help! Of course, for obvious reasons, MissingBindingValidator can only list the missing binding keys, not the modules from our project that provide them, hence the need for an extra layer of project-specific tooling.

My first thought was to create a custom Dagger SPI plugin, which has sort of worked! The problem is that my new plugin runs after the default validators and so if one of them fails, my plugin won't run at all. Naturally this is the one case I care about, since if there aren't any missing bindings then my plugin doesn't need to do anything.

Dagger plugins, including the build-in validators, can use the provided Filer object to save resource files into the Java bundle. If the built-in validators could take advantage of that to export a standard CSV/JSON/Protobuf version of the failure then our tooling could read that in and proceed from there. I would rather not parse the human-readable output as it's highly formatted (highly appreciated, BTW, as a human myself) and subject to change.

**Comment by Chang-Eric** [comment]
This is an area we want to generally improve with plugins, though our full plans will probably require a revamp of some of the plugin APIs. Incidentally though, we have built some plugins internally that are similar to what you are trying to build.

If you enable the flag `-Adagger.pluginsVisitFullBindingGraphs=ENABLED` then your plugin will be visited before the missing binding validator fails. This will give you a full binding graph though, which is a little different in that it will include bindings that we normally prune because they are unreachable. This might not be a problem for you, but if it is, you could also update your plugin to do a traversal to find only the reachable missing binding nodes.

**Comment by Chang-Eric** [comment]
Going to close this for now since hopefully setting that flag should solve your problem.
