### ISSUE TITLE
@BindValueIntoMap fields must have exactly one @MapKey. Found []

### ISSUE THREAD

**Issue by tynn** [google/dagger#2710]
This error is triggered by [`BindValueMetadata`](https://github.com/google/dagger/blob/4b695aefb0f5553ec3171ab47c2e7c80d5cbe73f/java/dagger/hilt/android/processor/internal/bindvalue/BindValueMetadata.java#L148):

> @BindValueIntoMap fields must have exactly one @MapKey. Found []

So in general this feature might be working with custom keys, but not with with any of the provided `@MapKey` defining `@Target(METHOD)` to only allow to annotate methods

 * `@ClassKey`
 * `@IntKey`
 * `@LongKey`
 * `@StringKey`

**Comment by Chang-Eric** [comment]
Just to make sure I'm understanding, when you get that error you must also get some error from the compiler saying that the `@ClassKey` or whichever one you are using cannot be applied to a field, right?

I assume this issue is less about the error message and more about a request to add the target to those dagger annotations. Is that correct?

**Comment by tynn** [comment]
Yes, the error for adding a provided map key to a property is:
> This annotation is not applicable to target 'member property with backing field' and use site target '@field'

In my case I was using `@StringKey("...")`.

I raised the issue here as the error itself could not be resolved. Adding the target might be the simples solution, but not the only one. In general I would like to request a working example (for Kotlin) or test case to use `@BindValueIntoMap` for testing purposes.
