### ISSUE TITLE
Optional alternative to javax.inject

### ISSUE THREAD

**Issue by overheadhunter** [google/dagger#2721]
[As per spec](https://dagger.dev/api/2.37/dagger/Provides.html), Dagger is

> allowing `null` by annotating the method with any `@Nullable` annotation like `javax.annotation.Nullable` or `androidx.annotation.Nullable`.

---

Now I'm wondering, if the same behaviour would be feasible for `@Inject`, `@Named`, ... annotation as well?

The reason why I'm proposing this change is simply, because [we can not expect `javax.inject` to declare an automatic module name](https://github.com/javax-inject/javax-inject/issues/33) any time soon. This effectively stops Dagger users from publishing named modules without relying on a filename-based module name for `javax.inject`.

If Dagger accepted these annotations from _any_ package, users could exclude the `javax.inject` dependency and use e.g. `jakarta.inject` instead.

`javax.inject` could still remain the default dependency, so this change wouldn't break anything. But it would add some flexibility when dealing with the module system.

**Comment by Chang-Eric** [comment]
I don't think we can do the same thing for `@Inject` as we did for `@Nullable` easily since the difference is we actually trigger our annotation processing off of the `@Inject` annotation. We do intend to support `jakarta.inject` though (https://github.com/google/dagger/issues/2058 is open for that) so hopefully that will solve your needs that way.

**Comment by overheadhunter** [comment]
Yes, that would solve the issue as well. 👍
