### ISSUE TITLE
error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved.

### ISSUE THREAD

**Issue by a914-gowtham** [google/dagger#2739]
I'm using [apollo](https://github.com/apollographql/apollo-android) for graphql.   I added @inject in the MainRepository class. 
then, I rebuilt the project for the hilt's stuff and I got this error.

**Error log** 
`/home/gowtham/AndroidStudioProjects/RickNMortyCompose/app/build/tmp/kapt3/stubs/debug/com/gowtham/ricknmorty/MainRepository.java:6: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public final class MainRepository {
             ^  `

**MainRepository.class** 
```kotlin

class MainRepository @Inject constructor(private val apolloClient: ApolloClient) {

    suspend fun getAllCharacters(page: Int): Response<GetCharactersQuery.Data> {
        return apolloClient.query(GetCharactersQuery(page = Input.optional(page))).await()
    }
}
```

**AllCharacters.graphql** 
```graphql
query GetCharacters($page: Int) {
    characters(page: $page) {
        info {
            pages, count, next
        }
        results {
            ...CharacterDetail
        }
    }
}
```

I assume it happens. because of the `GetCharactersQuery.Data` which is the generated code by apollo library. is there any way to solve it?

**Comment by Chang-Eric** [comment]
I think this is an issue that the type validation in the annotation processor is being over eager. We use it from a common library because it helps us wait for code to be generated from other annotation processors (I'm assuming apollo doesn't use an annotation processor for its code generation since it comes from some graphql file), but because the logic is generic it doesn't know what Dagger will and will not use so it can validate stuff that Dagger doesn't care about and then cause these kind of errors. We have https://github.com/google/dagger/issues/2208 to rewrite it into more specific Dagger logic, but it would be a bit of work and is probably a ways off.

I don't know much about apollo, so not sure how feasible this is, but probably the best thing to do would be to move the apollo generated code into a library so that it is done generating before Dagger tries to run on anything.

**Comment by a914-gowtham** [comment]
@Chang-Eric I don't know how to get generated file from apollo. I found a workaround,
 After i moved my api related code  from MainRepository.class to ApiHelperImpl.class. now, I inject ApiHelperImpl class like below instead of using constructor injection. Is this correct way?
```kotlin
@Singleton
    @Provides
    fun provideApiHelper(
        apollo: ApolloClient,
        @ApplicationContext context: Context
    ): ApiHelperImpl {
        return ApiHelperImpl(
            appContext = context,
            apolloClient = apollo
        )
```

**Comment by Chang-Eric** [comment]
Oops I had started a response to this earlier but got distracted. I think that is a reasonable workaround though, assuming `ApiHelperImpl` is going to be the only class that references the generated code, then just not running the Dagger processor over it should help avoid this problem.

**Comment by a914-gowtham** [comment]
thanks @Chang-Eric

**Comment by rcfrias** [comment]
I am having the same issue and error description, I have 1 LoginActivity and 1 MainActivity, for some reason the inject only works on the first one.
