### ISSUE TITLE
Provide methods with same name prohibited?

### ISSUE THREAD

**Issue by pyricau** [google/dagger#274]
I just got this: `Error:(35, 24) error: Cannot have more than one @Provides method with the same name in a single module`

I had a module with two methods with different signatures but the same name. Some old code I'm transitioning from Dagger1 to 2.

I'm merely curious about why this is enforced, I don't think it matters much, but if Java allows it, why forbid it?

**Comment by tbroyer** [comment]
I believe this is merely because the `dagger.internal.Factory` implementation that's being generated is named after the module class and provides method names, independently of the arguments' number and type: see https://github.com/google/dagger/blob/9293bcf0e8ddb93121dbdf74ff771a3ee9e43379/compiler/src/test/java/dagger/internal/codegen/ModuleFactoryGeneratorTest.java#L356 (and following tests, with and without arguments to the provider method).

**Comment by pyricau** [comment]
Makes sense. Thanks!

**Comment by gk5885** [comment]
It's not actually _because_ it causes issues with the generator.  There are plenty of places we have to deal with collisions.  We disallow it because it breaks just about every rule for what logically defines an overload.  Particularly, it only works because your 2 bindings happen to have different dependencies (right now), but there is no relationship between the dependencies of separate bindings.  EJ2: Item 41 has a bunch of good detail about what does and does not constitute a good use of overloads.

Also, from a more practical perspective, we have found that people rarely do it intentionally. Most of the time somebody copied and pasted a provides method and changed all of the relevant bits but forgot to change the method name.  This just leads to confusion later on, so it seemed best to have the validator check for it.

**Comment by pyricau** [comment]
yes, all true :) . And that's exactly what I had, something copy pasting a provider methods, and I detected that while trying to transition to Dagger2
