### ISSUE TITLE
Floating bug when injecting dependencies into BroadcastReceiver using Hilt

### ISSUE THREAD

**Issue by artyomefimov** [google/dagger#2741]
Hi everyone! Got some unexpected behavior while injecting dependencies using field injection into `AppWidgetProvider` which is actually `BroadcastReceiver`. My code looks like this:
```
@AndroidEntryPoint
class ExpensesControlAppWidget : AppWidgetProvider() {

    @Inject
    lateinit var expenseInteractor: ExpenseInteractor

    init {
        expenseInteractor.getExpensesForCurrentMonth()
    }
}
```
And in some cases i got crash with the following exception:
```
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.artyomefimov.expensescontrol, PID: 2834
    kotlin.UninitializedPropertyAccessException: lateinit property expenseInteractor has not been initialized
```

Can anyone help with this? Seems like a bug

**Comment by Chang-Eric** [comment]
In general, you can't use `@Inject` fields in an initializer block because those fields are set later (as noted by the `lateinit`). You can only use them after they are injected. In the case of a BroadcastReceiver, this happens after `super.onReceive()` is called, so you'll want to move that code after that. If you can't move that code for some reason and it must be in the initializer block, you can use an entry point to access that dependency instead (https://dagger.dev/hilt/entry-points)

**Comment by artyomefimov** [comment]
@Chang-Eric thanks! I thought to implement it using entry points. But it is really unexpected for me that in some cases lateinit field is already injected to the point of execution within `init` block and in some cases it's not.

**Comment by Chang-Eric** [comment]
Sorry, I don't think I'm familiar with the term "floating issue". In any case though, I think the only case where `@Inject lateinit` fields are accessible in `init` blocks are those cases where we inject in the constructor, which should just be in views. It would be nice if we could be consistent across all types, but for each different type of class, we have to choose a different point in time to inject the fields based on the most reasonable place in the lifecycle. You can see the table of when those fields will be injected at https://dagger.dev/hilt/components#component-lifetimes.
