### ISSUE TITLE
Dagger not working with packages named "public" 

### ISSUE THREAD

**Issue by chemouna** [google/dagger#2743]
getting an error when attempting to inject a class in a package named 'public':

`error: [Dagger/MissingBinding] error.NonExistentClass cannot be provided without an @Inject constructor or an @Provides-annotated method.
`

created a small sample project demonstrating the issue in https://github.com/chemouna/DaggerIssue

ran into this initially  use case because we were generating protobuf services with a package name contain public and injecting those service didn't work.

**Comment by bcorso** [comment]
The issue is that `kapt` silently ignores these classes.

In order to work with annotation processing, `kapt` generates a java stub class for each of your kotlin classes. However, since `public` is a keyword in java it can't be used as a package name, so `kapt` just silently ignores these classes rather than fail.

Thus, Dagger doesn't even know these classes exist, so there's not really anything we can do about it. Maybe once Dagger supports [KSP](https://github.com/google/ksp) and generates Kotlin this may be possible, but even if we do that it would be a long ways off.

For now your best option is to avoid using Java keywords for your package names.
