### ISSUE TITLE
Accept lists of keys to bind to a provided map.

### ISSUE THREAD

**Issue by CoatedMoose** [google/dagger#275]
On a particular project, I find myself having to provide a particular provider to multiple keys. I would like to be able to have the `@MapKey` annotated type take an array. Something like this.

```java
@MapKey(unwrapValue = true)
@Retention(RUNTIME)
public @interface StringKey {
String[] value();
}
```
So instead of this:
```java
@Module
class MyModule {
  @Provides(type = Provides.Type.MAP)
  @StringKey("A_STRING")
  ResponseBuilder provideA(DefaultResponseBuilder defaultBuilder) {
    return defaultBuilder;
  }

  @Provides(type = Provides.Type.MAP)
  @StringKey("B_STRING")
  ResponseBuilder provideB(DefaultResponseBuilder defaultBuilder) {
    return defaultBuilder;
  }
}
```
Would be equivalent to this.
```java
@Module
class MyModule {
  @Provides(type = Provides.Type.MAP) // Maybe a different type could/should be used?
  @StringKey({"A_STRING", "B_STRING"})
  ResponseBuilder provide(DefaultResponseBuilder defaultBuilder) {
    return defaultBuilder;
  }
}
```

I seem to recall reading somewhere that `MapKey` annotated class can't take array, but I can't find it now. That being the case, I don't expect this would conflict with anything. However I might be missing something (in particular, why arrays aren't allowed). I am also not sure what the best way to handle scoping would be. Maybe enforcing only providing `Provider`s should be considered.

Another alternative I was toying with was writing a separate annotation processor that would generate those methods into another module. This could be kept separate from dagger and possibly re-usable with non-dagger projects, however, I currently can't think of a reason why I would need that functionality in a non-dagger context. I don't really like this option.

**Comment by gk5885** [comment]
Equality for an array in java is _instance_ equality (hence the need for `Arrays.equals()`).  If arrays were allowed as map keys, the only way that get would ever work would be if you were to pass the **exact same instance**.  That's why `@MapKey` doesn't take an array -- it's current definition says that the value _is_ the key.

The feature that you're asking for here seems to me to have less to do with the API for `@MapKey` and more like the ability to make a key `@Repeatable` and have that mean that a single value is being associated with multiple keys.  That actually makes a bit of sense to me.  Unfortunately, `@Repeatable` only exists in Java 8, so that probably won't help a large portion of our users.

Usually, when you want to make something like a repeatable annotation, you can just make a wrapper annotation that takes an array of the annotation you want to repeat.  Unfortunately, you can't take _any_ annotation, so for each `@MapKey` that we'd want to repeat you'd have to make a wrapper.  I'm not sure that that this feature would get enough use to warrant all of the extra API…

**Comment by CoatedMoose** [comment]
I haven't really started poking around to see what would be needed to implement this, or how `MapKey`s are implemented already, so correct me if I am confusing the issue.

I wasn't aware of `@Repeatable` until just now, but I assume you mean to use it like this (instead of what I was suggesting in the issue): 
```java
@Module
class MyModule {
  @Provides(type = Provides.Type.MAP)
  @StringKey("A_STRING")
  @StringKey("B_STRING")
  ResponseBuilder provide(DefaultResponseBuilder defaultBuilder) {
    return defaultBuilder;
  }
}
```

I can see that being a cleaner/more flexible interface than what I was suggesting, but as you mentioned, does limit support to java 8.

I understand why you wouldn't want the key to be an array. Since this is the case, why not allow binding with each of the instances contained in the array as the key, rather than the array itself as the key? Since arrays as keys are disallowed for other reasons, if the value happens to be an array, then bind to each particular instance to the returned/provided value.

**Comment by CoatedMoose** [comment]
Point in my last comment being, it isn't much extra API (at least superficially).

**Comment by CoatedMoose** [comment]
I may have some time available to take a swing at this, but don't want to sink a bunch of effort if it won't be useful. How do you feel about the feature?

**Comment by ronshapiro** [comment]
This is probably doesn't have a large enough benefit for us to consider incorporating it. Since it's easy enough to do as is and we suspect that it's not going to be widely used, it's not something we plan on supporting. When we can start supporting Java 8 we can reconsider this.
