### ISSUE TITLE
Make annotation processing lombok-aware

### ISSUE THREAD

**Issue by CC007** [google/dagger#2781]
With lombok it is possible to add a `@NoArgsConstructor`, `@AllArgsConstructor` or `@RequiredArgsConstructor` annotation to a class to auto-generate a constructor for that class. It is also possible to specify any annotations that should be put on that constuctor like so:
```java
@NoArgsConstructor(onConstructor_ = @Inject)
public class ExampleClass {
}
```
Which generates:
```java
public class ExampleClass {
    @Inject
    public ExampleClass() {
    }
}
```
I am using Maven with the following config for the maven-compiler-plugin:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.6.1</version>
    <configuration>
        <annotationProcessorPaths>
            <path>
                <groupId>com.google.dagger</groupId>
                <artifactId>dagger-compiler</artifactId>
                <version>2.16</version>
            </path>

            <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.18.20</version>
            </path>
        </annotationProcessorPaths>
    </configuration>
</plugin>
```
As you can see, it should be possible for this generated class to be used as a binding, but I'm still getting the following error:
```
[Dagger/MissingBinding] my.package.name.ExampleClass cannot be provided without an @Inject constructor or an @Provides-annotated method.
```
It doesn't matter if I use JDK 8  or JDK 14, both exhibit this behavior.

Would it be possible for Dagger to make sure that lombok annotation processing happens before dagger annotation processing, so that it can detect the `@Inject` annotation correctly?

**Comment by CC007** [comment]
From what I can see when I run the maven compiler plugin verbosely, it looks like it supports multiple rounds of annotation processing, so if dagger were to process the annotations in round 2 instead of round 1, it might already solve the issue. Any idea if this can be achieved?

**Comment by danysantiago** [comment]
Have you try declaring Lombok first in the annotation processor classpath so it gets discovered and 'run' first?

The order in which processors are run should not be guaranteed, which is why they work via 'rounds', so that as long as new code is generated processors can keep acting on it. However, Lombok is special (and I don't know how it fully works), but it is likely transforming (maybe via bytecode or internal JDK APIs) the structure of the Java classes which [is normally not permitted in an annotation processor](https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/Filer.html#:~:text=In%20general%2C%20processors%20must%20not%20knowingly%20attempt%20to%20overwrite%20existing%20files), specifically annotation processors should only create new sources (or classes), but cannot modifying existing ones.

Usually in Dagger if you have some class that is not yet generated, say, some return type of a `@Provides` method, Dagger will differ processing until the subsequent rounds in hopes for that the class is generated by another processor. But with Lombok and specifically the constructor feature, it seems as if the class is already well-formed so there is no way for Dagger to 'differ' processing because all types are resolved. It just looks as if the constructors is simply not there.

I would suggest you file some feature request or bug to Lombok asking how to configure Lombok such that it always runs first such that other annotation processors can be aware of the modifications done by Lombok.

**Comment by CC007** [comment]
> Have you try declaring Lombok first in the annotation processor classpath so it gets discovered and 'run' first?

Yes

> Lombok is special (and I don't know how it fully works), but it is likely transforming (maybe via bytecode or internal JDK APIs) the structure of the Java classes 

Yea, they're special like that... 

> I would suggest you file some feature request or bug to Lombok asking how to configure Lombok such that it always runs first such that other annotation processors can be aware of the modifications done by Lombok.

I'll see what I can do. If all else fails, I can try to use the lombok-maven-plugin instead.
