### ISSUE TITLE
Generated code doesn't support modules with identical names

### ISSUE THREAD

**Issue by pyricau** [google/dagger#279]
Here's the use case:

```java
@Component(modules=SharedModule.class)
public interface AppComponent {
  @Module class SharedModule {}
}
```

```java
@Component(modules=SharedModule.class)
public interface DevAppComponent extends AppComponent {
  @Module(includes=AppComponent.SharedModule.class)
  class SharedModule {}
}
```

The generated `DaggerDevAppComponent.Builder` has this:

```java
@Deprecated
public Builder sharedModule(DevAppComponent.SharedModule sharedModule) {
  if (sharedModule == null) {
    throw new NullPointerException();
  }
  return this;
}

@Deprecated
public Builder sharedModule(SharedModule sharedModule) {
  if (sharedModule == null) {
    throw new NullPointerException();
  }
  return this;
}
```

Both methods get a java compile time error, `sharedModule(SharedModule)` is already defined in DaggerDevAppComponent.Builder`.

The reason is because `SharedModule` resolves to the closest declaration, ie `DevAppComponent.SharedModule`, so we effectively have two `sharedModule(DevAppComponent.SharedModule)` methods.

So either both should use the outer class name (might be simpler), only the furthest ones.

**Comment by pyricau** [comment]
As an aside, what's up with this `@Deprecated`? Is there some doc or issue that I can go read on? This is worrying.

**Comment by ronshapiro** [comment]
Looks like all your methods in your `@Module` are static. They're deprecated because you don't need to supply instances of those modules; the methods can be invoked directly.

As a workaround, can you define a `@Component.Builder` with the modules that you do need to supply to the builder (ones with non-default constructors) and name them however you chose? I imagine the list of builder methods will be short (if any) and you can avoid this issue.

**Comment by pyricau** [comment]
Ah, right, this only happens for empty modules that I use to define shared list of includes. So it's fine, but I guess a little comment would help understand what this `@Deprecated` is about :) .

**Comment by ronshapiro** [comment]
I've begun a switch from JavaWriter to JavaPoet so that we could more easily add comments to the source to address the `@Deprecated` issue, but I'm not sure that JavaPoet will do better at solving this issue. The root of this problem is that module is nested in the Component interface, so even if you remove the `extends` clause from `DevAppComponent` you can get into this issue. Neither JavaPoet nor JavaWriter know anything about class hierarchies, so when generating `DaggerDevAppComponent`, they aren't aware that `SharedModule` will be inherently nested. JavaWriter assumes to unqualify one of them and it seems that JavaPoet [does the same](https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/CodeWriter.java#L410-L413). I'm not sure this is something we want to support or feature request on JavaPoet. I think the best advice I have is either (a) don't nest modules in your components if you don't have to and (b) if you want to, then give them different names.

**Comment by ronshapiro** [comment]
Note that this does work since there is no ambiguity of naming if one is or is not imported.

```java
class Foo {
  @Module static class M {}
}

class Bar {
  @Module(includes = Foo.M.class)
  static class M {}
}

@Component(modules=Foo.M.class)
interface One {}

@Component(modules=Bar.M.class)
interface Two extends One {}
```

**Comment by pyricau** [comment]
If it works in Java, it should work in Dagger. I agree it's a corner case, low priority. @swankjesse any thoughts on providing the ability in javapoet to control which class is imported, or provide an option to use FQN for both types in case of simple name conflicts? This should happen any time we generate code with type shadowing.

**Comment by pyricau** [comment]
A maybe simpler option would be to detect this and error out in Dagger.

**Comment by JakeWharton** [comment]
You can use FQCN yourself by not using `$T` to participate in import resolution.

**Comment by ronshapiro** [comment]
Ah, I just found this commit (https://github.com/square/javapoet/commit/dc836e498fde995a74c71f363957522192b69ed5) which should do the trick. I've begun the javawriter -> javapoet migration, so as that gets completed I'll ping this to see if it resolves the issue on your end.
