### ISSUE TITLE
Enabling enableAggregatingTask causes Gradle build cache miss on multi-flavoured builds

### ISSUE THREAD

**Issue by FatihYalmanbas** [google/dagger#2795]
**Environment:**
Hilt version 2.38.1
enableAggregatingTask true
Gradle 7.1.1
Android Gradle plugin 4.2.2

**When does it happen?**
Run `clean assembleDebug` task twice on same device

**What happens?**
 `hiltJavaCompileFlavour1Debug` and `hiltJavaCompileFlavor2Debug` tasks have different value properties which causes cache misses 

Please see below screenshot from gradle build-scan for more info;

Blue dots represent values given for first build while green dots represent values given for second build

<img width="839" alt="Screenshot 2021-08-03 at 12 28 01" src="https://user-images.githubusercontent.com/13086186/128011743-70933a9e-6018-42a2-bf53-f5f172f39772.png">

<img width="883" alt="Screenshot 2021-08-03 at 12 27 53" src="https://user-images.githubusercontent.com/13086186/128011746-2b5ebf6d-0ced-4d98-8eb7-40797a5dddc3.png">

**Comment by danysantiago** [comment]
I think cache is being disabled due to a correctness issue.

Specifically I've seen the following warnings:
```
> Task :app:hiltJavaCompileProductionDebug
Execution optimizations have been disabled for task ':app:hiltJavaCompileProductionDebug' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/usr/local/google/home/danysantiago/AndroidStudioProjects/HiltCheck/app/build/intermediates/compile_and_runtime_not_namespaced_r_class_jar/developDebug/R.jar'. Reason: Task ':app:hiltJavaCompileProductionDebug' uses this output of task ':app:processDevelopDebugResources' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/usr/local/google/home/danysantiago/AndroidStudioProjects/HiltCheck/app/build/tmp/kapt3/classes/developDebug'. Reason: Task ':app:hiltJavaCompileProductionDebug' uses this output of task ':app:kaptDevelopDebugKotlin' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

We have an internal bug tracking this issue. One interesting thing is that it happens when building multiple flavors with a single task (i.e. `assembleDebug`) but I've have not seen this issue when building using the specific flavor tasks (i.e. `assmebleFlavour1Debug` and `assembleFlavour2Debug` separetly), so maybe you can try that as a workaround.

From what I've gathered we are basically running into an implicit dependency issue: https://docs.gradle.org/7.1/userguide/validation_problems.html#implicit_dependency. The `hiltJavaCompile*` task takes as input the variant's JavaCompile classpath which itself is populated from outputs of various other tasks (like kapt or kotlinc) which are configured by the Android Gradle Plugin, and it seems the tasks dependency is being lost as the plugin uses File APIs ([see here](https://github.com/google/dagger/blob/master/java/dagger/hilt/android/plugin/src/main/kotlin/dagger/hilt/android/plugin/HiltGradlePlugin.kt#L323-L340)).

I'm don't have a good solution yet, it would be bad for the Hilt plugin to search and find the various tasks that make up AGP's JavaCompile task classpath and make them explicit dependencies of the task. It would be more ideal if the `FileCollection` in JavaCompile retained task information and that would be translated to the Hilt created configuration, but I don't know if it does and is being lost or if we have to change the way we gather kapt and kotlinc outputs.

**Comment by danysantiago** [comment]
@FatihYalmanbas can you try using Gradle 7.2 RC3 ?

We think this is an issue in Gradle that was recently [fixed](https://github.com/gradle/gradle/commit/40f3152005920fe6b610ca5081b7c40e305a361d) in 7.2, I was able to verify the fix on my end but would be great if you could confirm it too. Thanks!

**Comment by FatihYalmanbas** [comment]
Hey @danysantiago, Unfortunately since we run this task on CI I'd rather have all my assemble tasks run in one invocation in order to reduce time spent

But I will try giving Gradle 7.2 a chance to test if it works. Thanks for your fast reply 👍🏻

**Comment by FatihYalmanbas** [comment]
Yes, updating to 7.2-rc-2 seems to fix this issue
