### ISSUE TITLE
Add ability to inject abstract @AssistedInject

### ISSUE THREAD

**Issue by mnayef95impressions** [google/dagger#2825]
I have a use case while I have to inject the abstract class, not the implementation itself, but the implementation requires an assisted parameter to be injected, like this:

```kotlin
class ClassAImpl @AssistedInject constructor(
    @Assisted private val params: ClassAParams
) : ClassA {

    ....

    @AssistedFactory
    interface ClassAFactory {

        fun create(params: ClassAParams): ClassA
    }
}
```

I got this error:
```
An assisted factory's abstract method must return a type with an @AssistedInject-annotated constructor.
```

While it should work fine

**Comment by tbroyer** [comment]
Just because the `ClassAFactory` is nested into `ClassAImpl` does not mean Dagger will extrapolate anything from that: it sees an `@AssistedFactory` interface whose abstract methods returns a `ClassA`, whose constructor is (apparently) not annotated with `@AssistedInject`.

Because you don't _inject_ either `ClassA` or `ClassAImpl` instances, but only `ClassAFactory`, you can declare the method to return `ClassAImpl`, and then it should Just Work™.

If you don't want to expose the detail that this will be a `ClassAImpl` instance, and really want injection points to only know about `ClassA`, then make an interface for `ClassA`, and then have the `@AssistedFactory` extend it and override the method to tighten its return type, and then finally add a binding for those interfaces so Dagger will actually inject a `ClassAImplFactory` whenever a `ClassAFactory` is needed:

```kotlin
// This is your "public API"
interface ClassAFactory {
    fun create(params: ClassAParams): ClassA
}

// This is an implementation detail for Dagger
interface ClassAImplFactory : ClassAFactory {
    override fun create(params: ClassParams): ClassAImpl
}

// Add that to you @Module
@Binds fun bindClassAFactory(factory: ClassAImplFactory): ClassAFactory

// This will actually receive a ClassAImplFactory, so create(params) will return a ClassAImpl instance
@Inject lateinit var classAFactory: ClassAFactory
```
(this should work in theory, but I haven't tested it, so maybe there are limitations in Dagger that would prevent it from working)

**Comment by Chang-Eric** [comment]
Going to close this since the comment by @tbroyer is what I would suggest as well.

**Comment by udamaster** [comment]
I tried the suggestion above and it results in the same exception at compile time. :-/

**Comment by bcorso** [comment]
@udamaster where did you put the `@AssistedFactory` annotation? In the example in https://github.com/google/dagger/issues/2825#issuecomment-903832310 it should go on the `ClassAImplFactory`.

**Comment by udamaster** [comment]
Yep, got it to work ...that was the prob. Thanks
