### ISSUE TITLE
Provide multiple bindings for the same type

### ISSUE THREAD

**Issue by andrewhunter0** [google/dagger#2832]
Hi, I See here
[Provide multiple bindings for the same type](https://developer.android.google.cn/training/dependency-injection/hilt-android)
In section[Provide multiple bindings for the same type], We can use `@Qualifier` to provide multiple bindings for the same type, such as `@AuthInterceptorOkHttpClient` and `@OtherInterceptorOkHttpClient` to inject the specific type that we need.

But this usage doesn't seem to be an elegant way.

According to the normal design of Java, the caller should not care about which specific instance it uses, but the example in hilt, it really needs to care about which instance it use (which should be identified by annotation).    

The correct thing is that when user refers to the instance object through an interface, the real instance of the interface is dynamic.  

```
A extends C
B extends C 

public class InstanceManager {
    private C mInstance = new A();
    public void getC() {
        return mInstance;
    }

    public void setC(C instance) {
        mInstance = instance;
    }

    private static InstanceManager  mManager;
    private InstanceManager() {}
    public static InstanceManager instance() {
        if (mManager == null) {
            mManager = new InstanceManager();
        }
        return mManager;
    }
}
```   

In module `app`, I first get instance of A(class A is in module `app`)
```
C cInstance = InstanceManager.instance().getC()
```   

When another  module `business` is running, it changes the instance  to B(class B is in module `business`)
```
InstanceManager.instance().setC(new B())
```  

And now In module `app`, cInstance will change to B, and module `app` doesn't care which is the real instance of C
```
C cInstance = InstanceManager.instance().getC()
```   

So, can we add an ability to dynamically replace the instance that provided by annotations `@Provides`?

**Comment by Chang-Eric** [comment]
I think saying the client shouldn't need to know the type and so shouldn't need to use a qualifier is taking that advice too far. I take that advice to be that clients shouldn't care about the implementation, but just about the concept. Sometimes concepts match exactly to types, but sometimes they don't. For example, maybe you have two RPC clients to two different servers. We shouldn't have to combine them into the same binding just because they share the same RPC client type. In fact, you might have a situation where you need to call both because they are separate concepts.

I'm not sure I understand how dynamic replacement of the instance would work, but in general it'd be better to avoid any sort of implicit switching, since that just adds more confusion to what objects you are actually getting. If there are situations where you cannot know the instance until runtime, you might check out assisted injection, though I'm not sure if that is what you are asking for.

**Comment by andrewhunter0** [comment]
Yes, you can retain this ability :  `For example, maybe you have two RPC clients to two different servers. We shouldn't have to combine them into the same binding just because they share the same RPC client type. In fact, you might have a situation where you need to call both because they are separate concepts.` 

But more generally, we provide an interface and write different implementations for the interface. We don't need to know how the interface methods are implemented.   

For example, I don't care which database is used to store data. I only need to operate data through the `get`、`update` or `set` methods that provided by the interface . I don't need to know where the data is stored and how it is obtained.

**Comment by Chang-Eric** [comment]
Right, but that is what Dagger provides you the ability to do already with binding an interface to an implementation. Maybe I don't understand the request, but if your thing doesn't care which database it uses, that's fine, you can have your implementation figure it out on its own via whatever logic you choose.
