### ISSUE TITLE
Missing @AndroidEntryPoint activity annotation causes crash in runtime instead compilation time

### ISSUE THREAD

**Issue by msesma** [google/dagger#2842]
Version used: 2.38.1

Let's have an activity NOT annotated with @AndroidEntryPoint by mistake, where we are not injecting anything. In this activity we have a fragment,  annotated with @AndroidEntryPoint where we inject some dependencies.

Actual result:
This application will compile without errors and it will crash in runtime :
```
    Process: com.example.android.hilt, PID: 27485
        java.lang.IllegalStateException: Hilt Fragments must be attached to an @AndroidEntryPoint Activity. Found: class com.example.android.hilt.ui.MainActivity
```

Expected result:
The app compilation will fail.

To reproduce it, use the Hilt codelab, https://developer.android.com/codelabs/android-hilt
At the end of Step 7, where the codelab says `Hilt needs to be aware of the Activity that hosts the Fragment in order to work. We'll need to use @AndroidEntryPoint.`, don't do it and run the app. Press a button and the app will crash with the above error.

**Comment by danysantiago** [comment]
This is tricky because we don't know at compile time wether a `@AndroidEntryPoint` fragment will be attached to the activity.

We could have a Lint warning, but it'll just be a warning and it can be noisy since it would ask users to annotate all their activities with `@AndroidEntryPoint` even though they might not needed. Or it could lead to missing the warning if say we warn only when an `@Inject` is found in the activity.

**Comment by msesma** [comment]
I cannot understand why the activity needs a `@AndroidEntryPoint` annotation if nothing is going to be injected on it. In plain Dagger this is not necessary. 
I suppose it is done in order to have the activity context available as `@ActivityBinding`, but what if I don't need that binding?

**Comment by danysantiago** [comment]
The main reason an Activity that hosts a Fragment that is an `@AndroidEntryPoint` also needs to be annotated with `@AndroidEntryPoint` is because the Activity hosts the `ActivityComponent` which is the parent component of the `FragmentComponent` (see [hierarchy](https://dagger.dev/hilt/components)). In plain Dagger if you had a similar setup where activities host a parent component for fragments, then you would need to create and retain the component with the activity such that fragments created can create their subcomponent, even if the activity is not injected. That is essentially what the `@AndroidEntryPoint` annotated Activity is doing.
