### ISSUE TITLE
FR: Allow binding of Supplier<T> in addition to Provider<T>

### ISSUE THREAD

**Issue by perezd** [google/dagger#2843]
This is a small thing, but I'm often finding myself fighting with APIs that work well with Supplier<T> only to have Provider<T> available in the binding graph. It'd be cool to be able to support both depending on which is declared in the type signature.

**Comment by JakeWharton** [comment]
You should be able to pass `injectedProvider::get` to a supplier-accepting API as a fairly terse workaround for now.

One problem here is what happens when someone binds `Suppler<T>` into the graph? Dagger prevents you from binding `Provider<T>` so that a dependency request of `Provider<T>` is unambiguous in that it should be a Dagger-wrapped provider of the mechanism for resolving `T`.

**Comment by perezd** [comment]
yeah that's annoying, I definitely been doing both things to work around this which complicates prevention. I guess it could be detected if someone is binding a `Supplier<T>` and can warn them that their takes precedence in this case?

Another Idea would be to provide a new `dagger.Provider<T>` that implements both like so:

```
  interface Provider<T> extends javax.inject.Provider<T>, java.util.function.Supplier<T> {
    T get();
  }
```

And then have folks request that one if you want to be compatible. Thinking out loud, not sure that works.

**Comment by Chang-Eric** [comment]
I think this would be practically difficult to do. The issue Jake mentions is one thing, and `Supplier` being introduced in JDK8 is another problem. I also think it'd add confusion to have both interfaces supported but be functionally the same. Closing this since I think it is unlikely we'd make this change.
