### ISSUE TITLE
@AssistedFactory-annotated type is missing with kotlin value classes

### ISSUE THREAD

**Issue by m4xp1** [google/dagger#2855]
When using kotlin inline or value classes of the form:

```kotlin  
@JvmInline
value class LocationIata(val code: String) : Serializable
```

```kotlin  
inline class LocationIata(val code: String) : Serializable
```

In ViewModel 

```kotlin  
class TransferInformerViewModel @AssistedInject constructor(
  @Assisted private val originLocation: LocationIata,
) : ViewModel() {

  @AssistedFactory
  interface Factory {
    fun create(
      originLocation: LocationIata
    ): TransferInformerViewModel
  }
}
``` 

We get a compilation error: 

```kotlin  
The @AssistedFactory-annotated type is missing an abstract, non-default method whose return type matches the assisted injection type.
    public static abstract interface Factory {
                           ^
```

**Comment by bcorso** [comment]
Unfortunately, it looks like the KAPT generated stub for the factory just drops the `create()` method, so I don't think there's much we can do about this on the Dagger side. 

You can try filing a bug with https://youtrack.jetbrains.com/issues/KT to verify if this is KAPT bug or if `inline` classes are just not interoperable with java code. 

Otherwise, we may be able to support this at some point in the future when Dagger enables processing with KSP and generating Kotlin code so that it's possible to avoid java altogether, but that's a far ways off for now.
