### ISSUE TITLE
@AndroidEntryPoint in abstract fragment

### ISSUE THREAD

**Issue by CROCDC** [google/dagger#2912]
Hi!!! I have this doubt 

ok how i solved this 

![image](https://user-images.githubusercontent.com/36147037/135916252-60ceabb1-601b-40d3-ac04-7619cba5aa82.png)

I have an abstract fragment annotated with AndroidEntryPoint and my MainFragment use the abstract fragment

![image](https://user-images.githubusercontent.com/36147037/135916409-ca8db53b-4ced-461e-9af1-1606970b52f3.png)

this way I don't need to put the AndroidEntryPoint twice, is this way to use AndroidEntryPoint ???

**Comment by bcorso** [comment]
This works if your subclass does not contain `@Inject` fields itself. However, once you add `@Inject` fields in the subclass, you will also need to annotate the subclass with `@AndroidEntryPoint`. Otherwise, Dagger will only inject the `@Inject` in the abstract fragment and the other `@Inject` fields will never be initialized and you'll get an NPE or similar during runtime when you access those fields.

**Comment by CROCDC** [comment]
so I only need add the AndroidEntryPoint when my subclass has fields with Inject????

**Comment by bcorso** [comment]
Yep

**Comment by CROCDC** [comment]
So what do you think of this? https://github.com/google/dagger/issues/2682

**Comment by bcorso** [comment]
I agree with @Chang-Eric's comment. 

To clarify, my comment above only relates to `@Inject` fields, I completely missed that you were asking about `@HiltViewModel` usage in your example. ViewModels are a special case which I think @Chang-Eric summed up nicely in #2682.

However, I'm still not sure I've answered your question. If you're asking if you have to annotate your parent fragment in this case, the answer is yes. If you're asking if you have to annotate your child fragments in this case, the answer is no. If you're asking if it's recommended to annotate the child fragments in this case, I'd probably say yes just because it makes it more explicit that your fragment is using Hilt, but that's just my preference.

**Comment by CROCDC** [comment]
perfect!
