### ISSUE TITLE
Prevent specific bindings from being exposed to all subcomponents

### ISSUE THREAD

**Issue by pyricau** [google/dagger#296]
Subcomponents are amazing because they simplify the work so much. No need to define a whitelist of bindings to consumers / sub scopes. However, the entire world is available to sub components. I would like us to consider some sort of blacklist API.

For instance, let's say we have an `AppComponent` and a `LoggedInComponent` that's a subcomponent of `AppComponent`. `AppComponent` has a `CurrencyHolder` binding that holds a `Currency` when the user is logged in, and no currency otherwise. That currency never changes in the logged in scope. Bindings in the logged in scope should never be able to inject the `CurrencyHolder`, they should only inject `Currency`.

This API could be defined in a similar way to scoping annotations. Let's define an `@Private` annotation that's works the same way `@Scope` works.

``` java
@Private
public @interface AppPrivate {
}

@Scope
public @interface AppScope {
}

@Module
public class AppModule {
  // This binding won't be available in LoggedInComponent.
  @Provides @AppPrivate @AppScope CurrencyHolder currencyHolder() {
     return new CurrencyHolder(); 
   }
}

@AppScope
@AppPrivate
@Component(modules = AppModule.class)
public interface AppComponent {
  LoggedInComponent loggedIn(LoggedInModule module);
}

@Subcomponent(modules = LoggedInModule.class)
public interface LoggedInComponent {
}
```

Additionally Dagger would check that the private binding isn't exposed by the component (ie not defined as a method on the component interface).

We'd use annotation equality, similar to scopes, so we could have this:

``` java
@Private
public @interface OnlyIn {
  Class<?> value();
}

@Scope
public @interface SingleIn {
  Class<?> value();
}

@Module
public class AppModule {
  // This binding won't be available in LoggedInComponent.
  @Provides @OnlyIn(AppComponent.class) @SingleIn(AppComponent.class) CurrencyHolder currencyHolder() {
     return new CurrencyHolder(); 
   }
}

@SingleIn(AppComponent.class)
@OnlyIn(AppComponent.class)
@Component(modules = AppModule.class)
public interface AppComponent {
  LoggedInComponent loggedIn(LoggedInModule module);
}
```

**Comment by ronshapiro** [comment]
Does using a `@Qualifier` with restricted accessibility suit your needs? 

```java
@Module class M {
  @Qualifier private @interface Private {}

  @Provides @Private Dep1 provideDep1() { return new Dep1(); }
  @Provides @Private Dep2 provideDep2() { return new Dep2(); }

  @Provides UsesDeps provideUsesDeps(@Private Dep1 dep1, @Private Dep2 dep2) {
    return new UsesDeps(dep1, dep2);
  }
}
```

Technically `@Private Dep1` and `@Private Dep2` are part of their children components as well, but since those could never actually access `@M.Private` they are effectively blacklisted. If everything is enclosed well within the same module, or the qualifier can be package private and the children components live in different packages, this could work well. I think this has also been @gk5885's approach to this so far IIRC.

**Comment by pyricau** [comment]
This is an interesting approach. It does require using provide methods for many bindings who would otherwise just be constructor injects.

**Comment by tasomaniac** [comment]
Correct me if I am wrong but can't this be also achived by putting `CurrencyHolder` into another `SubComponent`? Since it is in another subcomponent, no-one will be able to inject it. 

The places that needs it (i.e some module in main graph) can depend on the builder of that subcomponent that holds the `CurrencyHolder` and can access it.

I am actually referring to `Subcomponents for encapsulation` section in this [document](http://google.github.io/dagger/subcomponents.html)

**Comment by pyricau** [comment]
@tasomaniac Oh nice idea. That means you'd have to create a new instance of the subcomponent every time you want to inject CurrencyHolder in the main graph though, right?

**Comment by tasomaniac** [comment]
I guess so. If all the modules that uses `CurrencyHolder` has a single parent `Module`, you can put that subcomponent into that `Module` though. Then it will be initialized only once and can be used by all the child module of that `Module`. And no other module could access it.

**Comment by ronshapiro** [comment]
I think both of those options are our recommendations for how to achieve this option. Creating a subcomponent for one binding shouldn't be so heavyweight compared to having the dependent bindings in the parent component, plus the costs of initializing a factory. I'm going to close for now, but we can always rediscuss at another time.
