### ISSUE TITLE
Issue with `enableAggregatingTask = true`

### ISSUE THREAD

**Issue by atfb** [google/dagger#2996]
After enabling `enableAggregatingTask` on version 2.38.1 I'm getting dependency issues. 

The issues can be fixed if I either add a direct dependency to the submodule or expose the submodule via `api` but based on [this](https://dagger.dev/hilt/gradle-setup.html#classpath-aggregation) `enableAggregatingTask` should be doing the job.

### :moduleB
````
dependencies {
    implementation project(":moduleC")
}

hilt {
    enableAggregatingTask = true
}
````

### :moduleC
````
package moduleC;

public class DatabaseMigrationManager {
}
````
````
hilt {
    enableAggregatingTask = true
}
````

### :moduleA

````
import moduleC.DatabaseMigrationManager

public class LifecycleManagerTest {

    @Mock private DatabaseMigrationManager databaseMigrationManager;
}
````

````
dependencies {
    testImplementation project(":moduleB")
}

hilt {
    enableAggregatingTask = true
}
````

Stacktrace
````
error: cannot find symbol
import moduleC.DatabaseMigrationManager;
                                  ^
  symbol:   class DatabaseMigrationManager

Execution failed for task ':compileDebugUnitTestJavaWithJavac'
Compilation failed; see the compiler error output for details
````

=====
Version: 2.38.1 with `enableAggregatingTask = true` fails but works with `enableExperimentalClasspathAggregation`

**Comment by danysantiago** [comment]
This is working as intended, with `enableExperimentalClasspathAggregation` classes were being over exposed across compilation boundaries, while with `enableAggregatingTask` the dependency aggregation is *only* done for the compilation unit where Dagger code is generated.

In this case because `moduleA` directly references a class in `moduleC` it should declare a dependency to it, or if it makes sense given how `moduleB` works, for it to provide `moduleC` as an API. The when to use `api` vs `implementation` can be found here: https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_recognizing_dependencies

**Comment by atfb** [comment]
Thanks @danysantiago. It makes sense now.

Based on the docs tho `enableAggregatingTask ` should give "the same benefits" right? So, I assumed the transition should be seamless.  It might be a good idea to have a mention about this on the setup page.

Doc for [enableAggregatingTask](https://dagger.dev/hilt/gradle-setup.html)
> Note that this option replaces enableExperimentalClasspathAggregation since it has the same benefits without any of its caveats.

Doc for [enableExperimentalClasspathAggregation](https://dagger.dev/hilt/gradle-setup.html#classpath-aggregation)
> With this option enabled, implementation dependencies don’t have to be relaxed to api.
