### ISSUE TITLE
Abstract classes with @Provides should not fail requiring a @Module annotation.

### ISSUE THREAD

**Issue by JakeWharton** [google/dagger#304]
The type is uninstantiable so there's no harm in omitting the annotation.

**Comment by RodrigoQuesadaDev** [comment]
+1 It would be great if they could also be ignored for default methods on interfaces.

**Comment by cesar1000** [comment]
Why is it not desirable to annotate all classes containing providers with @Module? Abstract modules are still usable (@Binds, static providers). Also, using base class modules is not a good practice, and I don't think Dagger should encourage it.

**Comment by RodrigoQuesadaDev** [comment]
It seems like these days simply stating something "is not a good practice" is a widely accepted (good?) practice. Would you mind elaborating a bit why is it that you think that way? Even if that statement were to be true, I still find this current limitation—of not being able to define provider methods on non-annotated base module classes/interfaces (which by the way, don't affect the dependency graph unless they are actually inherited by a Dagger module)—forces you to have lots of boilerplate code (which makes your code harder to implement, understand and maintain).

Being able to define base module classes (which are not actual modules) would undoubtedly allow you to reuse many parts of your dependency graph (otherwise you might find yourself having to define the same dependency subgraph over and over again for different implementation and/or subtypes of certain components); like when you have a layer super type (http://martinfowler.com/eaaCatalog/layerSupertype.html) defined in your domain layer and you want to reuse the associated dependency graph structure created around each of the subclasses (e.g. like associated repository dependencies in case you are using the repository pattern).

On the other hand, the only thing that I remember reading in the official documentation about using base modules being a bad thing, is when you want just want to override some module methods for the sake of being able to simply swap some component implementations during testing (see http://google.github.io/dagger/testing.html, specifically Option 1 for replacing bindings), and that is absolutely not related with being—or not being—able to define base abstract modules without having to use the @Module annotation (because in fact, it is currently possible to create such code using the current capabilities of Dagger 2; otherwise it would not really make sense to even mention/discourage it in the documentation—except maybe, to justify design decisions made by the Dagger team).

**Comment by ronshapiro** [comment]
> Being able to define base module classes (which are not actual modules) would undoubtedly allow you to reuse many parts of your dependency graph (otherwise you might find yourself having to define the same dependency subgraph over and over again for different implementation and/or subtypes of certain components)

What about `@Module(includes = ...)`? That easily allows you to reuse modules without needing to depend on parts of the java type system for this.

**Comment by cesar1000** [comment]
I mentioned that it's not a good practice precisely for the reasons stated in the dagger documentation: inheritance forces you to defined the dependencies required by all your implementations in your base class. In a majority of cases, this will just not work. The alternative of defining different components for your application and tests works around this issue without the need to use inheritance. Using includes, as Ron suggests, allows you to reuse full portions or your graph. You just need to collect providers that you want to override in test in separate modules, so that you can replace them in your test component.

I used inheritance originally and ran into all this issues. I switched to using test components and additive modules with include, and removed all uses of inheritance without a need for much more boilerplate.

**Comment by RodrigoQuesadaDev** [comment]
@ronshapiro I'm mostly talking about generic base classes, that's why @Modules(includes = ...) wouldn't work.

@cesar1000 My current approach to testing seems to coincide with the advice given on Dagger's documentation regarding that matter. Also:

> ...and that is absolutely not related to being—or not being—able to define base abstract modules without having to use the @Module annotation...

**Comment by cesar1000** [comment]
@RodrigoQuesadaDev I'm just wondering - why do you need inheritance at all if not to override providers? That's against the recommendation in the documentation (where it says "don't do this!"). It works - I just said it's not a good practice because of these reasons.

My original question, in any case, was not about whether you should use inheritance or not. I just wondered why it was a problem to annotate a base class with @Module.

**Comment by RodrigoQuesadaDev** [comment]
@cesar1000 you don't necessarily want to be able to override a provider method (whether you think it is appropriate or not) for an abstract base module to be useful; you can, for example, define useful generic provide methods that that are not abstract in that base class/interface (using default methods in the case of interfaces).

**Comment by cesar1000** [comment]
@RodrigoQuesadaDev if you only need to provide generic provide methods, `@Module(includes = ...)` will do the trick.

**Comment by RodrigoQuesadaDev** [comment]
@cesar1000 Unfortunately that's not true, Java doesn't allow generic class literals (you know, because of the way type erasure works). So you would not be able to have, let's say, this kind  of code: `@Module(includes = IHateBoilerplateCode<ConcreteType>)`

**Comment by cesar1000** [comment]
Ah, that's one interesting case. You can still add an empty class that just extends that module. In which case, annotating the case class as a `@Module` wouldn't hurt? Does dagger allow that?

**Comment by theapache64** [comment]
Any updates on this issue ?

**Comment by netdpb** [comment]
I feel like this turned into a conversation about inheritance vs. composition for modules, which is interesting, but I don't see why it's a problem to add `@Module` to a class when there's a Dagger binding method. @JakeWharton's original comment was maybe made before abstract modules could be used themselves via static `@Provides` methods or things like `@Binds`.
