### ISSUE TITLE
Wrong class name in test supertypeMembersInjection

### ISSUE THREAD

**Issue by h908714124** [google/dagger#3043]
In `MembersInjectionTest.supertypeMembersInjection`:

```
JavaFileObject expectedMembersInjector =
    JavaFileObjects.forSourceLines(
        "test.AllInjections_MembersInjector",
        "package test;",
        // ...
        "public final class B_MembersInjector implements MembersInjector<B> {",
        "  private final Provider<String> sProvider;",
        "",
        // ...
```

It looks like the class name in line 3 should be `B_MembersInjector`, not `AllInjections_MembersInjector`.
Why isn't this test failing? Is it ignored?

**Comment by bcorso** [comment]
> Is it ignored?

If you mean the test, no it is not ignored.

> Why isn't this test failing?

I don't think there's any validation between the file name and the class name when creating a JavaFileObject.

The only validation is by the javac compiler, which enforces that public classes must match their file name. However, this class isn't being compiled, so there's no error. It's only used to check the generated code.

We should probably fix this just to avoid confusion, but we can't really prevent regressions since there's nothing enforcing it.

**Comment by h908714124** [comment]
I think later compiler versions may start validating this, I get an error when running the test with Java 17

**Comment by h908714124** [comment]
same problem in `supertypeMembersInjection`

**Comment by bcorso** [comment]
Hmm, I think that's the one I fixed, no?

**Comment by h908714124** [comment]
oops yes sorry that's the one, looks like I fixed it twice 🤔
