### ISSUE TITLE
Application failed to build with IntuneSDK

### ISSUE THREAD

**Issue by bryancaray** [google/dagger#3122]
Hi i was having issue when building a application

I do have application that i am currently building with intune sdk. When trying to extend MAMApplication in Application layer. I was unable to build my app because in MAMAplication the oncreate function is declared final and hilt was trying to override it.

**Comment by Chang-Eric** [comment]
Thanks for the report. I'll send out a change to add a new annotation to control whether or not we try to inject the Application class for you in onCreate. The annotation will then let you decide when you want to inject the Application, if ever.

**Comment by bryancaray** [comment]
Hi would you able to ellaborate more on this?

**Comment by bcorso** [comment]
@bryancaray the issue is that Hilt currently needs to override `Application#onCreate()` so that it can inject the application (for the case where you have `@Inject` fields in your app that need to be injected). 

Eric's plan is to introduce a new annotation that will tell Hilt not to inject the application in `onCreate()`. Instead you will be responsible for calling `inject(this)` yourself. For example, it looks like `MAMApplication` might replace `onCreate()` with `onMAMCreate()`? If so, your application might look something this:

```
@CustomInjection // <- a new annotation that tells Hilt not to inject in onCreate
@HiltAndroidApp 
class MyMAMApplication extends MAMApplication {
  @Override
  public void onMAMCreate() {
    CustomInject.inject(this);  // <- Call CustomInject#inject() manually to inject where you want.
    super.onMAMCreate();
  }
}
```

Another thing we can look into is to avoid injecting altogether if your application doesn't currently have any `@Inject` fields or methods (not sure if this is your case or not). In this case, you wouldn't need to do anything different unless you later added `@Inject` fields to your application.

**Comment by Chang-Eric** [comment]
I just added the aforementioned annotation to control Application injection. It should be out with the next release.
