### ISSUE TITLE
UI testing doesn't work with NavHost using hiltViewModel

### ISSUE THREAD

**Issue by DreamSkyMXDan** [google/dagger#3129]
I am trying to run a simple UI test like below. The MainView uses NavHost to build the bottom navigation bar. When we use NavHost, we have to use hiltViewModel ([If your @HiltViewModel annotated ViewModel is scoped to the navigation graph, use the hiltViewModel composable function that works with fragments or activities that are annotated with @AndroidEntryPoint.](https://developer.android.com/jetpack/compose/libraries)) When we use hiltViewMode, running UI tests produces no results. 

```
private lateinit var mainScenario: ActivityScenario<MainActivity>

    @get:Rule(order=0)
    var hiltRule = HiltAndroidRule(this)

    @get:Rule(order = 1)
    val composeTestRule = createEmptyComposeRule()

    @Before
    fun setup() {
        hiltRule.inject()

        mainScenario = ActivityScenario.launch(Intent(ApplicationProvider.getApplicationContext(), MainActivity::class.java))
    }

    @After
    fun tearDown() {
        mainScenario.close()
    }


    @Test
    fun testMainLaunches() {
        composeTestRule.onNodeWithTag(MainTest).assertIsDisplayed()
    }
```

**Comment by Chang-Eric** [comment]
Can you include more specific information that indicates this is an issue in Hilt? A ViewModel isn't tied to any specific UI piece as it really is just a container object, so if your test isn't showing UI it is likely an issue with your logic. If you can root cause it to some misbehavior of the Hilt ViewModel that your logic depends on though we can take a look given more details.

**Comment by danysantiago** [comment]
Your `assertIsDisplayed` is failing because the Compose Test Rule knows nothing about the Activity launched since you are mixing Compose test APIs with non-Compose ones. specifically you should swap the `ComposeTestRule` and `ActivityScenario` and only use `createAndroidComposeRule<MainActivity >()`, see: https://developer.android.com/jetpack/compose/testing

Feel free to re-open if you do find an issue with Hilt ViewModel integration.
