### ISSUE TITLE
Dagger: name and documentation

### ISSUE THREAD

**Issue by RalphBergmannKMB** [google/dagger#3134]
Hello,

I'm writing on a Dagger clone for Dart. It works so far and now it's time to write good documentation and of course, find a good name for the library.

For Dart/Flutter there are a lot of plugins that are all doing some kind of dependency injection or service location: 
- inject
- injectable
- dependency_injection_flutter
- injector
- injectorio
- dartin
- injector_x
- dart_inject
- finject
- dm
- dependency_injector
- inject_it
- daggerito

All these dart + inject combinations are used and it's hard for me to find a good name :-(
So I'm wondering if I can use dagger itself as the name for my plugin.

Q1: Is it allowed to use Dagger as a name for a Dart plugin?

My library/plugin works more or less the same as this one. So the documentation would also be the same. Someone wrote good documentation on https://dagger.dev and I'm wondering if I can reuse it.

Q2: Can I use the documentation from https://dagger.dev and rewrite it for my Dart plugin?

**Comment by Chang-Eric** [comment]
I would avoid using Dagger as a name for your library since it is likely to cause confusion for people. There will probably need to be a lot redirects for issues when people go to the wrong project and ask questions and there will likely be confusion about ownership of the project. New people already get confused with Dagger 1 and Dagger 2 as well as with Hilt, so it'd probably be better to avoid all of that.

Feel free to link to our documentation if you think it is useful, but I would guess you would want to write your own docs anyway as even if features resemble or take inspiration from Dagger, there will likely be differences in how things work that you'll want to have documented anyway.

**Comment by RalphBergmannKMB** [comment]
Okay, I will try to find another name. Thank you for your answer.
