### ISSUE TITLE
Android section in documentation is weird

### ISSUE THREAD

**Issue by pyricau** [google/dagger#319]
I just noticed the Android section of the documentation: http://google.github.io/dagger/android.html

A few things strike me:

```
Even much of the advice in Effective Java is considered inappropriate for Android.
```

I don't believe this to be true. IMHO, this is only valid if you are an engineer on the Android core framework: they have good reasons to write Java code differently. Those reasons don't apply to app developers. They likely don't use DI anyway.

Android code written by app developers can and should use the good practices laid out in Effective Java.

Furthermore, this sentence is vaguely worded. Bad practices (if any) should be explicitly called out. I also don't see how this relates to Dagger.

```
In order to achieve the goals of both idiomatic and portable code, Dagger relies on ProGuard to post-process the compiled bytecode.
```

That's news to me. I didn't think there was anything specific related to ProGuard in Dagger. Unless I'm mistaken, this seems like it's meant to say "you can use ProGuard with Dagger". 

```
Moreover, Dagger has an explicit goal to ensure that the Java source that it generates is consistently compatible with ProGuard optimizations.
```

How could the generated code not be compatible with ProGuard optimizations?

**Comment by tbroyer** [comment]
> How could the generated code not be compatible with ProGuard optimizations?

Dagger 1 using class names in strings?

**Comment by gk5885** [comment]
@pyricau, sure, "much" is maybe a bit strong, but EJ2 is an excellent resource because it synthesizes a wealth of experience with both the language _and the platform_, but it obviously doesn't consider Android when it dispenses advice.  The point is that what is considered canon for the JVM _can_ be inappropriate for a mobile platform (Android or otherwise) and we have to take that under consideration and make sure that we are serving both platforms well rather than just _assuming_ what is good for the JVM is _always_ good for mobile.

Anyway, the whole point of this page was to state that by and large the code that Dagger generates will look like typical, idiomatic Java, but that we rely on ProGuard to turn it into something that is often quite different.  There's some weird holy war brewing about how developers write code and this has nothing to do with that.  There is no prescription for how _you_ should write _your_ code, but a statement about how Dagger writes _its_ code and what assumptions are made about the conditions under which we expect it to be most effective and performant.  Or rather, if you have performance concerns on Android, but _are not_ using ProGuard, that will always be the first requirement before any change to the framework is considered.

@tbroyer has identified one of the primary pain points, but there are a variety of ways in which you can structure your code that will help or hurt how well ProGuard can optimize it.  A simple example is whether or not a method is short enough to be inlined.  On the JVM, I doubt anybody would really bother to consider whether a method was short enough for hotspot inlining, but when the method count can be a commodity, it's worth keeping an eye on.  We're still going to make methods where we feel that it's appropriate from a structural/organizational perspective, but in a way that doesn't tax our users.

**Comment by pyricau** [comment]
Thanks! That's a really good answer. I think what's missing in that doc is the details that you just outlined.  You wrote it in a much clearer way. When I read `Dagger relies on ProGuard to post-process the compiled bytecode.`, I understand `you have to use ProGuard`, when it's in fact the other way round: `if you use ProGuard, the Dagger generated code will benefit from all ProGuard optimizations`
