### ISSUE TITLE
This field leaks a context object

### ISSUE THREAD

**Issue by Morons** [google/dagger#3253]
I found "**This field leaks a context object**" whan I try to Inject Contecxt into ViewModel (Code Below)
How can this be safely done? There is many functions in Kotlin/Android that does need Context to work
```kotlin
@HiltViewModel
class AddEditRewardViewModel @Inject constructor(
	@ApplicationContext private val context: Context, // <<<<<< This field leaks a context object
	savedStateHandle: SavedStateHandle,
	private val rewardDao: RewardDao
) : ViewModel() {
```
I actually dont see the supposed Leak, when inspecting, but it need to be fixed/amended, me thinks

```
buildscript {
	ext {
		hilt_version = "2.40.5"
		hilt_extension_compiler = '1.0.0'
		hilt_lifecycle_viewmodel = "1.0.0-alpha03"
}

	// Dagger Hilt
	implementation "com.google.dagger:hilt-android:$hilt_version"
	kapt "com.google.dagger:hilt-compiler:$hilt_version"
	implementation "androidx.hilt:hilt-lifecycle-viewmodel:$hilt_lifecycle_viewmodel"
	implementation "androidx.hilt:hilt-compiler:$hilt_extension_compiler"
	implementation "androidx.hilt:hilt-navigation-compose:$hilt_extension_compiler"
```

**Comment by dmapr** [comment]
If you *must* have a context in a view model, you're supposed to use `AndroidViewModel` instead of `ViewModel` as the base class. Then you can change your constructor so that context is just a parameter (`@ApplicationContext context: Context`) and then invoke super as `AndroidViewModel(context as Application)` (not sure if that holds true in tests, but it will work in the app itself because that's what the application context is bound to). 
On a personal note I've never been in a situation where I *had* to have a Context in a ViewModel — so I never had to use an `AndroidViewModel`.

**Comment by Chang-Eric** [comment]
I think it'd be safe to suppress that warning too since I think the Lint check just doesn't know that it is the Application context and not some other context. It should be safe since there really isn't a leak here.
