### ISSUE TITLE
Add some lifecycle component as default binding to ViewModelComponent

### ISSUE THREAD

**Issue by jd565** [google/dagger#3310]
We would like to be able to inject a ViewModel with an Rx Scheduler that is created for the view model, and is shutdown when the ViewModel is cleared.

Right now we can inject a factory and pass the view model to the factory when creating the scheduler which can do the required operations.

It would be cleaner and nicer if we could just inject the scheduler directly, and the ViewModelComponent can inject either the view model itself (though this seems like it would cause a circular dependency) or an interface that lets you register a listener for when the ViewModel is cleared.

**Comment by Chang-Eric** [comment]
I think we can provide something like this once https://issuetracker.google.com/206789617 makes to stable. We might need to rename our current `ActivityRetainedLifecycle` to have a more generic name though.

**Comment by jd565** [comment]
Is this something you would accept a PR for?
My thinking being:
- Rename `ActivityRetainedLifecycle` to `ComponentLifecycle`
- Add componentLifecycle to ViewModelComponentBuilder
- Create a ComponentLifecycle instance and pass it to the component builder in HiltViewModelFactory
- When the view model is created add the ComponentLifecycle instance to the closable group, and when it is closed pass that to all the listeners
- Update documentation to reference the ComponentLifecycle as an injectable item in the view model scope

**Comment by Chang-Eric** [comment]
Just to clarify, this would be a PR after that API goes stable? Since I think that is still a requirement. For the PR though, while I do really appreciate the offer and those changes are the changes that would need to be done, unfortunately the way our tools are setup makes it hard for us to take large PRs from outside the team. This is something we will do though once that API is stable though.
