### ISSUE TITLE
Can't use @Inject and @AssistedInject together

### ISSUE THREAD

**Issue by risalfajar** [google/dagger#3351]
The goal is to inject a class with an optional constructor parameter.

If using @Inject the class will be created without the optional parameter, while if I want to pass the optional parameter I can use a factory @AssistedFactory.

I am trying to achieve it like this:
```kotlin
class ClassName @AssistedInject constructor(
    private val database: FirebaseFirestore,
    private val functions: FirebaseFunctions,
    @Assisted private val division: String?
) {

    @Inject constructor(
        database: FirebaseFirestore,
        functions: FirebaseFunctions
    ) : this(database, functions, null)
}
```
But it throws an error when I am injecting ClassName without using a factory
```
error: Dagger does not support injecting @AssistedInject type, ClassName. Did you mean to inject its assisted factory type instead?
```
How can I achieve the goal above? Any help is much appreciated

**Comment by bcorso** [comment]
Hi @risalfajar, you can't use `@AssistedInject` and `@Inject` together, but you can provide a [qualified version](https://dagger.dev/dev-guide/#qualifiers) of the type via a Dagger module. 

Given that an `@AssistedInject` type is meant to be created via a factory, the qualifier can help users distinguish what's special about the non-factory version, e.g. in your case maybe`@NoDivision`?

**Comment by risalfajar** [comment]
@bcorso yes there are workarounds, thank you. But I wonder if this can be added as a feature request?

**Comment by bcorso** [comment]
We currently view this as working as intended. In particular, the `@Inject` is being used to define defaults for your assisted parameters, but the `@Inject` approach is pretty limiting because it only allows one set of defaults and it's not clear to the user what defaults they're actually getting. 

Using a qualifier or factory creator method allows you to better describe to the users of that type what defaults they're getting and is more flexible to allow multiple sets of defaults. Sorry, I hope that makes sense.

**Comment by risalfajar** [comment]
Yes, that makes sense to me. Thanks for the explanation!
Closing this.
