### ISSUE TITLE
R8 - ClassCastException because of removed EntryPoint HiltWrapper_ classes

### ISSUE THREAD

**Issue by abd3lraouf** [google/dagger#3386]
R8 is failing on a release build and working normally on debug.

```bash
Caused by: java.lang.ClassCastException: Cannot cast somepackage.DaggerDemoApplication_HiltComponents_SingletonC to somepackage.r.f
...
at dagger.hilt.android.EntryPointAccessors.fromApplication(EntryPointAccessors.java:35)
at somepackage.someclass.onCreate(someclass.java:1)
```

```kt
EntryPointAccessors.fromApplication(
      context.applicationContext,
      CustomEntryPoint::class.java
    )
```

and After Decompiling the application found out that ` DemoApplication_HiltComponents$SingletonC` doesn't implement the `HiltWrapper_CustomEntryPoint` class it's removed completely from the class signature. And it does appear on debug builds.

**Comment by abd3lraouf** [comment]
Thank you @danysantiago for your response, really appreciate your help.

Actually was working on a project trying to reproduce the issue for you and nearly found it.

The main issue is that hilt cannot work with libraries, meaning I cannot generate a release aar build (minification enabled) as it needs an application that will be provided later by library users.

I'm just curious if there is something else we can do about it.

**Comment by abd3lraouf** [comment]
@danysantiago I've created the application to reproduce the issue

https://github.com/abd3lraouf/DaggerReleaseIssue

**Comment by danysantiago** [comment]
Thanks for the repro!

The issue is not with Hilt itself but just with the nature of minification, by shrinking a library and not the final APK you need to add rules to keep your public APIs since from R8's perspective, many classes, including the SDK APIs are not used and will get removed. I [see the project already has a rule for classes in your package](https://github.com/abd3lraouf/DaggerReleaseIssue/blob/master/sdk/consumer-rules.pro#L4) but with code generating libraries like Dagger and Hilt you need to also consider the generated classes and specifically keep those too.

Hilt for example, generates various metadata classes in a special package called `hilt_aggregated_deps`, which is used to pass information across compilations and get aggregated into the 'root' where Dagger components are generated. So in order to create a consumable SDK that uses Hilt and is minified, you'll need to add a rules for the generated classes: `-keep class hilt_aggregated_deps.** { *; }`.

Note that this is a general trade-off when minifying or obfuscating a library, you need to verify the produced library has its public API as desired, including generated code, where as if R8 is run in the app, then it can figure out what is being used from the app and remove unnecessary code, including code from consumed libraries.
