### ISSUE TITLE
@HiltAndroidApp base class must extend Application error after update to Dagger Hilt 2.42

### ISSUE THREAD

**Issue by satoshun** [google/dagger#3400]
When update hilt version 2.41 to 2.42 fails build with error message.

```
~/g/g/s/dagger-2.42-libapplication ❯❯❯ ./gradlew installDebug
Configuration on demand is an incubating feature.

> Task :app:hiltJavaCompileDebug FAILED
error: [Hilt]
  @HiltAndroidApp base class must extend Application. Found: com.example.mylibrary.Hilt_MyApplication
  [Hilt] Processing did not complete. See error above for details.
1 error

FAILURE: Build failed with an exception.
```

This project has Application class into library module (not application module). 

```kotlin
// success 2.41, but failed 2.42

// define into library module
@HiltAndroidApp
class MyApplication : Application()
```

If This Application class move to application module, the build will succeed.

```kotlin
// application module
@HiltAndroidApp
class MyApplication : Application()
```

it's expected behavior on 2.42?

---

sample project: https://github.com/satoshun-android-example/dagger-2.42-libapplication

**Comment by bcorso** [comment]
Hi @satoshun, Thanks for reporting this.

You're right that the Hilt application class must be located in the Gradle application module when you're using the [Hilt Gradle plugin](https://dagger.dev/hilt/gradle-setup#hilt-gradle-plugin).

As for why your build started failing when upgrading to 2.42, I'm not sure. However, due to the mechanics of the Hilt Gradle plugin it's not something that we can really guarantee will work except at the Gradle application module level, so you should definitely move it.

I'll update the documentation to make this explicit.

We can also look into automating this check so that it will automatically detect and fail when the application class is not defined in the Gradle application module.

**Comment by satoshun** [comment]
Thanks for replying. It was a great help.

I understand this behavior.

**Comment by zhlinh** [comment]
Encounter the same problem, cause a project contains multiple android.applications to publish different apps, but the share the same BaseApplication which in android.library that can be shared with multiple android.applications.

Is there a solution to handle this situation?

**Comment by bcorso** [comment]
Hi @zhlinh, 

You should be able to declare your `BaseApplication` (not annotated with `@HiltAndroidApp`) in an `android.library` Gradle module, and then each `android.application` Gradle module will have its own `@HiltAndroidApp`-annotated application class that extends `BaseApplication`.

**Comment by kuanyingchou** [comment]
A more explicit error message will be included in the next release when an Application annotated with @HiltAndroidApp
is not defined in an application module. Closing this one.
