### ISSUE TITLE
Could not find Application in Service 

### ISSUE THREAD

**Issue by St4B** [google/dagger#3431]
In a `Service` implementation, we have a code similar to the following: 
```kotlin
@EarlyEntryPoint
@InstallIn(SingletonComponent::class)
interface ServiceEntryPoint {
    fun getFoo(): Foo 
}

private val foo: Foo by lazy {
    EarlyEntryPoints.get(this, ServiceEntryPoint::class.java).getFoo()
}
```

Usage of `EarlyEntryPoints` was probably a misconfiguration. I do not remember if it was a hacky way to make our tests pass.

After bumping dagger to `2.42`, we have runtime crashes. These crashes can be fixed if we changed the code to something like that:
```kotlin
@EarlyEntryPoint
@InstallIn(SingletonComponent::class)
interface ServiceEntryPoint {
    fun getFoo(): Foo 
}

private val foo: Foo by lazy {
    EarlyEntryPoints.get(applicationContext, ServiceEntryPoint::class.java).getFoo()
}
```
The problem was introduced in this [commit](https://github.com/google/dagger/commit/d14a3d636fddd73d5375e417548e3ed1d8017849), because `.getApplicationContext()` is not called anymore. Is this on purpose, or do we need to safeguard against it? It is not an issue for us though , as we changed `@EarlyEntryPoint` to ` @EntryPoint`.

**Comment by Chang-Eric** [comment]
This is intentional since the documentation of the method is that you should be passing us the application context. https://github.com/google/dagger/blob/master/java/dagger/hilt/android/EarlyEntryPoints.java#L39 Our previous calling of `getApplicationContext()` was technically unnecessary, but I guess worked to cover up the issue where you passed us the Service context instead of the Application context. We had to remove the call due to the particulars of that issue. We probably should have anticipated this causing an issue for people currently passing in the wrong context and highlighted that in our release note.
