### ISSUE TITLE
Hilt - Dagger SPI plugins are not called since 2.40 due to flipping of `enableAggregatingTask` to `true` by default

### ISSUE THREAD

**Issue by arunkumar9t2** [google/dagger#3464]
`BindingGraphPlugin.visitGraph()` is not called in hilt since 2.40 but worked till 2.39.1. Disabling `enableAggregatingTask` manually via gradle extension fixes the issue.

Repro https://github.com/arunkumar9t2/dagger-spi-issue

**Comment by danysantiago** [comment]
Thanks for the sample app! If you need a workaround and are willing to have some Gradle script workaround then you can add the SPI plugin dependency to the annotation processor path of the JavaCompile task that Hilt creates when aggregation is turned ON.

You can do this by first creating a config where you'll put the SPI plugins, then find the task and add it to the processor path, in your sample project it would be like this:
```
configurations {
    spiPlugins
}

dependencies {
    spiPlugins project(":spi-plugin")
}

project.afterEvaluate {
    project.tasks.withType(JavaCompile)
            .matching { it.name.contains("hiltJavaCompile") }
            .configureEach {
                it.options.annotationProcessorPath += project.configurations.getByName("spiPlugins")
            }
}
```
But note that translating to a bigger project might be trickier if for example you have configuration caching turned on.

**Comment by arunkumar9t2** [comment]
Great thanks for sharing that. Fortunately I have been using a gradle plugin to ship my SPI plugin so I could include this fix for hilt versions this issue appears. I will have to investigate to make this config cache compatible.

**Comment by LeonRa** [comment]
Just want to touch base here, as it looks like this ticket is now closed. SPI plugins still don't appear to work with the aggregating task on in 2.43.2, though I can confirm that the suggested workaround works for me. I used Arunkumar's sample above to reproduce in isolation. Are things working as expected or is a fix expected in the future?

**Comment by danysantiago** [comment]
Hey, thanks for checking, looks like the Hilt Gradle plugin is not correctly finding the `kapt` configurations even though we added [a way to find those via name](https://github.com/google/dagger/blob/master/java/dagger/hilt/android/plugin/main/src/main/kotlin/dagger/hilt/android/plugin/HiltGradlePlugin.kt#L405).

You might be able to workaround this by declaring the SPI Plugin in the `annotationProcessor` config too: `annotationProcessor project(":spi-plugin")`, which then we'll be correctly used since [AGP takes care of making the config accessible per variant](https://github.com/google/dagger/blob/master/java/dagger/hilt/android/plugin/main/src/main/kotlin/dagger/hilt/android/plugin/HiltGradlePlugin.kt#L404).

I'll try to fix the issue for KAPT plugins.

**Comment by LeonRa** [comment]
Thanks so much @danysantiago!

**Comment by LeonRa** [comment]
Hi @danysantiago, just double-checking if there has been any progress here since August, or if another workaround available. Currently seeing the following error:
> 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts

**Comment by danysantiago** [comment]
Hey - Sorry for dropping this and taking soo long, I was able to find cause and created a change: https://github.com/google/dagger/pull/3759

The warning is a false positive, indeed if you only have `annotationProcessor` then during normal KAPT processing the SPI plugin will be missed, but if you have both it should be fine as a workaround, since during KAPT the `kapt` one will be picked up, while during `hiltCompile` the `annotationProcessor` will be discovered, however the KAPT plugin doesn't know this and produces the warning.

Once the fix lands, using only `kapt` should work.

**Comment by LeonRa** [comment]
No problem about the delay, life happens! Thank you for the additional background and the fix 🙏
