### ISSUE TITLE
Subcomponents require public constructors on pure-static modules

### ISSUE THREAD

**Issue by tadfisher** [google/dagger#348]
Example:

``` java
@Module
class MyModule {
    @Provides
    static String provideStaticDependency() {
        return "a static dependency";
    }

    private MyModule() {
        throw new UnsupportedOperationException("No instances!");
    }
}

@Subcomponent(modules = MyModule.class)
interface MySubComponent {
    String staticDependency();
}

@Component
interface MyComponent {
    MySubComponent subComponent();
}
```

Dagger complains:

```
error: MySubComponent requires modules which have no visible default constructors. Add the following modules as parameters to this method: MyModule
    MySubComponent subComponent();
                   ^
```

If I make the module constructor `public`, it solves the warning, but the generated code never calls that constructor (as is evidenced by the fact that my application never crashes).

**Comment by JakeWharton** [comment]
That warning is also incorrectly worded.

**Comment by JakeWharton** [comment]
Er, I guess it's ambiguously worded. The indirect object is what the
default constructor constraint is applied to. On my first read it sounded
like the direct object, the subcomponent, required no visible default
constructors which makes no sense.

**Comment by gk5885** [comment]
Oh, interesting.  I suppose that private constructors on modules with only static `@Provides` methods makes perfect sense and follows normal Java convention, but for whatever reason we just never thought to do it.  I completely agree that it's a bug though.

**Comment by gabrielittner** [comment]
Also happens for abstract modules which only have `@Binds` methods.

**Comment by mzgreen** [comment]
Right I've also encountered that. My usecase was this:

```java
@SomeScope
class SomePresenter implements Presenter {
    @Inject 
    public Repository repository;

    @Inject
    public SomePresenter() {}
}

//and then
public FooActivity extends Activity {

    @Inject
    Presenter presenter; // I want this to be SomePresenter
                         //  but it's impossible when using constructor
                        // injection in SomePresenter

    @Override
    public void onCreate() {
        getComponent().inject(this);
    }

}
```

So I thought that it would work if I would keep constructor injection and add a module with `@Binds` to tell Dagger what it should inject. But as I'm using subcomponents it's not possible to use `@Binds`. The documentation says that `@Binds methods are a drop-in replacement for Provides methods that simply return an injected parameter. `
So I've tried to keep constructor injection and at the same time provide it in my `Module` class. But this doesn't seem to work. It compiles but it crashes at runtime saying that it could not inject `Repository` to the `SomePresenter`. I guess that `@Binds` works a little bit different than `@Provides` returning an injected parameter and the documentation is wrong.

After all my only choice was to remove constructor injection and provide `SomePresenter` using only `@Provides` method in a standard `Module`. I don't like it because it forces me to write more boilerplate.
Is there any chance for improvements here anytime soon?

**Comment by tadfisher** [comment]
@mzgreen What if you tried:

```java
@Inject
public SomePresenter(Repository repository) {
  this.repository = repository;
}
```

**Comment by mzgreen** [comment]
@tadfisher It won't work if I remove an additional `Module` saying which instance to provide when someone requests `Presenter` object.

I tried to remove all dependencies from `SomePresenter` like this:

```java
@SomeScope
class SomePresenter implements Presenter {

    @Inject
    public SomePresenter() {}
}

//and then
public FooActivity extends Activity {

    @Inject
    Presenter presenter; 

    @Override
    public void onCreate() {
        getComponent().inject(this);
    }

}
```

And it didn't work because Dagger can inject only `SomePresenter`. If I would request `SomePresenter` instead of `Presenter` in `FooActivity` then it would work but that's not what I want to achieve.

**Comment by tadfisher** [comment]
@mzgreen Right, that's a separate issue from this one. If you are injecting an interface, a module has to exist which provides a dependency of that type. Otherwise Dagger can not know which implementation of that interface to use (well, it *could* if there is only a single implementation in scope, but that's not related to this issue).

**Comment by mzgreen** [comment]
@tadfisher I guess it's related because `@Binds` would help in this case but it's not possible to use in subcomponent.

I found a temporary fix:

```java

@Module
public class SomeModule {

    @SomeScope
    @Provides
    public static Presenter providePresenter(SomePresenter somePresenter) {
        return somePresenter;
    }
}

**Comment by tadfisher** [comment]
You'd still need a module with a `@Binds` method, so you wouldn't be able to elide the module entirely.

In any case, this issue is specifically about a compiler error when including a restricted constructor, so the problem you describe should probably be a separate issue.

**Comment by hzsweers** [comment]
![image](https://cloud.githubusercontent.com/assets/1361086/21469057/06d00666-c9ec-11e6-9e54-3c8b1c90da5b.png)

**Comment by gk5885** [comment]
Hey, thanks for the bump.  I was actually working on this just the other day because it was annoying me too and we should have fix for the next release.

**Comment by ronshapiro** [comment]
@gk5885 did you ever get to this one?

**Comment by styler1972** [comment]
I was incredibly angy at this until I found that it went away after cleaning my project.  Moral of the story, clean project early in troubleshooting.

**Comment by sophiataskova** [comment]
Bump!

**Comment by ronshapiro** [comment]
Just tested this out, and we don't require this anymore. It may be recent, so wait for the 2.22 release if it's not working in 2.21
