### ISSUE TITLE
Dagger/kapt fails when a component factory has a function named "create" (other names work)

### ISSUE THREAD

**Issue by Rubydesic** [google/dagger#3512]
Repository to replicate: https://github.com/Rubydesic/DaggerBrokenCreateMethod.

Minimum reproducible example:

```kt
class BrokenComponent @Inject constructor() {
    @Component
    interface Factory {
        fun create(): BrokenComponent
    }
}
```

Kapt will completely die while processing this unless the function is renamed to something other than "create"

The error message is also extraordinarily unhelpful: 
```
> Task :kaptKotlin FAILED
2 actionable tasks: 1 executed, 1 up-to-date
error: Cannot override generated method: Factory.create()

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kaptKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
```

Even more perplexingly, this pattern works fine if the component has a module that needs to be instantiated:

```kt
class WorkingComponent @Inject constructor(val a: Int) {

    @Singleton
    @Component(modules = [WorkingComponentModule::class])
    interface Factory {
        fun create(): WorkingComponent
    }

    @Module
    class WorkingComponentModule(@get:Provides val a: Int)
}
```

**Comment by Chang-Eric** [comment]
Thanks for this report. This is a case of the error message being extremely unhelpful. I'll send a change to clarify it.

What is going on here though is that Dagger is going to reserve some key methods like "create" and "builder" so you can actually get an instance of our generated component. In your case, I think there is some extra confusion too based on the naming, but you're actually just defining regular getters for bindings since `BrokenComponent` and `WorkingComponent` aren't actually the component, they are just `@Inject` classes and the actual component is `Factory`.

So Dagger is trying to reserve a method `create` that returns Factory on our generated implementation. It works when you have a module that needs to be instantiated because in those cases we generate a `builder` method instead to take the module.
