### ISSUE TITLE
`Lazy` injection fails through inheritance

### ISSUE THREAD

**Issue by romainpiel** [google/dagger#3564]
Using Dagger version `2.42` with `kapt`.

When I define a lazy field like:

```kotlin
abstract class Parent {
   @Inject lateinit var foo: Lazy<Foo>
}

class Child @Inject constructor(): Parent() {
}
```

`kapt` fails with the error:
```
error: [Dagger/MissingBinding] dagger.Lazy cannot be provided without an @Provides-annotated method
```

I've also tried switching `Lazy` by `Provider` and got the same error.
Defining `@Inject lateinit var foo: Lazy<Foo>` in `Child` works as expected.
I also tried with `ksp` and it works as expected.

Have we seen this issue before?

**Comment by bcorso** [comment]
> error: [Dagger/MissingBinding] dagger.Lazy cannot be provided without an @Provides-annotated method

Is this the exact error message?

Even if `Lazy<Foo>` was a missing binding, Dagger should be reporting the missing binding as `Foo` rather than `dagger.Lazy<Foo>` or just `dagger.Lazy`.

This error makes me think that you may have the wrong `Lazy`. Can you double check that you're not actually using `kotlin.Lazy` (which is the default if you don't import `dagger.Lazy`).

If you are using `dagger.Lazy` can you provide a repro project demonstrating this behavior? I tried locally and could not reproduce it.

**Comment by romainpiel** [comment]
👋 Thanks for your quick reply!

> Is this the exact error message?

Yes 👍 

> Even if Lazy<Foo> was a missing binding, Dagger should be reporting the missing binding as Foo rather than dagger.Lazy<Foo> or just dagger.Lazy.

If I replace the injection by `@Inject lateinit var foo: Foo`, `foo` gets injected just fine so I don't think there's an issue with the injection of `Foo` itself. I think the error is clear that it cannot inject the `dagger.Lazy` type here.

> This error makes me think that you may have the wrong Lazy. Can you double check that you're not actually using kotlin.Lazy (which is the default if you don't import dagger.Lazy).

I'm definitely using `dagger.Lazy` (and the error is also clear about that).

> If you are using dagger.Lazy can you provide a repro project demonstrating this behavior? I tried locally and could not reproduce it.

I can try to do that 👍

**Comment by romainpiel** [comment]
I can't reproduce the issue on a small project either. I'm not sure what going on in my project. I'm going to close this issue until I find a good way to reproduce.
