### ISSUE TITLE
Why does the dagger.dev documentation about "Adding a subcomponent to a parent component" wrap the subcomponent builder in a Provider?

### ISSUE THREAD

**Issue by stoyicker** [google/dagger#3652]
I was fiddling with this functionality yesterday and figured that the subcomponent builder can be asked for directly. Not only that but, because it is mandatory for the subcomponent to have a builder, I see little reason to ever want to ask for a Provider of the builder. Therefore this ends up just cluttering the example unnecessarily. Am I missing something or can/should this be simplified?

**Comment by bcorso** [comment]
When building multiple, independent instances of a component it usually doesn't make sense to use the same builder instance because you can leak state between calls to `.build()`.

For example (reusing a similar example from the docs):

```java
class RequestRouter {
  private final Provider<RequestComponent.Builder> componentProvider;

  @Inject 
  RequestRouter(Provider<RequestComponent.Builder> componentProvider) {
    this.componentProvider = componentProvider;
  }

  void dataReceived(Data data) {
    RequestComponent component = componentProvider.get().data(data).build();
  }

  // Without "Provider" the "config" passed here will leak into the next call to #dataReceived().
  void dataReceivedWithConfigs(Data data, Config config) {
    RequestComponent component = componentProvider.get().data(data).config(config).build();
  }
}
```

Calling `#dataReceivedWithConfigs()` followed by `#dataReceived()` will leak the `config` instance.

**Comment by stoyicker** [comment]
fair point. thank you very much!
