### ISSUE TITLE
"Every type annotated with @Component must contain at least one abstract component method." in Component documentation seems incorrect?

### ISSUE THREAD

**Issue by WhosNickDoglio** [google/dagger#3833]
I was reading through the java docs for some of the Dagger annotations and noticed the following line in [the documentation for `@Component`.](https://dagger.dev/api/latest/dagger/Component.html)

> Every type annotated with `@Component` must contain at least one abstract component method.

Maybe this is out of date or I'm not understanding it correctly but this is wrong right? I've written many `@Components` that don't have any methods.

**Comment by bcorso** [comment]
> Maybe this is out of date or I'm not understanding it correctly but this is wrong right? I've written many @Components that don't have any methods.

Hmm, in Java, if you don't have any abstract methods then the generated Dagger component literally does nothing for you. However, I can see how this would be confusing if you're writing Kotlin source (I'm guessing this is your case?) since that documentation is specifically talking about Java source. 

In Kotlin, Dagger allows abstract `val`/`var` in your components if you're using Kotlin, but note that this is more happenstance than a purposely supported feature. In particular, KAPT translates your Kotlin source into Java stubs for annotation processing and each abstract `val` will translate to an abstract getter method in the Java stub and each abstract `var` will translate to an abstract getter and setter method in the Java stub. Thus, from Dagger's perspective it's still only processing abstract methods.

In general, even in Kotlin, I would still only use `fun` in your components for two reasons. First, `var` ends up generating both a getter and a setter which is valid to Dagger but is probably not what you intended. Second, and the most important reason is that Dagger can miss qualifiers on your `val`/`var` properties depending on where the KAPT puts the qualifier on the Java stub, which can lead to confusing error messages or even getting the wrong binding if you have both a qualified and unqualified bindings available in your graph.
