### ISSUE TITLE
Support scala in dagger

### ISSUE THREAD

**Issue by toandaominh1997** [google/dagger#3856]
I have meet this error when build Component on Scala. This is example how to use dagger 2.46.0 on scala
```scala
class MyDependency {
  def getHelloWorld: String = "Hello, world!"
}

class MyService @Inject()(dependency: MyDependency) {
  def sayHello: String = s"Service says: ${dependency.getHelloWorld}"
}
@Component
trait MyComponent {
  def myService: MyService
}
object Main extends App{

//  DaggerPCTRMain_MainComponent.create()
  val component = DaggerMyComponent.create()
  val myService = component.myService
  println(myService.sayHello)

}

```
Error: 
```
error: not found: value DaggerMyComponent
  val component = DaggerMyComponent.create()
                  ^
one error found
Build failed
java.lang.RuntimeException: Build failed
	at io.bazel.rulesscala.scalac.ScalacWorker.compileScalaSources(ScalacWorker.java:290)
	at io.bazel.rulesscala.scalac.ScalacWorker.work(ScalacWorker.java:61)
	at io.bazel.rulesscala.worker.Worker.persistentWorkerMain(Worker.java:86)
	at io.bazel.rulesscala.worker.Worker.workerMain(Worker.java:39)
	at io.bazel.rulesscala.scalac.ScalacWorker.main(ScalacWorker.java:25)
```
Anyone know the way to fix. Please let's me know. Thanks

Notes: 
- dagger 2.4.6
- scala 2.12.14

**Comment by Chang-Eric** [comment]
Unfortunately, we only plan to support Dagger with Java and Kotlin. I'm not that familiar with DI libraries available in Scala, but it'd be best if you found an alternative library to use for DI.

**Comment by abhandaru** [comment]
Our team would have also loved to leverage Dagger with Scala.

I know this issue is closed, but from my research so far, support seems feasible.
* Scala runs on the JVM and does support annotations
* Under the hood `scalac` supports a largely overlapping set of flags
* Previously I have used `guice` and other runtime injection strategies

Anyways, this is just here in case you reconsider. Thank you!
