### ISSUE TITLE
[Kotlin Usability] Equivalence between Optional<T> and T?

### ISSUE THREAD

**Issue by cable729** [google/dagger#3865]
I couldn't find an issue for this. Last time I checked, this didn't work. Simply put, it makes sense to have `T? == Optional<T>` from a user perspective. Is this something that Dagger can support?

```kt
@Module object WaterModule {
  @Binds val water: Water?
  @Binds val glass: Optional<Glass>
}

class Thirsty @inject constructor(
  val water: Optional<Water>,
  val glass: Glass?
)
```

**Comment by JakeWharton** [comment]
I'm not sure this would work since Dagger has support for nullable bindings which are separate conceptually from optional bindings. A nullable binding is a required binding that may contain a null value. An optional binding is, well, just that, a binding which may not exist.

There's actually missing functionality in Dagger which is that you cannot have an optional binding of a nullable value. This is not possible in Java because its `Optional` (and type system in general) lack the ability to model the presence of null. This is not possible in Kotlin either since nullability is not monadic like it is in languages like Swift.

**Comment by Chang-Eric** [comment]
+1 to Jake's explanation above. Going to close this since this isn't really possible as they are separate concepts.
