### ISSUE TITLE
Type BaseFragment_MembersInjector is defined multiple times:

### ISSUE THREAD

**Issue by yoobi** [google/dagger#3911]
Hello, I've defined a BaseFragment such as this

```
**in module common**
@FragmentScoped
abstract class BaseFragment<T: ViewBinding>(
    bindingInflater: (layoutInflater: LayoutInflater) -> T
): BaseFragment<T>(bindingInflater) {
     @Inject lateinit var toolbarManager: ToolbarManager
}

interface ToolbarManager {
    ....
}
-----
**in app module**
@Module
@InstallIn(FragmentComponent::class)
interface ToolbarModule {
    @Binds
    fun providesToolbarManager(impl: ToolbarManagerImpl): ToolbarManager
}
```

When I'm using this BaseFragment only once I've got not issue, but as soon as implements another Fragment with BaseFragment I'm getting the following error: `Type BaseFragment_MembersInjector is defined multiple times: ..` with the path of the 2 Fragment implementing it

I should add that my project is a multi-module one. Here is how this is organized:
- app (`ToolbarManagerImpl`)
- common (contains `BaseFragment` and `ToolbarManager`)
- features
    - a
        - ui (contains: `@AndroidEntryPoint class AFragment: BaseFragment`)
    - b
        - ui (contains: `@AndroidEntryPoint class BFragment: BaseFragment`)
        
common is implemented in `:app`, `:features:a:ui` and `:features:b:ui`

**Comment by bcorso** [comment]
This would normally happen if Dagger's compiler isn't running in the library containing the `BaseFragment` source. Please make sure that that library has a dependency for `annotationProcessor "com.google.dagger:dagger-compiler"` or `kapt "com.google.dagger:dagger-compiler"`.

Otherwise, Dagger will generate `BaseFragment_MembersInjector` in each library where an `@Component` needs the `BaseFragment_MembersInjector`, which sounds like what's happening in your case.

**Comment by yoobi** [comment]
Okay ! I was using `javax.inject:javax.inject:1` in `:common` I though it was enough, when adding hiltandroid and hiltCompiler it did work. Thank you!
