### ISSUE TITLE
Is there any visualization tool  to see the dependency graph of the project?

### ISSUE THREAD

**Issue by ScorpioNeal** [google/dagger#3954]
Or any plan to integrate a plugin in Android Studio.

**Comment by ScorpioNeal** [comment]
Thanks @danysantiago . But I'm much more wondering if official can provide such tools.

**Comment by Chang-Eric** [comment]
We've thought about providing such tools, and it is technically somewhere on our roadmap, but there are just way more high priority things for us to be spending time on so it is unlikely to really get any attention. Also, this kind of tool would significantly increase our maintenance burden since it is a really different area from the rest of Dagger being a UI tool. Given all that, and since the SPI allows other people to build these tools like the one linked above, I think it is unlikely we're going to try to do anything in this space in the near future.
