### ISSUE TITLE
gradle configuration error: "Failed to notify project evaluation listener." when applying hilt 2.47 and ksp plugin to same project

### ISSUE THREAD

**Issue by frett** [google/dagger#3965]
When upgrading the Dagger/Hilt 2.47 I get a gradle configuration error when both the hilt plugin and the ksp plugin are applied to the same project.

here is the full stack trace of the crash that occurs: [dagger stacktrace.txt](https://github.com/google/dagger/files/12052091/dagger.stacktrace.txt)

I'm using:
- Kotlin 1.9.0
- KSP 1.9.0-1.0.11
- AndroidX Room 2.5.2
- Hilt 2.47

I'm currently using KSP for Room and was still using KAPT for Dagger/Hilt until the KSP support is ready. Here is a link to the renovate PR upgrading Dagger & Hilt that is triggering the error: https://github.com/CruGlobal/godtools-android/pull/2989

See this comment for a solution for this issue: https://github.com/google/dagger/issues/3965#issuecomment-1662360344

**Comment by danysantiago** [comment]
This is interesting, its as if KSP is being applied but it is not in the build script classpath, the error is happening [here](https://github.com/google/dagger/blob/master/java/dagger/hilt/android/plugin/main/src/main/kotlin/dagger/hilt/android/plugin/util/Tasks.kt#L63). This same strategy is used in KAPT but the KAPT tasks are most certainly in the script classpath because they are bundled with the Kotlin Gradle plugin which tends to be applied everywhere.

Maybe it's a good idea is to declare the plugins to be used across your project in the main [`build.gradle`](https://github.com/CruGlobal/godtools-android/blob/develop/build.gradle#L18-L21) to avoid classpath issues. i.e. you can fix this by adding `alias libs.plugins.ksp apply false` in that plugin closure.

In the meantime I still need to investigate how come the KSP plugin can be applied but its tasks classes not available in the classpath for Hilt's plugin.

**Comment by frett** [comment]
I see, it's acting like some sort of layered ClassLoader issue. I was loading the hilt plugin in the root classpath (I had forgot I was actually doing this), then the subproject loaded the ksp plugin.  It's behaving like the the Hilt plugin is only looking in that parent ClassLoader without checking the subproject classloader for the classes.

I have enough to fix the issue on my end, but I'll leave this ticket alone so you can sort out anything you need to for Dagger.

**Comment by harry248** [comment]
We've got the same issue after upgrading to Hilt 2.47.

**Comment by danysantiago** [comment]
Wanted to add more clarification about this issue. We recently added support for the upcoming Hilt KSP in the Gradle Plugin (https://github.com/google/dagger/commit/843a6a2064e834ffb9482315b2de9190108773b0) but it is exposing Gradle class loader shenanigans.

Specifically if you have a setup where the Hilt plugin is declared at the root but KSP is only declared in sub-projects then the Hilt's plugin class loader is the root's which is the parent of the sub-project making it impossible to see the KSP plugin classes required to correctly configure the processor.
```
// Example
- root project: with Hilt
- subproject "app": with KSP
```
Two possible solution here:
* Declare both plugins at the root (without applying them) and apply them in the sub-projects.
* Declare both plugins in the sub-projects, and not the root.

**Comment by harry248** [comment]
Adding, but not applying KSP in the project level build.gradle.kts file fixed the issue for us. Thanks for the hint.

**Comment by vitamin33** [comment]
For me, the working workaround was - use 'ksp' for everything except Hilt. And change hilt version to specific version - 2.46.

**Comment by sdzshn3** [comment]
added the ksp in root gradle but not applied. Then applying in android gradle made it to work.

**Comment by danysantiago** [comment]
We've added a better error message when this issue occurs, there is nothing else we can do from our side as this is purely class loading behaviour in Gradle that we can't control from Hilt's plugin.

**Comment by rvenky125** [comment]
> added the ksp in root gradle but not applied. Then applying in android gradle made it to work.

it worked for me, thanks

**Comment by Sagar0-0** [comment]
Ksp with Hilt is the reason for this issue,
This worked for other places...
in module - ```id("com.google.devtools.ksp") apply false```
in project - ```id("com.google.devtools.ksp") version "1.8.10-1.0.9"```

**Comment by thenameisvijay** [comment]
If anybody facing this issue while migrating from kept to ksp, you need to "_Make sure that you choose a KSP version aligned with your project's Kotlin version._" [read more](https://developer.android.com/build/migrate-to-ksp). 
Below config worked for me
In module:
`val hilt_version = "2.48"`

In project:
```
id("org.jetbrains.kotlin.android") version "1.8.10" apply false //downgraded from 1.9.0 to 1.8.10
id("com.google.devtools.ksp") version "1.8.10-1.0.9" apply false
id("com.google.dagger.hilt.android") version "2.48" apply false
```

**Comment by Dkathayat** [comment]
`kotlin = "2.2.20"
kotlinKsp = "2.2.10-2.0.2"
hiltAndroid = "2.57.2"`

The KSP plugin was detected to be applied but its task class could not be found.

This is an indicator that the Hilt Gradle Plugin is using a different class loader because
it was declared at the root while KSP was declared in a sub-project. To fix this, declare
both plugins in the same scope, i.e. either at the root (without applying them) or at the
sub-projects.
