### ISSUE TITLE
[KSP] @receiver: site target qualifier annotations are not accounted for

### ISSUE THREAD

**Issue by ZacSweers** [google/dagger#3990]
The following code snippet fails in KSP due to Dagger missing the `@receiver:Marker` annotation on the `Foo` receiver.

This is with Dagger version 2.47.

```kotlin
@Qualifier
annotation class Marker

class Foo : Bar
interface Bar

@Module
abstract class BarModule {

  @Marker
  @Binds
  abstract fun @receiver:Marker Foo.bindsBar(): Bar

  companion object {
      @Provides 
      @Marker
      fun providesFoo(): Foo = Foo()
  }
}
```

```
e: Error occurred in KSP, check log for detail
e: [ksp] /var/folders/nv/96k28mh96ml0g6y4gxkpjfcw0000gn/T/Kotlin-Compilation17939627823284801045/sources/src/main/java/com/squareup/test/Source0.kt:6: [Dagger/MissingBinding] com.squareup.test.Foo cannot be provided without an @Inject constructor or an @Provides-annotated method.

Missing binding usage:
    com.squareup.test.Foo is injected at
        com.squareup.test.BarModule.bindsBar($this$bindsBar)
    @com.squareup.test.Marker com.squareup.test.Bar is requested at
        com.squareup.test.ComponentInterface.bar()
```

**Comment by bcorso** [comment]
Thanks! 

This was a bug in the [XProcessing library](https://github.com/androidx/androidx/blob/androidx-main/room/room-compiler-processing/README.md) where annotations on receiver parameters are accidentally being dropped, and it also uncovered a bug in KSP where the receiver annotations are missing for precompiled classes (https://github.com/google/ksp/issues/1488).

While we plan to get this fixed in KSP/XProcessing, I talked this over with the team and the consensus was that we will likely ban this type of usage in Dagger. It's really just another way to do the same thing you could do with a normal function:

```kotlin
@Marker
@Binds
abstract fun bindsBar(@Marker foo: Foo): Bar
```

While I could see why you might want to write it like that (it’s a clever way to reorder things so that it reads more like "Foo bindsBar Bar"), it also adds additional overhead to users because it's unclear why it works unless you understand that there's an implicit receiver parameter under the hood.

However, feel free to give thoughts and also let us know if there’s benefits to the extension function approach that we may have missed.

**Comment by ZacSweers** [comment]
I think my personal [LOGAF](https://blog.danlew.net/2020/04/15/the-logaf-scale/) is low as we rarely write explicit binds functions anymore in our project in favor of anvil's `@ContributesBinding` feature, but I do wonder about this bit

> it also adds additional overhead to users because it's unclear why it works unless you understand that there's an implicit receiver parameter under the hood.

I feel like it's actually safe to assume that users understand the receiver is the parameter, and that it is explicit? But maybe I'm overestimating how much people understand how Kotlin works 😅.

There is another added marginal benefit to this - no longer needing to put a throwaway parameter name.

I could see value in better supporting receivers in the future as kotlin is expanding this functionality with context receivers, but that's probably a bridge better crossed when they're available.

**Comment by Chang-Eric** [comment]
FWIW, when I think about the concept of an extension function, I think of it like it is adding a method to that class. So since we don't support a parameterless function to be a binds function in a class, it is kind of weird to me even though I know what is happening under the hood with the receiver parameter.

**Comment by bcorso** [comment]
As discussed above, the extension syntax for `@Provides`/`@Binds` methods was banned in https://github.com/google/dagger/commit/b37cffd6a9bb58c7bbe2f39f53b761168d5235fb.

This change will be included in the next release.
