### ISSUE TITLE
Circular dependency deadlock possibility

### ISSUE THREAD

**Issue by justiny1023** [google/dagger#4003]
Is it possible for Dagger to deadlock while providing for dependencies? For example, if there is a circular dependency between Class A and Class B because both inject each other like this:

```
class ClassA @Inject constructor(classB: Provider<ClassB>) {
   fun logSomeMetrics() {
      // ...
      classB.get().writeSomething();
      // ...
   }
}

class ClassB @Inject constructor(classA: Provider<ClassA>) {
   fun writeSomething() {
      // ...
      classA.get().logSomeMetrics();
      // ...
   }
}
```

The Provider<T> was used in each class to try to break the circular dependency. Is there ever a race condition or scenario where two threads will deadlock because one is trying to resolve dependency (lazily through `get()`) for Class A, while the other is trying to resolve dependency (lazily through `get()`) for Class B?

Or is it guaranteed that both dependencies will be resolved properly without deadlock?

**Comment by Chang-Eric** [comment]
This should work fine. With these objects as written, they are unscoped, so a new `ClassA` and `ClassB` will be be created anyway, so there isn't any locking, so there is no deadlock. Even with these as scoped objects though, there still isn't really a deadlock here because those methods aren't invoked in the constructor. Dagger only covers the constructor call with locks when scoped.

**Comment by justiny1023** [comment]
@Chang-Eric Thanks Eric. I failed to mention that these are indeed scoped (same scope). It seems even then we just need to avoid lazily initializing in the constructor. I saw some cases of deadlock in Guice like this: https://timothybasanov.com/2015/03/31/guice-singletons-parallelization.html So wasn't sure if Dagger2 had same behavior that we should be aware that would deadlock.
