### ISSUE TITLE
[KSP] Doesn't work well with `kotlin.Result`

### ISSUE THREAD

**Issue by BraisGabin** [google/dagger#4059]
In my project I have a class like this:

```kotlin
class MyClass @Inject constructor(result: Result<Unit>)
```

When I moved from kapt to ksp the ksp task works but javac is not happy with the generated code:

```
/path/build/generated/ksp/release/java/thepackage/MyClass_Factory.java:21: error: type Object does not take parameters
  private final Provider<Object<Unit>> resultProvider;
                               ^
/path/build/generated/ksp/release/java/thepackage/MyClass_Factory.java:23: error: type Object does not take parameters
  public MyClass_Factory(Provider<Object<Unit>> resultProvider) {
                                        ^
/path/build/generated/ksp/release/java/thepackage/MyClass_Factory.java:32: error: type Object does not take parameters
  public static MyClass_Factory create(Provider<Object<Unit>> resultProvider) {
                                                      ^
/path/build/generated/ksp/release/java/thepackage/MyClass_Factory.java:36: error: type Object does not take parameters
  public static MyClass newInstance(Object<Unit> result) {
                                          ^
```

`Result` is a value class with `@JvmInline` and it has a generic type. I imagine that the combination of those two generates this problem.

**Comment by kuanyingchou** [comment]
Hi, thanks for reporting this. I’ve made [some changes](https://github.com/androidx/androidx/commit/b0fa9cf493458a1f3b35a1d68298552e3eaae678) to the underlying library Dagger uses. It should make Dagger KSP match Dagger KAPT and generate `Object` instead of `Object<Unit>` in the next release. However, Dagger is still generating Java code even with KSP and this makes it impossible to fully support Kotlin inline classes. Using inline classes with Dagger can potentially be error-prone as well. For example, instead of injecting a `Result<Unit>` to `MyClass` here, Dagger is actually injecting an `Object`, as that’s [what Java sees a Kotlin generic inline class](https://kotlinlang.org/docs/inline-classes.html#representation). Please follow https://github.com/google/dagger/issues/2930 for inline class support in general.
