### ISSUE TITLE
Dagger 2.50 produces code that calls deprecated method

### ISSUE THREAD

**Issue by mar3kk** [google/dagger#4203]
Dagger 2.50 produces code that calls deprecated `DoubleCheck.lazy(initializerProvider)` method issuing warnings. 

```
AmazonAdIntegration_Factory.java:49: warning: [deprecation] <P,T>lazy(P) in DoubleCheck has been deprecated
    return newInstance(splitInstallManagerProvider.get(), DoubleCheck.lazy(initializerProvider), dummyAdLoaderFactoryProvider.get(), dummyAdViewHolderFactoryProvider.get());
                                                                     ^
  where P,T are type-variables:
    P extends Provider<T> declared in method <P,T>lazy(P)
    T extends Object declared in method <P,T>lazy(P)
```

**Comment by Chang-Eric** [comment]
Ah sorry about that, I added the `@Deprecated` there because it usually would indicate version skew between the generated Component and the Dagger runtime, but it looks like I forgot that the generated Factory classes can call that method as well. A future change is going to update the factory classes, but in the meantime, I'll remove the `@Deprecated` annotation on that for now.
