### ISSUE TITLE
File name too long when nesting subcomponents

### ISSUE THREAD

**Issue by pyricau** [google/dagger#421]
I'm going through the final steps to fully convert our app to Dagger 2, tying the hierarchy of subcomponents together. We have a deep hierarchy of sub components. This means the subcomponent names are too long:

```
error while writing DaggerDevRegisterAppComponent.DevLoggedInComponentImpl.DevRootActivityComponentImpl.SellerFlow_MobileComponentImpl.HomeScreen_MobileComponentImpl.TenderPath_ComponentImpl.AbstractGiftCardBalancePath_ComponentImpl.GiftCardBalanceInputScreen_ComponentImpl: 
./DaggerDevRegisterAppComponent$DevLoggedInComponentImpl$DevRootActivityComponentImpl$SellerFlow_MobileComponentImpl$HomeScreen_MobileComponentImpl$TenderPath_ComponentImpl$AbstractGiftCardBalancePath_ComponentImpl$GiftCardBalanceInputScreen_ComponentImpl.class (File name too long)
```

**Comment by pyricau** [comment]
Maybe Dagger should chance its strategy for naming the impls, and add a numbering scheme for duplicates?

Not sure what I can do in the meantime.

**Comment by gk5885** [comment]
A few things here…

* I think the current naming scheme is pretty ideal for keeping things clear and straightforward.  I can't think of any change that we'd want to just apply across the board that would be shorter while being clearer or even as clear.
* We _could_ use an alternate scheme for whenever we think the names are getting too long.  Unfortunately, "too long" can be hard to predict:  https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits
* Adding javadoc has long been on our list of things to do and if we do change the names, at least javadoc `@link`s back to the component would soften the blow.

A quick strawman for something that might help would be to use initialisms to try to shorten some of these names.  Here's an example if we just did it for any enclosing classes:
`DaggerDevRegisterAppComponent.DevLoggedInComponentImpl.DevRootActivityComponentImpl.SF_MobileComponentImpl.HS_MobileComponentImpl.TP_ComponentImpl.AGCBP_ComponentImpl.GCBIS_ComponentImpl`

**Comment by valeriyo** [comment]
Instead of changing the filename generation scheme wholesale, how about providing a class annotation so that folks who encounter this issue could override the Dagger-generated name part? For example, for class DevRegisterAppComponent --> @DaggerName(name = "DDevRegAppCmp"). This would still keep easy-to-read filenames, but allow teams with complex hierarchies to mitigate the long filename problem locally.

**Comment by loganj** [comment]
Or just turn on a "deep component hierarchy" flag and switch to a flat class naming scheme.  `<ComponentName>-<UUID>.java` or similar.

**Comment by ronshapiro** [comment]
It would be pretty lame if you had to know that you needed to pass that flag just in order to have your code compile.

@gk5885 what if all subcomponent types were nested directly within the generated component? They'd all still be inaccessible from without the codegen, and we could pass references directly instead of implicitly. Then as long as `"Dagger" + component_name + longest_subcomponent_name < N` you'd be fine.

**Comment by pyricau** [comment]
Now, please make fun of me, this is my temporary fix for our internal fork:

```diff
--- a/compiler/src/main/java/dagger/internal/codegen/ComponentWriter.java
+++ b/compiler/src/main/java/dagger/internal/codegen/ComponentWriter.java
@@ -44,12 +44,15 @@ import javax.lang.model.element.Name;
 import javax.lang.model.element.TypeElement;
 import javax.lang.model.util.Elements;
 import javax.lang.model.util.Types;
+import java.util.concurrent.atomic.AtomicInteger;
 
 /**
  * Creates the implementation class for a component.
  */
 final class ComponentWriter extends AbstractComponentWriter {
 
+  private static final AtomicInteger count = new AtomicInteger(0);
+
   ComponentWriter(
       Types types,
       Elements elements,
@@ -108,23 +111,10 @@ final class ComponentWriter extends AbstractComponentWriter {
 
     private ImmutableBiMap<ComponentDescriptor, String> disambiguateConflictingSimpleNames(
         Collection<ComponentDescriptor> components) {
+      // See https://github.com/google/dagger/issues/421
       Map<String, ComponentDescriptor> generatedSimpleNames = new LinkedHashMap<>();
-      // The ending condition is when there is a unique simple name generated for every element
-      // in components. The sizes should be equivalent (with one generated name per component).
-      for (int levels = 0; generatedSimpleNames.size() != components.size(); levels++) {
-        generatedSimpleNames.clear();
-        for (ComponentDescriptor component : components) {
-          List<String> pieces = componentQualifiedNamePieces.get(component);
-          String simpleName =
-              QUALIFIED_NAME_JOINER.join(
-                  pieces.subList(Math.max(0, pieces.size() - levels - 1), pieces.size()));
-          ComponentDescriptor conflict = generatedSimpleNames.put(simpleName, component);
-          if (conflict != null) {
-            // if the map previously contained an entry for the same simple name, stop early since
-            // 2+ subcomponent descriptors will have the same simple name
-            break;
-          }
-        }
+      for (ComponentDescriptor component : components) {
+        generatedSimpleNames.put("C" + count.incrementAndGet(), component);
       }
       return ImmutableBiMap.copyOf(generatedSimpleNames).inverse();
     }
```

**Comment by pyricau** [comment]
Which generates things like `com.squareup.DaggerAppComponent.C2Impl.C279Impl.C281Impl.C282Impl.C63Impl.C64Impl`

**Comment by ronshapiro** [comment]
FYI, the processor is single threaded so the atomic integer isn't necessary (unless you plan on maintaining this fork for a while ;)

**Comment by gk5885** [comment]
@valeriyo, I'd rather not add an API for tweaking something that is _entirely_ an implementation detail.

@loganj, if by "flag naming scheme" you mean using top-level classes rather than nested classes, that would be an option, but means that we'd have to generate components very differently.  We would either have to make a lot of fields accessible or pass around a bunch of state (probably more than the max number of cxtor args).

@ronshapiro, that's a variant of flattening the component hierarchy that might dodge some accessibility issues, but does complicate the generated code because you can no longer use the implicit `this` pointer.  We'd have to start keeping track of some number of `parent` references and traverse the correct number of them to get to some `Provider`.  E.g. `this.parent.parent.parent.applicationProvider`.  Ick.  It'd work but it seems like it'd be a little gross.

OK, time to make fun of @py.  Not really, but that is _exactly_ the type of thing we don't want to show up in a stack trace.  We might as well call them `$$$FastClassByGuice$$`.  :P  

@ronshapiro, I'd stick with `AtomicInterger` b/c `incrementAndGet()` is useful even if you don't care about concurrency.

So, here's what I'm thinking we can do…
*  Let's use 255 characters as the heuristic.  It's not exactly right, but should cover most cases correctly.
* Collapse names w/ some version of initialisms, but only when we have to.  I.e. walk the whole tree of subcomponents, figure out the name size and just shorten the ones that are required to make them and all of their children fit.

Sound like a reasonable enough plan?

**Comment by pyricau** [comment]
Yes! You might still want to use a variant of my strategy for the degenerate case where shortening still creates conflicts?

**Comment by pyricau** [comment]
For the record:

![screen shot 2016-08-03 at 5 31 20 pm](https://cloud.githubusercontent.com/assets/557033/17389200/d128a68a-59b6-11e6-8e8d-b1521c26df09.png)

The actual fix will be deeply appreciated :) .

**Comment by py** [comment]
Why are you making fun of me? )c:

**Comment by gk5885** [comment]
Sorry, @py.  Let me invite you to join in making fun of @pyricau.

**Comment by gk5885** [comment]
@pyricau, I'm actually at a conference this week and not going to be able to look at this for quite a while.  Do you have any interest in taking this on?  Otherwise, it might be a while before we get a fix.

**Comment by pyricau** [comment]
Just saw this. I don't have any bandwidth at the moment. I'll pass the word around, maybe someone in my team will get pissed and just do it.

**Comment by vanniktech** [comment]
This was not mentioned properly in the Github release notes - https://github.com/google/dagger/releases/tag/dagger-2.11-rc2

**Comment by TWiStErRob** [comment]
@pyricau @gk5885 this problem came up for 8 nesting levels, shouldn't the names be kept for 2-3 levels to cover most common usage with nice names, and then start abbreviating deeper?

**Comment by sandeep2242** [comment]
Facing the same issue, 
`A failure occurred while executing com.android.build.gradle.tasks.TransformClassesWithAsmTask$TransformClassesFullAction  /Users/abc/AndroidStudioProjects/FApp/app/build/intermediates/incremental/transformProductionReleaseClassesWithAsm/com.def.android.frapp.ui.abcd_efgh.platform.DaggerComponent$XyzComponentImpl$AbcComponentImpl$DefComponentImpl$GhiComponentImpl$JklComponentImpl$MnoComponentImpl.json  (File name too long)
`
This occured after these version change
Dagger: 2.13 (no change) Kotlin: 1.6.10 → 1.9.23 AGP (Android Gradle Plugin): 7.0.4 → 8.2.2 Kotlin DSL: 2.3.3 → 4.3.0 compileSDK: 33 → 34 Gradle: 7.0.2 → 8.2 Issue:

**Comment by bcorso** [comment]
We added a more robust fix in [Dagger 2.42](https://github.com/google/dagger/releases/tag/dagger-2.42) (basically we no longer nest subcomponent implementations within their parent to avoid this sitguation). Please try upgrading to at least 2.42.

**Comment by sandeep2242** [comment]
Hey @bcorso I tired the same but in my project while using dagger 2.13 we have made changes were a module can have a scope, and with this changes there are around 250 modules having this change, so changing these many modules is not quite easy as there are many nested subcomponents and eventually I will end up in missing bindings issue. So I just need a quick for now and eventaully I'll update with the lastest. So is there any way to fix this?
Here is an example of using this
```
@BrandingScope
@Module(subcomponents = [BrandingBlacklistingComponent::class])
class BrandingSubComponentModule
```

**Comment by bcorso** [comment]
>  there are many nested subcomponents and eventually I will end up in missing bindings issue

I don't really understand this part. You just need to remove the scope annotation from your module (which is currently doing nothing), so it shouldn't change anything about your bindings. This should be pretty simple fix even if you have 250 modules.

> So I just need a quick for now and eventaully I'll update with the lastest. So is there any way to fix this?

You could try to manually shorten the name, but IMO that's a worse solution and even more of a pain than fixing the scopes on modules.

> FYI why this issue was is coming after above mentioned version changes?

No idea. Maybe something with AGP since it's happening in the transform asm task.

**Comment by sandeep2242** [comment]
Hey @bcorso I faced one more issue when migrating to 2.51, where in my implementation while providing the dependency I was using the internal modifier, like this
`@PremiumPurchaseContainerScope
    @Provides
    @JvmStatic
    internal fun router(
      component: PremiumPurchaseContainerBuilder.Component,
      view: PremiumPurchaseContainerView,
      interactor: PremiumPurchaseContainerInteractor
    ):
`
which also cause the file name too long issue.

`
Execution failed for task ':app:transformProductionReleaseClassesWithAsm'. |  
  | > A failure occurred while executing com.android.build.gradle.tasks.TransformClassesWithAsmTask$TransformClassesFullAction |  
  | > /Users/abc/AndroidStudioProjects/App/app/build/intermediates/incremental/transformProductionReleaseClassesWithAsm/com.tdef.android.driverapp.ribs.root.premium_subscription.purchase_container.PremiumPurchaseContainerModule_ProvidePremiumPurchaseContainerInteractorMP$App_V5_1005_0_feature_MOB_1111_master_1723922837397_productionReleaseFactory.json (File name too long) |  
 `
And when I removed the internal modifier it was working fine, what could be the reason?

**Comment by bcorso** [comment]
> And when I removed the internal modifier it was working fine, what could be the reason?

When using the internal modifier the name of the function gets mangled which causes it to be longer.
