### ISSUE TITLE
@BindsInstance on Component.Factory supertype lambda parameters

### ISSUE THREAD

**Issue by Dkhusainov** [google/dagger#4220]
Currently dagger KSP has a feature of declaring `@Component.Factory` with lambdas which accept `dependencies` as arguments. It would be nice to also have this for arguments annotated @BindsInstance, which currently does not work with an error:
`Component.Factory method has parameters for modules or components that aren't required: [android.content.Context p1]` 

Example code:
```
interface MyDependencies {
    val context: Context
}

//this works
@Component(dependencies = [MyDependencies::class])
interface MyComponent {
    @Component.Factory
    interface Factory: (MyDependencies) -> MyComponent
}

//this doesn't work
@Component
interface MyOtherComponent1 {
    @Component.Factory
    interface Factory: (@param:BindsInstance Context) -> MyOtherComponent1
}

//this obviously works
@Component
interface MyOtherComponent2 {
    @Component.Factory
    interface Factory {
        fun create(@BindsInstance context: Context): MyOtherComponent2
    }
}
```

**Comment by Chang-Eric** [comment]
> Currently dagger KSP has a feature of declaring @Component.Factory with lambdas

Technically, this isn't really a feature and more just a consequence of the Kotlin language. This isn't really something we intentionally created. I mention this mostly because it helps to understand why this doesn't work. What Dagger really sees is just the Factory interface and the methods defined on there.

In the first case, the Factory interface has a method on it that takes a `MyDependencies` and returns a `MyComponent`, and so it finds everything just fine. However, it helps to think about what is going on here under the hood. I believe when compiled it will essentially make the Factory interface extend something like `Function1<MyDependencies, MyComponent>`.

If you think about it now, it kind of makes sense why adding the `@BindsInstance` to the parameter isn't going to work. You can't actually annotate the parameter in the `Function1` definition since you only change the type arguments. I'm not sure if that annotation just gets dropped or what, but that's basically why Dagger isn't finding the `@BindsInstance` annotation.

Given this and that extending lambdas wasn't really an intentional API anyway, I think it'll be best if you just directly define the Factory methods.
