### ISSUE TITLE
Hilt Generated Code having not used code?

### ISSUE THREAD

**Issue by Ahn-seokjoo** [google/dagger#4276]
hi im watching hilt generated code, but never called get method and create method in generated code.

![image](https://github.com/google/dagger/assets/67602108/d2777b96-42c0-463a-a790-688e583a03f0)

even NetworkModule_ProvideMemberDaoFactory usage, only use provideMemberDao method. never used get()
![image](https://github.com/google/dagger/assets/67602108/3be4a916-2e7c-4283-94f7-260b5ca565bd)

so why hilt generated not used code? (get, create)
If I missed something, I would appreciate it if you could let me know in what situations it is used.

**Comment by Chang-Eric** [comment]
Because the factory classes are generated by Dagger, and are created separate from the `@HiltAndroidApp` or Dagger `@Component` as they may be used in multiple roots (e.g. if you include a module in a library). So we have to include code for multiple situations, but not all of it will be used in any particular situation. For example, some of those methods will be used when not using `fastInit` mode.
