### ISSUE TITLE
Compile time error with KSP with Generics

### ISSUE THREAD

**Issue by nitinsethi86** [google/dagger#4322]
I am trying to test the waters with KSP (currently in aplha ) mainly because of the expected build time improvements. 

I am seeing the below compile time error with ksp. The same setup works with kapt. Is this expected with the current version of 2.51.1?  

app/build/generated/ksp/debug/java/com/ms/multimoduleapp/DaggerApplicationComponent.java:78: error: incompatible types: TestDelegate cannot be converted to ITestDelegate<InterfaceUsedInGenerics>
      LoginActivity_MembersInjector.injectTestDelegate(instance, new TestDelegate());

I am not quite sure if I understand the comment regarding generics in the below thread.

https://github.com/google/dagger/issues/2349#issuecomment-1699569360

Dagger version: 2.51.1

I have also attached the reproducer project in case its needed.
[Reproducer_KSP.zip](https://github.com/user-attachments/files/15605038/Reproducer_KSP.zip)

**Comment by kuanyingchou** [comment]
Hi, @nitinsethi86 , 

Thanks for reporting. I was able to reproduce. This should be due to an issue in the KSP library where a type defined as `ITestDelegate<? extends InterfaceUsedInGenerics>` would be seen as `ITestDelegate<InterfaceUsedInGenerics>`. While this is fine in Kotlin because `ITestDelegate` has declaration-site variance, it becomes incompatible with your `TestDelegate` in Java. I just filed the issue at https://github.com/google/ksp/issues/1969.

As a workaround I would try migrating the place where you inject `ITestDelegate` to Kotlin.

**Comment by nitinsethi86** [comment]
@kuanyingchou Thanks for the reply.
The classes involved is considerably large. So, the workaround is slightly challenging. 
Is there any other workaround that we can apply?

**Comment by kuanyingchou** [comment]
You can create a wrapper in Kotlin and inject that wrapper instead. Something like:

```
class DelegateWrapper @Inject constructor(
    val testDelegate: ITestDelegate<InterfaceUsedInGenerics>)
```

Note that due to [another issue in an underlying library](https://issuetracker.google.com/issues/347731178)  Dagger uses, the value of `suppress` in `@JvmSuppressWildcards` is not respected. Please use `@JvmWildcard` instead. For example, `@JvmSuppressWildcards(suppress = false) ITestDelegate<InterfaceUsedInGenerics>` in your code should be replaced with `ITestDelegate<@JvmWildcard InterfaceUsedInGenerics>`.

**Comment by nitinsethi86** [comment]
That works. Thanks. I will wait for the stable support of KSP in dagger.
