### ISSUE TITLE
@Provides annotated abstract methods

### ISSUE THREAD

**Issue by j-baker** [google/dagger#448]
Was wondering if it'd be acceptable to use @Provides annotated abstract methods.

In our code we have plenty of cases where we're using things like Immutables for brevity, but want to inject one of the fields; e.g. we might have a cache timeout in a config which we want to inject when constructing the cache itself.

That being the case, it'd be really nice to use an abstract getter in order to do this, which is implemented by the annotation processor, however Dagger dies in this case.

At the moment, we could achieve the same thing by simply not marking the method abstract, and directly overriding it, but this is unpleasant.

Are there any major blockers to removing this restriction in Dagger?

**Comment by ronshapiro** [comment]
Can you illustrate the case in code?

**Comment by j-baker** [comment]
Yeah, so: We have a nested YAML configuration, and we use Jackson to deserialise this into Java objects.

So, as an illustrative example, we would like to be able to do

```
@Value.Immutable
@JsonDeserialize(as = ImmutableMyAppConfiguration.class)
@Module(includes = {AuthorizationConfiguration.class})
public interface MyAppConfiguration {
    LoggingConfiguration logging();
    @Provides AuthorizationConfiguration auth();
    ...
}

@Value.Immutable
@JsonDeserialize(as = ImmutableAuthorizationConfiguration.class)
@Module
public interface AuthorizationConfiguration {
    @Provides @Named("user-session-cache-timeout") Duration userSessionCacheTimeout();
}

```

but at the moment our choice is between either wrapping the configuration classes with modules, or otherwise not using Immutables and adding boilerplate.

**Comment by ronshapiro** [comment]
As someone who doesn't use Jackson this doesn't mean much to me, I'm not sure what the intent of those annotations are. 

Modules either need to tell Dagger explicitly the code to call to construct an object, or it must be a well-defined Dagger construct, like `@Binds`. There's no way for Dagger to understand what either of these annotations do. Perhaps you're trying to use `@Component.dependencies`?

**Comment by tbroyer** [comment]
@ronshapiro IIUC, it doesn't really matter whether Jackson is used here; it's more a matter of using Immutables (similar to AutoValue). Let's illustrate the same problem with AutoValue:

```java
@AutoValue
@Module
public abstract class AuthorizationConfiguration {
  @Provides @Named("user-session-cache-timeout")
  public abstract Duration userSessioncacheTimeout();
}
```
(i.e. ignore the `@JsonDeserialize`, and change `@Value.Immutable` to `@AutoValue`; creation of the generated value-classes is different between Immutables and AutoValue but they're not the problem here)

FWIW, in my apps, where I have similar patterns (using Immutables for configuration objects), I'd inject the `AuthorizationConfiguration` object directly. So with the nested pattern from the OP:

```
@Module
public class ConfigurationModule {
  private final MyAppConfiguration appConfiguration;

  @Provides LoggingConfiguration logging() { return appConfiguration.logging(); }

  @Provides AuthorizationConfiguration auth() { return appConfiguration.auth(); }

  @Provides @Named("user-session-cache-timeout") Duration userSessionCacheTimeout() {
    return appConfiguration.auth().userSessionCacheTimeout();
  }
}
```

This is probably what @j-baker calls _“wrapping the configuration classes with modules”_. I, for one, find it much more readable/maintainable (+ separation of concerns). And if the added boilerplate is an issue, you could still create an annotation processor to generate the module(s) based on your value-classes.

**Comment by ronshapiro** [comment]
I think what @tbroyer mentioned, combined with either component dependencies or `@BindsInstance` should suffice here?
