### ISSUE TITLE
Dagger 2.53 causes unstable transitive dependency kotlin-stdlib

### ISSUE THREAD

**Issue by G00fY2** [google/dagger#4525]
Dagger 2.53 bumped `org.jetbrains.kotlin:kotlin-metadata-jvm` to `2.0.0-Beta5` (https://github.com/google/dagger/commit/9a94d1973fa42b56405c5cf0f80dcebd85e19580). Since `kotlin-metadata-jvm` depends on `kotlin-stdlib` this will also affect stdlib version used at the pre compile task.

We have a check in our Gradle setup which fails the build if a dependency was selected by conflict resolution and the new version is not stable (https://gist.github.com/G00fY2/c852322a18b187f40bb884a85065c57f).

Would be nice if dagger ships only stable dependencies.

I know that **this will not affect runtime classpath**, but still wanted to raise this "issue".

**Comment by hnljp** [comment]
org.jetbrains.kotlin:kotlin-metadata-jvm should now follow the Kotlin version.
I guess that it is a mistake that it is not simply using the already defined KOTLIN_VERSION.

**Comment by bcorso** [comment]
Hmm, yeah Dagger [explicitly depends on `"org.jetbrains.kotlin:kotlin-stdlib:1.9.24"`](https://github.com/google/dagger/blob/master/WORKSPACE#L293), but since `"org.jetbrains.kotlin:kotlin-metadata-jvm:2.0.0-Beta5"` also depends on `kotlin-stdlib` dependency resolution takes the newer version.

I think the easiest way to fix this is to try to bump to `"org.jetbrains.kotlin:kotlin-metadata-jvm:2.0.0"` (i.e. non-beta version). I initially tried that but there were some breaking API changes, so I'll need to fix those as well.

I'll try to get this out in the 2.53.1 release.

**Comment by Ufkoku** [comment]
I think it can be a cause of this [issue ](https://stackoverflow.com/questions/79257452/i-am-struggling-compiling-android-project-in-android-studio-with-dagger-hilt-and). 
Using dagger/hilt 2.53 with kotlin 2.1.0 and view models injection fails during compilation with meta data error on windows machines.

**Comment by bcorso** [comment]
The issue itself is pretty simple, we just need to upgrade our kotlin-metadata-jvm dependency past v2.0.0-Beta5. 

However, the main blocker for this is that Dagger currently depends on deprecated kotlin metadata v1.0 APIs that are removed in kotlin metadata v2.0.0+.

I should have a fix out today and then will try to get the 2.53.1 release either today or early next week.
