### ISSUE TITLE
[KSP] Incremental symbol processing not working (or working poorly)

### ISSUE THREAD

**Issue by mar3kk** [google/dagger#4549]
Does dagger/hilt KSP actually support incremental symbol processing? It seems changing any java or kotlin file in our project, even one that seemingly shouldn't contribute to the output, causes the ksp to re-run completely.
Analyzing the KSP log files `kspDirtySet.log` and `kspSourceToOutputs.log` turns out most of the times the files considered dirty are only used to produce some proguard rules. There are a lot of entries ending `_HiltModules_KeyModule_LazyClassKeys.pro`. Feels like something that could be skipped when minification is disabled.

**Comment by bcorso** [comment]
> Does dagger/hilt KSP actually support incremental symbol processing?

Hmm, yes, it should support incremental processing. 

In KSP the incremantal processing is determined by the mode of each output ([isolating/aggregating](https://kotlinlang.org/docs/ksp-incremental.html#aggregating-vs-isolating)). For the LazyClassKey proguard files, this is setup [here](https://github.com/google/dagger/blob/master/java/dagger/internal/codegen/processingstep/LazyClassKeyProcessingStep.java#L112-L115).

If you're seeing an issue specifically with the `.pro` files it could be a bug related specifically to resource file outputs (since most of Dagger's outputs are source files, it could explain why we didn't hit this before now). However, that would be something we'd need to get fixed in KSP rather than Dagger.

We're a little back logged right now, so if you could provide a minimal repro example that could help get this rolling.

**Comment by bcorso** [comment]
Actually, nm. @Chang-Eric pointed out that we were forgetting the originating element for the resource file (https://github.com/google/dagger/blob/master/java/dagger/internal/codegen/processingstep/LazyClassKeyProcessingStep.java#L114).

I'll send out a fix for that soon.

**Comment by mar3kk** [comment]
Thanks @bcorso for fixing it promptly, however I do get compilation error on the latest HEAD-SNAPSHOT.
```
e: [ksp] MultibindingAnnotationsProcessingStep was unable to process 'binds(com.opera.android.privatedownloads.customisation.PrivateFolderCustomisationViewModel)' because 'error.NonExistentClass' could not be resolved.
```

**Comment by bcorso** [comment]
Thanks @mar3kk  for trying it out and verifying the fix! 

We'll get the 2.54.1 release out next week, though it might be later in the week due to the holidays.

**Comment by bcorso** [comment]
> after applying resolution strategy described here https://dagger.dev/dev-guide/versions.html it compiled.

Just to confirm (since I noticed you only said "it compiled"), did you verify if it fixed the incremental processing issues you were seeing?

**Comment by mar3kk** [comment]
Yes, I didn't verify the fix back then when I posted the message. I gave it a try and I think the issue reported here got fixed. I no longer see that many files contributing to the generated proguard rules. Thanks!

However I still see a hundreds of files marked dirty in the `kspDirtySet.log` after changing single .java file that is not listed as contributing to any output in the `kspSourceToOutputs.log` file. I am trying to figure it out but feels KSP cannot tell why those files are considered dirty. I don't think this is necessarily a dagger issue though, we have more ksp processors in the project and KSP doesn't help not producing some log files that could help finding the root cause which I reported here https://github.com/google/ksp/issues/2277.

**Comment by mhadad** [comment]
in app level gradle file the following is correct

```
allprojects {
    configurations.all {
        resolutionStrategy.eachDependency { 
            if (this.requested.group == "com.google.dagger") {
                this.useVersion("HEAD-SNAPSHOT")
            }
        }
    }
}

```
