### ISSUE TITLE
Allow subcomponents to have explicit component dependencies

### ISSUE THREAD

**Issue by dalewking** [google/dagger#480]
Components allow you to specify component dependencies so that when you construct the component you can supply to the constructor components to provide dependencies which allows you to decide at run time what implementation of the component  to use at runtime. But for some reason subcomponents are not allowed to use dependencies other than the implicit dependency to the parent component.

I cannot find any valid reason for the disparity and I have a complex graph scenario involving a plugin architecture and being able to choose which implementation of a dependency to use for a subcomponent at runtime is definitely needed.

**Comment by tasomaniac** [comment]
I think I have a complete different scenario but I recently needed the same thing. 

Currently, I am doing it through module. I have the dependency as constructor param in a module in subcomponent. Since the module cannot be instantiated automatically, I instantiate the module using the dependency and provide it to the subcomponent's Builder manually. 

Instead, I would prefer to provide the dependency directly to the component's builder.

**Comment by ronshapiro** [comment]
Maintaining a valid graph of scopes gets really complicated when you start adding subcomponent dependencies. It's not something we are ready to take on yet. If you want, you're welcome to write a wrapper module for any dependency you want - that's essentially what we would do anyway, but it's not something we are ready to include in dagger, at least today.

**Comment by tasomaniac** [comment]
Makes sense. But why close the issue? 
If it is a possible feature that can be there in the future why not keep it open? It doesn't have to be done today.

**Comment by ronshapiro** [comment]
It's not anywhere on our horizon at all, and I don't think it will be. It's definitely something we're aware that people have asked for, but we don't at the moment thing it's a necessary feature. I'm pretty confident that more people will ask for it again, and we can continue to reevaluate then.
