### ISSUE TITLE
Art kills app

### ISSUE THREAD

**Issue by jcampbell05** [google/dagger#482]
Currently the Art runtime seems unable to locate the Factory classes generated by dagger. I get this:

10-25 11:05:00.984 4542-4542/com.wenow.oneaday I/art: Rejecting re-init on previously-failed class java.lang.Class com.wenow.oneaday.ApplicationModule_ProvidesMixpanelAPIFactory

**Comment by ronshapiro** [comment]
What makes you think this is dagger?  That log line has nothing related to Dagger in it. If `javac` completes fine, this is likely an Android build system issue and not a Dagger one.

**Comment by jcampbell05** [comment]
@ronshapiro The copy and paste didn't work properly. But the error its giving is its missing one of the Factory classes generated by Dagger. 

Either its Dagger or I'm missing a configuration in the build system to make Dagger work.

**Comment by ronshapiro** [comment]
Can you try again to put the message? Without that there's nothing we can do. Maybe try stack overflow?

**Comment by jcampbell05** [comment]
@ronshapiro  I have updated with the full message ?

**Comment by ronshapiro** [comment]
That's still not so helpful. I would search that art error on its own. Also try disabling dagger but copy/pasting all the generated code into your project, so that you can see if it's something related to `apt` or not. If you find anything dagger related feel free to reopen, otherwise stack overflow is probably your best bet
