### ISSUE TITLE
ComponentBuilder keeps module instance when it's bound to a map

### ISSUE THREAD

**Issue by frogermcs** [google/dagger#505]
Hey,

In Dagger 2.7 there is a new way to provide Builders of Subcomponents into map (Multibinding). This is something what @gk5885 showed on his presentation: https://www.youtube.com/watch?v=iwjXqRlEevg&feature=youtu.be

I tried to reproduce it in Android (more details in my blog post: https://medium.com/azimolabs/activities-subcomponents-multibinding-in-dagger-2-85d6053d6a95#.m8fzq32ms) and I've just found one thing which causes memory leaks.

Subcomponents builders which are kept in injected Map keep references to their modules. And it leads to issue where:

I have Activity (screen) subcomponent, which depends on Activity Module. Module keeps Activity reference to make it a part of objects tree in this subcomponent (Activity object is injected to its presenter).
The problem is that even if Component itself is destroyed, Activity reference is still kept by Module, which is kept by Subcomponent builder class. 

Temporary I fixed this issue by changing Activity reference in Module to WeakReference, but I'm wondering if keeping module instance in Subcomponent builder is correct approach.

My example project where full implementation of Subcomponents multibinding can be found here: https://github.com/frogermcs/Dagger2Recipes-ActivitiesMultibinding

**Comment by gk5885** [comment]
I presented that before the feature actually existed, so caveat emptor. :)

But from a quick read of your post, what you have appears to look right, and I agree with the issue that you have identified for the code that you've presented.  But, the solution to avoiding the leak is pretty straightforward: inject `Map<Class<?>, Provider<Builder>>` rather than `Map<Class<?>, Builder>`.  Then, when you look up builders from the map, you get a new instance from the provider rather than holding the same builder reference.

So, I don't think that there's a bug here.  The builders all hold the passed objects with strong references and retain them for their entire lifetime.  The fix is to just ensure that you're not holding on to the builders long-term.
