### ISSUE TITLE
Feature Request: Make code formatter configurable

### ISSUE THREAD

**Issue by digitalbuddha** [google/dagger#515]
Currently there does not exist a way to disable the code formatting during generated class creation.  https://github.com/google/dagger/issues/368 goes into a discussion on performance of current formatting.  I'd like to create a separate feature request to allow a user of Dagger to disable formatting altogether.  I have 2 reasons for the request:
* Like many, we do not adhere to Google's code formatting within our codebase 
* Speed of compilation

Thank you for your consideration

**Comment by nisrulz** [comment]
@digitalbuddha looks like someone created a PR #513 , in the same context. Leaving it here for info.

**Comment by gk5885** [comment]
Glad we have a tracking bug for this.  Thanks.

First, insofar as performance is a concern, I think our first priority should absolutely be to address #368.  Regardless of whether or not we add a flag we *must* address performance.  I think we have sufficient evidence to suggest that we have done a pretty bad job of making the formatting perform well, but not that we cannot make it sufficiently fast as to be acceptable in every build.

As to whether or not it needs to be formatted at all, that is a tricky thing to reason about.  You can obviously argue that you don't necessarily _need_ legible source code to have a functional, successful dependency injection framework because Guice exists.  But, aside from the particular limitations w.r.t. Android, Google decided to invest in Dagger particularly because the opacity of the implementation made applications difficult to debug and maintain.  So, the ability to read and understand the implementation of the injector has always been a primary design goal or Dagger 2.

As far as the particular styling goes, the fact that it is Google style vs. any other doesn't really matter much to me.  We use GJF to format the source mostly because we've had terrible luck using other formatters -- they seem to have too many poorly handled edge cases to apply them broadly.  That said, if someone were motivated to try to adapt a different formatter implementation, I think that'd be a great addition.

**Comment by JakeWharton** [comment]
I'm particularly interested in what pragmatic changes we can make in JavaPoet to support _some_ formatting. I believe @ronshapiro or maybe it was you Greg that suggested running CJF only on a `CodeBlock` for method body contents and leaving the rest to the default JavaPoet formatting.

**Comment by hzsweers** [comment]
Chiming in here: 95% of my reason for that PR is because it causes flaky builds for us (#457).

**Comment by cypressious** [comment]
I'm the author of #368. I understand the motivation to fix the underlying issue but why not take the quick win by adding the option first and then you can still fix the formatting performance later?

As @hzsweers stated, his issue isn't even the performance, so disabling formatting can be considered a valid _feature_ with a real use case.

**Comment by hzsweers** [comment]
Apparently we do have build perf issues. I don't have the numbers, but @kageiit does and is going to give the data we have over to @ronshapiro and @gk5885

**Comment by lwasyl** [comment]
What's the status on this issue? #513 seemed to be pretty straightforward but haven't been merged in almost a year, and eventually got closed. Is it something that you are still considering?

**Comment by landoulsi** [comment]
Hey, I tried the following feature to disable formatting dagger generated sources : 
```
kapt {
    javacOptions {
        option("-Adagger.formatGeneratedSource=disabled")
    }
}
```
but I am getting this warning while building 
`warning: The following options were not recognized by any processor: '[kapt.kotlin.generated, dagger.formatGeneratedSource]'`

**Comment by cypressious** [comment]
According to @JakeWharton's talk at https://jakewharton.com/helping-dagger-help-you/, this is the correct syntax to set the option

```groovy
afterEvaluate {
    extensions.findByName('kapt')?.arguments {
        arg('dagger.formatGeneratedSource', 'disabled')
    }
}
```

**Comment by JakeWharton** [comment]
That's for in your `allprojects` block in root `build.gradle` so it applies everywhere.

For a single project, just
```groovy
kapt {
  arguments {
    arg(...)
  }
}
```
will work

**Comment by Dimezis** [comment]
Seems like it's released already, but doesn't work for me. 
Neither this
```
afterEvaluate {
    extensions.findByName('kapt')?.arguments {
        arg('dagger.formatGeneratedSource', 'disabled')
    }
}
```
this 
```
kapt {
    arguments {
        arg('dagger.formatGeneratedSource', 'disabled')
    }
}
```
or this
```
tasks.withType(JavaCompile).all {
        options.compilerArgs += ['-Adagger.formatGeneratedSource=disabled']
}
```

Code is still formatted after a clean build.

**Comment by tbroyer** [comment]
What do you mean by

> Code is still formatted after a clean build.

?
If you mean that code still is really readable, then yes, that's a feature of JavaPoet (which is why reformatting it again using Google Java Format is mostly useless work, and is actually useless for most people, who won't style-check generated code and won't really bother about the exact code style of generated code)
