### ISSUE TITLE
Create maven shaded/all-deps artifact for dagger-compiler

### ISSUE THREAD

**Issue by facboy** [google/dagger#574]
I keep trying to post this to dagger-discuss but it never seems to get accepted.  Is it possible to create a version of dagger-compiler (and possibly dagger if necessary) that has its dependencies shaded?

dagger 2.8 does not work on our project because it requires Guava 20.0 but our project is pinned to Guava 19.0.  During compilation the dagger annotation processor fails with a NoSuchMethodError because some of the Guava Preconditions method signatures have changed between 19.0 and 20.0.

**Comment by JakeWharton** [comment]
The annotation processor and normal classpath are separate. You should be
able to use 20 in the processor path and 19 in the compilation and runtime
classpath.

**Comment by ronshapiro** [comment]
If you're using Guava 19, you should really upgrade. Guava expects users to stay up-to-date and each release has a diff to make it easy to upgrade. Unless you have an explicit reason to stay on 19, you should probably get to 21.

Aside from what @JakeWharton said, we can't shade all of Guava dependencies, since we need to understand some like Optional and ListenableFuture in your own source. For this, and the reason that Guava maintains a stable API, we have chosen not to shade Guava. 

If you feel there are other dependencies that need shading, we are happy to consider them.

FYI Dagger 2.9 will be using Guava 21. You don't want to drift too far from the latest version while using Guava.

**Comment by facboy** [comment]
That sounds fair enough.

@JakeWharton Thanks for the suggestion, I thought I'd tried that and it didn't work.  Turns out that it does work on Maven command-line, but not in Intellij IDEA (it doesn't respect the Maven annotationProcessorPath config).  Time to raise a bug with JetBrains.
