### ISSUE TITLE
Dagger docs side-navigation is cut on small screens

### ISSUE THREAD

**Issue by tasomaniac** [google/dagger#583]
The side navigation at https://google.github.io/dagger/ is getting bigger and it is not scrollable. 

I was using my 11inch laptop and some of the items are not visible/clickable. Not a huge deal but would be good to fix.

![image](https://cloud.githubusercontent.com/assets/763339/23094112/2116c086-f5f3-11e6-8e31-fa21a0ba0729.png)

**Comment by jfelrod1960** [comment]
Same here with me.  I'm trying to learn more about Dagger and every little bit will help.

**Comment by ronshapiro** [comment]
I tried to fiddle around with this with Chrome Developer tools but couldn't figure it out. It's been long since I did any non-trivial CSS. Do you know how to fix it? Or, maybe we should make the sections expandable/collapsable?

I'd be happy to review a PR on the gh-pages branch if either of you have a solution to either.

**Comment by tasomaniac** [comment]
I also have no idea. I just wanted to report. 
Let me seek for someone then.
