### ISSUE TITLE
Allow @BindsInstance on builder method parameters

### ISSUE THREAD

**Issue by JakeWharton** [google/dagger#616]
The current usage on builders would change from:
```java
interface Builder {
  @BindsInstance Builder activity(MainActivity activity);
  MainComponent build();
}
```
to:
```java
interface Builder {
  Builder activity(@BindsInstance MainActivity activity);
  MainComponent build();
}
```
to no real gain or loss in readability.

It would, however, also allow shorthand use on subcomponent factory methods from the parent component:
```java
interface AppComponent {
  MainComponent createMainComponent(@BindsInstance MainActivity activity);
}
```
One could bind as many instances as you want with additional parameters, switching to a subcomponent builder at their own discretion.

**Comment by stevecstian** [comment]
When I see a builder method annotated with `@BindsInstance`, that annotation is telling me that *this builder method* is going to *bind instance*.  I think we should have a new annotation to describe *that parameter is going to be bound* **if** we really want to have annotation on parameter.

**Comment by JakeWharton** [comment]
I would rather not have the feature than add a new, redundant annotation.

Also, the sentence "When I see a builder method parameter annotated
with @BindsInstance, that annotation is telling me that this builder
method is going to bind this parameter instance." makes sense as well so
it's not an argument.

**Comment by gk5885** [comment]
@ronshapiro and I had a fair bit of discussion about this.

As @JakeWharton points out, there is really no difference between putting the annotation on the method and putting it on a parameter, so just plain inertia makes me want to keep it where it is.

But, the point about factory methods is interesting.  Generally, we don't really encourage the factory methods because it makes for some awkward relationships between components, interfaces and the call sites where you actually want to instantiate a subcomponent.  It can totally be done (and based on what Jake is hinting at, it sounds like they're doing more or less exactly what I would hope), but perhaps there's a more straightforward way

@jbeder suggested that we also provide `@Subcomponent.Factory` as functional interface for single methods with N parameters (`@BindsInstance`, passed modules) that create subcomponents.  Then rather than implementing interfaces and passing the component directly, you have lightweight objects that can be injected right where they're needed.  If that were a thing, then `@BindsInstance` on the parameter would be crucial.

What do you think?

**Comment by JakeWharton** [comment]
I would definitely like that as we do something similar manually. I'd be
curious if such an approach could help the Android binding setup in any
way. I guess the builder could be replaced by the factory, but otherwise it
would be the same.

**Comment by ronshapiro** [comment]
Yea, `AndroidInjector.Builder` could effectively go away which would be nice.

**Comment by stevecstian** [comment]
@gk5885 @jbeder Do you mind share some quick code example here for the usage of `@Subcomponent.Factory`?

**Comment by cgruber** [comment]
I'm pretty +1 to this proposal, as I would like to see factory options for cases where there are no instance modules, and maybe one or two pieces of seeded state.  I'm kind of agnostic if htere's a Factory interface or it's an optional aspect of the Builder.

**Comment by stevecstian** [comment]
Does that help if we allow user to declare those *instances to be bound* as the parameters of the build method in Builder?

**Comment by ronshapiro** [comment]
@cgdecker implemented `@Component.Factory` recently and I think that should make this obsolete.

**Comment by JakeWharton** [comment]
I still think there's a weird asymmetry between builder methods and factory methods now. Could builders support the annotation existing on the parameter _or_ the method now? I seem to always get it wrong.

**Comment by ronshapiro** [comment]
Fair point.

**Comment by cgdecker** [comment]
This is submitted internally and should be synced out soon; `@BindsInstance` will be allowed on either the method or the parameter, but not both.
