### ISSUE TITLE
Move Factory, MembersInjector to internal package.

### ISSUE THREAD

**Issue by JakeWharton** [google/dagger#63]
As discussed.

**Comment by cgruber** [comment]
Bumping this, but we'll chat about it separately.

**Comment by gk5885** [comment]
You know, the thing that I completely overlooked until seeing it now is that † had `MembersInjector`, so it'd seem a little weird for ‡ to just not have it.  Since I think we were a little on the fence, that seems like a reasonable argument in favor of leaving it alone.

`Factory` can totally move though.

**Comment by JakeWharton** [comment]
Dagger 1 didn't have components which are a more-explicit members injector.

**Comment by gk5885** [comment]
That's true, but I see it as not really doing any harm and removing it adds cost to migrating from † to ‡.

**Comment by cgruber** [comment]
Agreed.  SGTM.  I'll close this when I sync from head.

**Comment by JakeWharton** [comment]
The harm is being the less-valuable of a redundant pair of mechanisms that are in the public API and thus require documentation, explanation, and support.

**Comment by cgruber** [comment]
A semi-crappy thing would be to make dagger.internal.MembersInjector, and make dagger.MembersInjector deprecated and inherit from the former.  Then there's a migration path, wtih the deprecation warning to go with it, and a note that it will go away in 2.1.

**Comment by cgruber** [comment]
Never mind - that would require supporting injecting of both interfaces for backward compatibility, and that's ungood.

**Comment by sameb** [comment]
I'm not clear on how leaving MembersInjector helps migration to Dagger2.  IIRC, Dagger2 doesn't support injecting a MembersInjector... so it'd just cause injection errors and confusion, no?

**Comment by cgruber** [comment]
#140 moves Factory into internal.

**Comment by gk5885** [comment]
@sameb, injecting a `MembersInjector` is something we support and I just sent the CL to test it.

**Comment by cgruber** [comment]
Given that this is a public type that is referenced in user code, I think that's the deciding factor, and we leave MembersInjector as is.

**Comment by JakeWharton** [comment]
> that's the deciding factor

the major version bump disagrees with this

**Comment by gk5885** [comment]
Oh, for sure we _could_ get rid of it.  There just didn't seem to be any real benefit.  Smaller APIs are nice, but this is already a thing that we already support and moving it to a different package is just feels like churn.

**Comment by cgruber** [comment]
@JakeWharton - to be clear, I didn't mean that the fact that *Dagger 1.0* user code references it is the deciding factor, but the fact that it is, currently a supported (and tested) feature of the Dagger 2 code line.  If we decided to disable that feature, it would then be in question.

**Comment by ronshapiro** [comment]
Just stumbled upon this. I only see 16 usages of "MembersInjector<" in google, and most of them seem either like the wrong idea (someone is calling `injectMembers(new Foo())`) or extremely easy to migrate to just injecting the component or their own type.

I say that because we're working on inlining members injection now, which would mean that dagger's generated factories could remove their dependency on a `MembersInjector`, really making it obsolete.

If we were to remove it, it could make the internal model much simpler as we could replace all usages of `BindingKey` with `Key`.

This would obviously have to go through a deprecation cycle (and I think for something like this we'd probably want something much more than 6 months), but it could be worth it.

**Comment by cgruber** [comment]
I think it's worth it. I think there's a theoretical case for it that I've
not seen in real life, that couldn't be achieved with a subcomponent.
