### ISSUE TITLE
dagger-grpc

### ISSUE THREAD

**Issue by lukaszx0** [google/dagger#647]
I'm following up on the chat I had with @gk5885 at Devoxx conference.

He said that there is a some sort of gRPC integration library for Dagger and the best way to learn about it is by filling issue.

@netdpb could you provide more info?

**Comment by netdpb** [comment]
We have integration for gRPC servers internally. If you're interested, we will release it here.

It effectively lets you inject your service implementations even if they're in a subcomponent, even though gRPC expects the implementations to be singletons eagerly loaded on the server.

It also gives you `@CallScope`, which you can apply to subcomponents, so that a subcomponent's lifetime can be associated with a particular call, even a streaming one.

**Comment by lukaszx0** [comment]
> If you're interested, we will release it here.

Yes, I'd be very interested in that.

Very cool, thanks @netdpb!

**Comment by ronshapiro** [comment]
https://github.com/google/dagger/pull/716 adds in support for dagger-grpc. It will be in the next release (2.11-rc2 probably)

**Comment by ronshapiro** [comment]
If you want to give it a go, it's in the latest snapshot
