### ISSUE TITLE
Support multiple keys within Map Multibindings

### ISSUE THREAD

**Issue by tsums** [google/dagger#701]
It would be useful if when declaring a binding into a map, we could specify that one binding should be available under multiple keys.

Something like:

```java
@Binds
@IntoMap
@TypeKey(Type.FOO)
@TypeKey(Type.BAR)
abstract Handler bindFooBarHandler(FooBarHandler handler);
```
or
```java
@Binds
@IntoMap
@TypeKeys({Type.FOO, Type.BAR})
abstract Handler bindFooBarHandler(FooBarHandler handler);
```
Right now this can be accomplished with multiple `@Binds` methods within a module, which is a little verbose.

**Comment by trevjonez** [comment]
Repeatable annotations are a java 8 feature so that could/would cause problems with android builds? Maybe possible once the new desugar tool is on the production release channel? Seems like the array of types would be the only option given the current landscape.

**Comment by JakeWharton** [comment]
They're a language feature only so there's no problem for Android. In bytecode they wind up as an array enclosed a single annotation. And anyway these annotations should have `SOURCE` retention so they're not even making it to the class file.

**Comment by ronshapiro** [comment]
> these annotations should have `SOURCE` retention
`SOURCE` retention will not always work if the module is in a different compilation from the `@Component` that installs the module. But this is a point, just wanted to correct the record.

**Comment by ronshapiro** [comment]
I think this fits under #869 -- this could be a custom module method annotation

**Comment by devindi** [comment]
Hi guys,

I tried to use repeatable annotations from java 8 and I faced with issue.

Firstly I defined my custom annotation as map key like this (from tutorial):
```
enum MyEnum {
  ABC, DEF;
}

@MapKey
@interface MyEnumKey {
  MyEnum value();
}
```
After that I tried to bind same object to a few keys:

```
@Provides @IntoMap
  @MyEnumKey(MyEnum.ABC)
  @MyEnumKey(MyEnum.DEF)
  static String provideAbcOrDefValue() {
    return "value for ABC or DEF";
  }
```
Compiler said me that I should mark my annotation with [Repeatable](https://docs.oracle.com/javase/8/docs/api/java/lang/annotation/Repeatable.html) one
This annotation this available since API level 24 so I can't use multiple keys in my project.

Even in 2k19 we should support devices with API level 19 or even API level 17 so it would be great to support multiple keys from dagger's side.
