### ISSUE TITLE
Request: Dagger 2 inside a library?

### ISSUE THREAD

**Issue by jpgpuyo** [google/dagger#712]
Hello,

I have never used dagger 2 inside a library.
I try to avoid using dagger 2 using inside a library, because I don't like add dependencies inside a library if it is not strictly necessary, but, anyway, I would like to see a sample from dagger 2 inside a library.

For example, in https://github.com/Karumi/Rosie/ they are using dagger 1, but not dagger 2.
I think it would be nice if you can provide a official sample for this :)

Is it considered bad practice use dagger 2 inside a library?

Thank you,
Joaquim

**Comment by tbroyer** [comment]
Related: #636

**Comment by jpgpuyo** [comment]
Hello @tbroyer,
Thank you for the reference, but my intention is not expose components or modules to application.
The use of dagger 2 inside library should be transparent to application.

For example, imagine that I want to build a library to communicate with a bluetooth printer.
The library name will be named MyBluetoothPrinterLibrary.

In the application, I have a feature to search a bluetooth printer. When bluetooth printer is found, I want to store MAC address of bluetooth printer inside library (using shared preferences for example), because next time I open app, I don't want search MAC address another time. I want to ask MAC address to library.

In this case, I want to create a PreferencesUtil class to save MAC address and get MAC address.
If I want to apply singleton pattern for do this, I don't want to write the boilerplate code of singleton, although it is extremely easy make a singleton.

My best approach is create a MyBluetoothPrinterLibraryComponent when I call method MyBluetoothPrinterLibrary.initialize(), usually called in onCreate method from Application class.

I have a lot of work, but I would like to make a sample with this :)

**Comment by trevjonez** [comment]
IMO the most user friendly way to offer this without library lock in would be to setup your library with nothing but JSR330 annotations and offer an extra aar/jar that would include perhaps a preconfigured set of modules and/or (sub)components.

At that point the api your main library depends on is `javax.inject:javax.inject:1` rather than the dagger jar.

It may be better to specify a custom scope for your library components rather than specify it as a singleton that way the consuming codebase can control the life cycle anyway they see fit while you are still able to indicate you designed it with scoping in mind.

**Comment by ronshapiro** [comment]
These are all good suggestions. In your first question, with a library that compiles against dagger1, you can request that they compile against Dagger2 as well so that applications that need either will work.

This is probably better for StackOverflow, so please move it there.

**Comment by jpgpuyo** [comment]
Ok, thank you for all the suggestions!
