### ISSUE TITLE
Add implementations of component default methods.

### ISSUE THREAD

**Issue by JakeWharton** [google/dagger#74]
They can break the contract of a component's scope otherwise.

``` java
@Module
public class NetworkModule {
  @Provides @Singleton
  OkHttpClient provideOkHttpClient() {
    return new OkHttpClient();
  }
}
```

``` java
@Singleton
@Component(modules = NetworkModule.class)
interface ApiComponent {
  OkHttpClient client();

  default TwitterApi api() {
    return new TwitterApi(client());
  }
}
```

``` java
ApiComponent apiComponent = Dagger_ApiComponent.create();
System.out.println("true? => " + apiComponent.api() == apiComponent.api());
```

```
true? => false
```

With this, default methods would only be used in custom implementations of a component interface.

**Comment by cgruber** [comment]
I'm marking this as a 2.1 release issue to resolve Java 8 default method behavior.  In the mean-time it's specifically undefined behavior.

**Comment by netdpb** [comment]
Why wouldn't we treat default methods on `@Component` interfaces just like concrete methods on `@Component` classes? That is, don't override them because they're not abstract.

In your example @JakeWharton, I don't see why you would expect two calls to `api()` to return the same thing. You've provided `OKHttpClient` as a `@Singleton`, not `TwitterApi`. Even if you meant to provide `TwitterApi` as a `@Singleton`, the `api()` method doesn't read to me as a component provision method, because it's not abstract.
