### ISSUE TITLE
Inspecting BindingGraph from Separate Annotation Processor

### ISSUE THREAD

**Issue by Leland-Takamine** [google/dagger#773]
We’re currently investigating ways to simplify our DI patterns at Uber. One option we’re evaluating is extending Dagger with our own API that assumes some of our common patterns (one module per component for example). Our annotation processor would process this new API and generate a Dagger implementation under the hood, which would then be processed by Dagger’s annotation processor.
 
Part of a potential implementation would involve leveraging Dagger's BindingGraph logic in order to calculate the transitive dependencies. We’re considering having our annotation processor depend on Dagger’s annotation processing API (dagger-compiler) with the aim of somehow building an instance of a BindingGraph programmatically.
 
**Questions**
* Is it possible to get an create an instance of Dagger’s BindingGraph from another annotation processor?
* If not, would you be open to a contribution that exposes a way to do this? Seems like it could be useful for analysis use cases as well.

**Comment by cgruber** [comment]
You can't see one processor's objects from another without a fair amount of
risk that javac will close that loophole.  I don't believe the annotation
processing environment supports it.

I know there has been talk of creating an internal API for "plugins" to the
dagger processor which would allow inspection of the binding graph, and
this might allow for the plugin to generate additional artifacts which
could potentially be consumed by another processor - or you could implement
your own generation as that plugin.  Ideally dagger's own validation could
then be implemented on top of this, so dagger woudl be its own internal
APIs first customer.

That said, it is a long-term idea, and not one that has any staff
allocation.  But it might be useful to discuss use-cases and requirements,
so that they could be taken into account in any such design.

(Disclaimer: I am no longer a full time Dagger team member, just a heavy
user, so what I'm saying reflects discussions with some stakeholders,
community members, and with members of the dagger team, and should NOT be
considered any sort of commitment)

**Comment by cgruber** [comment]
I would also suggest that we open a dialogue around why subcomponents
aren't working for you.  That seems like something worth figuring out.

**Comment by Leland-Takamine** [comment]
> I would also suggest that we open a dialogue around why subcomponents
aren't working for you.  That seems like something worth figuring out.

We have a component graph that spans many modules:
<img src="https://user-images.githubusercontent.com/847683/27159982-b6530276-5125-11e7-9964-b67896fac5e6.png" width=200 height=200 />

Since Subcomponents merge all of the component implementations into a single file, most of the work is deferred until the root module is processed. Additionally, this causes certain changes in leaf modules to trigger builds of all ancestor modules unnecessarily. These issues end up increasing our incremental build times.

**Comment by naturalwarren** [comment]
Seems like this should be in a new issue now. Was there any public discussion regarding this previously?

**Comment by Leland-Takamine** [comment]
To clarify - not looking for solutions to the `@Subcomponent` issues in this thread. Just wanted to give more context to the original question.

> Was there any public discussion regarding this previously?

I don't think there's any issue tracking this, but I'd be surprised if there's way to fix this without drastically changing the way `@Sucbomponents` work.

**Comment by ronshapiro** [comment]
Let me clarify some of the things that have been mentioned so far.

There's no way to create `BindingGraph` from other code, and we don't plan to support it. The `BindingGraph` code is very complicated and relies on a lot of other validation in our code. It only makes sense in the context of a component or subcomponent that already exists.

What we are working on is a way that, from another processor, you can get a handle to a `BindingGraph` object for a component that already exists, and apply your own custom validation/reporting to it, before Dagger generates the code for it. You could conceivably generate a massive component with every module/entrypoint available, retrieve that binding graph, and then construct your own new component from that (which would then trigger Dagger to implement that derived component). But that sounds quite convoluted, and the massive component would probably be invalid anyway.

**Comment by netdpb** [comment]
Specifically, what we're working on is an SPI that would let you plug into
the Dagger annotation processor and inspect the binding graph (not
BindingGraph, but another type) after we validate but before we generate
code. With that you'd be able to add additional validation or do other code
generation. You would not be able to modify the binding graph or the code
that Dagger generates.

I'm not sure about whether what you're trying to do with component
dependencies is the right solution to your problem, but the SPI might help
you do it. :)

**Comment by Leland-Takamine** [comment]
Thanks for the feedback all - opted to structure our API in a way that does not require parsing Dagger's API manually.
