### ISSUE TITLE
Redundant cast in generated component

### ISSUE THREAD

**Issue by NightlyNexus** [google/dagger#789]
I have a redundant cast in one of my generated component implementations:
`this.provideFooProvider = DoubleCheck.provider((Provider) provideRealFooProvider);`
where Foo is an interface and RealFoo is the concrete type.

```java
@Module public abstract class FooModule {
  @AppScope @Provides static RealFoo provideRealFoo() {
    return Foo.create();
  }

  @AppScope @Binds abstract Foo provideFoo(RealFoo realFoo);
}
```

This is such a minor thing, and it doesn't end up in the bytecode. Totally close this if it's uninteresting.

**Comment by ronshapiro** [comment]
Is `RealFoo` public? How about `Foo`?

**Comment by NightlyNexus** [comment]
RealFoo is package-private (in the same package as the FooModule), and Foo is public.

**Comment by ronshapiro** [comment]
And the component is in a different package? Is there any more of the
generated code you can share? The field declarations would be great

**Comment by gk5885** [comment]
This looks like the intersection between two things.  The first, which I think is what @ronshapiro is getting at, is that we do some casts just to dodge accessibility restrictions.  If we can't hold a reference to `Provider<RealFoo>` because it's not visible from the component, we hold a reference to `Provider` instead.  That's why we're seeing raw `Provider` at all.

In this case, I'm guessing that your fields are
```
Provider<Foo> provideFooProvider;
Provider provideRealFooProvider;
``` 
since we couldn't reference `RealFoo` in the component source.

The other bit is how `@Binds` (currently) works.  For better or worse, all of our original generics were done without wildcards.  At the time, it was never a problem, so it was the reasonable thing to do.  If you want a `Provider` for `Foo`, you'd always have a type that implemented `Provider<Foo>`.  Then, we introduced `@Binds` as a safe delegation, but in order to actually do the assignment in a typesafe way, we'd have to change `Provider<Foo>` to `Provider<? extends Foo>` so that we could use the `Provider<RealFoo>` in its place.  So, in the cases where we need to assign one `Provider` to another, we rely on some casts that we know to be safe.  Maybe someday we try to make the wildcards work, but the binding graph already verifies that it'll work, so we didn't bother.

Anyway, I think that the reason we have a redundant cast here is that the raw type that we use for accessibility and the cast to a raw type that we use to make `@Binds` work without wildcards are both raw `Provider`.  So, two independent mechanisms that are necessary for the component implementation just happen to be doing the same thing in this case.

If we were to really try to "fix" it, I think we'd want wildcards for `Provider` and make `@Binds` more typesafe.  I don't think it'd be worth trying to just get rid of the extra cast.

**Comment by NightlyNexus** [comment]
Yes, my component is in a different package, and those are my fields.

Oh, that makes sense. Thank you for the fantastic explanation! I appreciate it! I was super curious about the cause.
🌟

**Comment by TWiStErRob** [comment]
@ronshapiro @gk5885 I just ran into this while upgrading from 2.16 to 2.23.2. If you're not going to go with `? extends` would it make sense to at least `@SuppressWarnings("cast")` on that method so we can use `-Werror` on our codebases?

---

By the way, if someone find this issue, the **TL;DR workaround** is to open up the visibility of the implementation (so that the generated component can access it):
```diff
package a;
@Module
public class MyModule {
    @Binds
    Interface bind(Implementation impl);
}

package a;
public interface Interface {}

package a;
-class Implementation implements Interface {}
+public class Implementation implements Interface {}

package b;
import a.MyModule;
@Component(modules = {MyModule.class})
```

---

Exact error message that lead me here for SEO:
```
> Task :app:compileDebugJavaWithJavac
C:\dev\app\build\generated\source\kapt\debug\a\DaggerAppComponent.java:5986:
warning: [cast] redundant cast to Provider
        this.bindProvider = DoubleCheck.provider((Provider) implementationProvider);
```
