### ISSUE TITLE
Shade the compiler jar

### ISSUE THREAD

**Issue by JakeWharton** [google/dagger#79]
The compiler should be self-contained so as to not cause dependency resolution problems with our upstream library usage choices.

Cross filed for v1 at https://github.com/square/dagger/issues/451.

**Comment by cgruber** [comment]
So, #118 does an initial cut of this.  Because javawriter is the .v3 fork that was always in Dagger 2, it's sort of pre-shaded.  This doesn't shade guava, but most importantly shades auto-common, which we've seen collide with autovalue and autofactory in the wild.

I'd like to shade more of guava, but it'll have to wait until we stop using literals in the code-gen.  I'm going to mark this closed, as the compiler jar is shaded, and we can re-open or open new issues as problems arise.
