### ISSUE TITLE
Dagger "HasFragmentInjector" with sub fragments is problematic

### ISSUE THREAD

**Issue by Chrylo** [google/dagger#791]
Hey, we are using DaggerFragments with Dagger 2.11 + SubFragments. The SubFragment inherits some dependencies from the parent fragment. When using `AndroidInjector.inject(this)` the sub fragment searches for its parent via `.getParentFragment`. This returns null because we are not using `getChildFragmentManager` for the navigation. We have a complex navigation stack which would be difficult to refactor if we want to use multiple fragment managers. The only advantage I can see right now for the `getChildFragmentManager`, is having a reference to the parentFragment.

Is there a possibility to work around this issue. Maybe using setTargetFragment or something? Thanks.

**Comment by ronshapiro** [comment]
IIUC, you have many fragments which are all added from `Activity.getFragmentManager()`? But you want Fragment A's component to be a parent of Fragment B's component?

If that's the case, I recommend that you write your own `AndroidInjection.inject()` method for your use case. You'll also have to implement the logic in `DaggerFragment`, but it's intentionally small so that it is easy to do. https://google.github.io/dagger/android can help

**Comment by Chrylo** [comment]
Thanks for the help :)
