### ISSUE TITLE
Detect duplicate module declarations on component

### ISSUE THREAD

**Issue by NightlyNexus** [google/dagger#835]
`@Component(modules = { AppModule.class, AppModule.class }` works fine, but perhaps it would be nice to detect and warn about confusing duplicate declarations like this?

**Comment by ronshapiro** [comment]
This has come up a lot, not sure how valuable it would be. Especially since `@Module.includes` lists are likely to include duplicates - would you want to track those too, or just the "top-level"?

Worth noting that it would be pretty easy to do as a separate processor (and also when we have the SPI ready @netdpb)

**Comment by ronshapiro** [comment]
I'm going to close this, I don't think it's high enough priority.
