### ISSUE TITLE
Is there any way to avoid boilerplate for Activity's module when using @ContributesAndroidInjector?

### ISSUE THREAD

**Issue by tseglevskiy** [google/dagger#967]
In simple case I create for every activity or service some boilerplate like this:

```
@Module
public abstract class MainActivityModule {
    @ContributesAndroidInjector
    abstract MainActivity contributeActivityInjector();
}
```

Is it possible to generate this boilerplate by annotation directly from Activity? Manual creating of this has no meaning.

**Comment by ronshapiro** [comment]
There's nothing builtin and I don't think this is directly appropriate for the `dagger.android`, but it shouldn't be hard to write an annotation processor that would do this. I'm sure you could find users if you wrote it!

**Comment by JonathanMerritt** [comment]
@ronshapiro 

Apologies if you'd rather have this on SO. Just let me know and I'll do that.


I've been wanting to try this out, making a simple processor that can handle things like the one mentioned here.

If someone has close to zero experience with writing an annotation processor, would this be something they could do? Only asking because I looked thru some of the internals for dagger and they are all way over my head...

A basic outline of what I'd want to do for now...


**@AutoBind(component = "Component to place the binding on", modules = "Any included modules for the binding")** 

This will be used by an activity or fragment. 

Then ~somehow~ use it to write a @Contribute method for the class onto the supplied component and include any supplied modules.

If writing to an existing component is an issue or just not correct, only guessing if so. I suppose having the annotation write a new module that can then be manually included to the necessary component would also work.


I'm not asking for you to tell me how, just if in your opinion it may be too intensive for a beginner? And or if you know of one, possibly point me to a decent example to learn from. 

Whenever you have time,
Thanks,
Jon.
